-- Migration : Transport intrahospitalier des patients à risque vital (SRLF/SFAR/SFMU, RFE 2011)
-- Source : rfe-sfar-website/build/content_transport_intrahospitalier.json (99 blocs -> 99 recommandations)
-- Méthodologie source : RAND/UCLA à deux tours, un seul niveau de force ("accord fort"/"accord faible"),
-- PAS de grade de preuve GRADE. Les 99 propositions de cette synthèse ont TOUTES recueilli un accord
-- fort (vérifié exhaustivement par le pipeline fiche d'origine, aucune occurrence de "faible") : la
-- colonne grade est donc constante ('Fort') par fidélité à la source, pas une valeur par défaut devinée.
-- Statut : toutes les lignes sont insérées en 'draft' — jamais 'active' : la relecture/validation humaine
-- (contrainte recommendations_active_requires_review) reste à faire par un relecteur puis un validateur.

insert into public.documents (title, doc_type, original_language, publication_date, source_url, pdf_url, grading_system, freshness_status)
values (
  'Transport intrahospitalier des patients à risque vital (nouveau-né exclu)',
  'RFE', 'fr', '2011-01-01',
  'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf',
  'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf',
  'RAND/UCLA à deux tours (accord fort/faible, pas de grade de preuve GRADE)',
  'a_jour'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf'
  and s.acronym = 'SFAR' and s.country_or_region = 'France'
on conflict do nothing;
-- À VÉRIFIER : SRLF et SFMU, également co-signataires (cf. content_transport_intrahospitalier.json), ne
-- sont pas dans le seed Annexe B (build/library_final.json) sous une entrée pré-existante distincte de
-- SFAR pour ce document ; seule SFAR est liée ici. Ajouter SRLF/SFMU à document_societies quand leur
-- statut de validation (societies.vetting_status) aura été tranché.

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf'
  and s.slug in ('anesthesie_reanimation', 'medecine_intensive_reanimation', 'medecine_d_urgence')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.source_section,
  'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf',
  'draft'
from public.documents d, (values
  ('MG-ANES-000001-R01', 'Les patients à risque vital, hospitalisés ou non en réanimation, nécessitent fréquemment un TIH pour une procédure diagnostique, thérapeutique ou une admission dans une unité spécialisée.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 1'),
  ('MG-ANES-000001-R02', 'Les patients à risque vital regroupent l''ensemble des patients présentant au moins une défaillance ou menace de défaillance vitale.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 2'),
  ('MG-ANES-000001-R03', 'Il faut standardiser les définitions des EI et de leur évitabilité au cours du TIH.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 3'),
  ('MG-ANES-000001-R04', 'Les EI sont classés selon leur gravité en deux catégories : les EIG et les EPR.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 4'),
  ('MG-ANES-000001-R05', 'Un EIG est une complication directement liée aux soins, pouvant entraîner un risque vital, une prolongation de séjour, la nécessité de gestes invasifs et des séquelles invalidantes.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 5'),
  ('MG-ANES-000001-R06', 'Les EPR sont définis par le décret sur l''accréditation des médecins exerçant dans les spécialités à risque : ils regroupent tous les EI à l''exclusion des EIG (EI patients mineurs, dysfonctions du matériel et/ou de l''organisation).', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 6'),
  ('MG-ANES-000001-R07', 'Des incidents sans gravité surviennent régulièrement lors du transport : il faut définir précisément les EIG/EPR les plus fréquents pour mettre en place des procédures de surveillance et des mesures correctrices.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 7'),
  ('MG-ANES-000001-R08', 'Un EI survenant pendant le transport, nécessitant une intervention thérapeutique et résolutif après, doit être considéré comme un EPR.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 8'),
  ('MG-ANES-000001-R09', 'Un EI nécessitant une intervention thérapeutique qui ne permet pas de corriger l''anomalie selon l''objectif fixé par le clinicien doit être considéré comme un EIG.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 9'),
  ('MG-ANES-000001-R10', 'Un EPR compliqué d''une auto-extubation et/ou d''un arrêt cardiaque est un EIG.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 10'),
  ('MG-ANES-000001-R11', 'Une désaturation nécessitant une augmentation de FiO2 ou un autre réglage du ventilateur est un EPR ; c''est un EIG dès lors qu''elle n''est pas corrigée et reste sous l''objectif fixé par le clinicien.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 11'),
  ('MG-ANES-000001-R12', 'Une baisse de la pression artérielle nécessitant un geste thérapeutique est un EPR ; c''est un EIG dès lors que le traitement n''atteint pas l''objectif fixé.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 12'),
  ('MG-ANES-000001-R13', 'Un état d''agitation ou une désadaptation du respirateur nécessitant un geste thérapeutique est un EPR ; c''est un EIG s''il n''est pas corrigé par la mesure thérapeutique.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 13'),
  ('MG-ANES-000001-R14', 'Un problème lié au ventilateur nécessitant une modification de réglage, une ventilation au BAVU ou un changement de matériel est un EPR.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 14'),
  ('MG-ANES-000001-R15', 'Un problème lié au ventilateur qui se complique d''un événement clinique est un EIG.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 15'),
  ('MG-ANES-000001-R16', 'Les arrachements de matériels (cathéters, drain, pression intracrânienne...) sont des EPR sans conséquence clinique directe ; ce sont des EIG dès lors qu''ils sont compliqués.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 16'),
  ('MG-ANES-000001-R17', 'Un EI survenant lors du TIH doit être considéré comme inévitable lorsque l''ensemble de la procédure a été réalisé conformément à l''état de l''art.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 17'),
  ('MG-ANES-000001-R18', 'Les procédures de sécurisation (« safety practices ») sont des procédures de soins et/ou structurelles/organisationnelles qui préviennent, diminuent la fréquence ou atténuent les conséquences des erreurs et des EI survenant lors du TIH.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 18'),
  ('MG-ANES-000001-R19', 'Il faut faire un signalement des EI pouvant survenir pendant le TIH, qui devront ensuite être analysés.', 'Fort', 'Champ 1 — Épidémiologie des événements indésirables (EI), proposition 19'),
  ('MG-ANES-000001-R20', 'Le choix de l''équipement doit prendre en compte son encombrement et son autonomie.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 1'),
  ('MG-ANES-000001-R21', 'Il faut vérifier toutes les connexions entre les matériels de monitorage (ex. capteurs de pression invasive) avant le TIH.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 2'),
  ('MG-ANES-000001-R22', 'Le monitorage minimum durant un TIH comprend la fréquence cardiaque électrocardioscopique, l''oxymétrie de pouls et la pression artérielle non invasive.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 3'),
  ('MG-ANES-000001-R23', 'Chez le patient non ventilé, la fréquence ventilatoire doit être surveillée à intervalle régulier, au mieux de façon monitorée.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 4'),
  ('MG-ANES-000001-R24', 'Le monitorage de l''EtCO2 est recommandé pour les patients ayant une souffrance neurologique et pour ceux nécessitant un contrôle strict de la PaCO2.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 5'),
  ('MG-ANES-000001-R25', 'Les principaux paramètres monitorés doivent être couplés à des alarmes dont le réglage est adapté à chaque patient.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 6'),
  ('MG-ANES-000001-R26', 'Il faut un matériel dédié au TIH et identifié au niveau d''une structure de soins, d''un service ou d''un pôle.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 7'),
  ('MG-ANES-000001-R27', 'Le ventilateur de transport doit disposer d''alarmes sonores et visuelles sur les principaux paramètres ventilatoires monitorés.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 8'),
  ('MG-ANES-000001-R28', 'Pour tout patient ventilé lors d''un transport long ou à risque particulier, il faut disposer immédiatement d''un système d''aspiration, au mieux un appareil électrique autonome portable.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 9'),
  ('MG-ANES-000001-R29', 'Il faut adapter l''autonomie en électricité et en gaz médicaux à la durée du TIH et à la consommation, et en surveiller l''autonomie restante.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 10'),
  ('MG-ANES-000001-R30', 'Les moyens de monitorage doivent être adaptés au type de transport, à la sévérité du patient et aux thérapeutiques utilisées, selon une procédure écrite.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 11'),
  ('MG-ANES-000001-R31', 'La ventilation manuelle au ballon autogonflable doit être évitée lors d''un TIH, et n''être utilisée qu''en cas de panne du ventilateur (y compris chez l''enfant).', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 12'),
  ('MG-ANES-000001-R32', 'Le réglage des consignes machine du ventilateur de transport doit permettre les mêmes paramètres de ventilation, y compris les modes non invasifs.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 13'),
  ('MG-ANES-000001-R33', 'Tout patient ventilé lors d''un TIH doit pouvoir être repris à tout moment, en ventilation au ballon sur sa prothèse endotrachéale ou au masque.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 14'),
  ('MG-ANES-000001-R34', 'Les performances réelles du ventilateur de transport doivent être connues de l''utilisateur, selon trois catégories : basique/secours (mode VC, PEP, monitorage réduit) ; intermédiaire (mode VAC, PEP, réglage du débit ou de l''I/E, spirométrie expiratoire, réglage FiO2 100 %/mélange air-oxygène) ; haute performance (modes volumétriques/barométriques dont VS-AI-PEP, large plage de réglage de la FiO2, réglage du débit d''insufflation, triggers performants, spirométrie expiratoire, au mieux compensation de la compliance du circuit, mode VNI).', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 15'),
  ('MG-ANES-000001-R35', 'La performance, le monitorage et les alarmes du ventilateur doivent être adaptés à la pathologie : patient très hypoxémique (ex. SDRA) → haute performance ; contrôle strict de la PaCO2 ou modes assistés → intermédiaire/haute performance ; patient en VNI → option VNI performante.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 16'),
  ('MG-ANES-000001-R36', 'Le mode d''alimentation électrique et de recharge du ventilateur doit être compatible avec son utilisation à tout moment et avoir une autonomie suffisante.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 17'),
  ('MG-ANES-000001-R37', 'Le ventilateur utilisé doit disposer d''une alarme de défaut d''alimentation en gaz, en électricité, et d''une alarme de panne.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 18'),
  ('MG-ANES-000001-R38', 'L''interface du ventilateur de transport ne doit pas permettre de déréglages accidentels des consignes machine.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 19'),
  ('MG-ANES-000001-R39', 'À performances comparables, le ventilateur ayant l''interface la plus simple et le circuit patient le plus simple doit être privilégié.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 20'),
  ('MG-ANES-000001-R40', 'Pour vérifier la bonne tolérance de la ventilation et la stabilité du malade, le ventilateur de transport doit être branché sur le patient 5 à 10 minutes avant le départ réel, sur les gaz muraux et l''alimentation secteur.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 21'),
  ('MG-ANES-000001-R41', 'Le ventilateur de transport doit être stocké dans un endroit accessible connu des utilisateurs, avec ses accessoires (circuit complet avec ECH et raccord annelé, tuyau d''alimentation en gaz médicaux).', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 22'),
  ('MG-ANES-000001-R42', 'Le circuit utilisé doit être en accord avec les recommandations du fabricant.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 23'),
  ('MG-ANES-000001-R43', 'Lorsque le ventilateur le nécessite, il doit être étalonné en fonction du type de circuit utilisé.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 24'),
  ('MG-ANES-000001-R44', 'Un filtre antibactérien et échangeur de chaleur et d''humidité (ECH) doit être systématiquement mis en place entre le raccord annelé et le circuit patient.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 25'),
  ('MG-ANES-000001-R45', 'Le réglage des consignes machine et des alarmes du ventilateur de transport doit faire l''objet d''une prescription écrite.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 26'),
  ('MG-ANES-000001-R46', 'Le monitorage de la ventilation par le ventilateur de transport doit comporter au minimum la surveillance de la pression d''insufflation (pic) et la spirométrie expiratoire.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 27'),
  ('MG-ANES-000001-R47', 'Une auto-extubation doit pouvoir être identifiée immédiatement par le monitorage de la capnographie et/ou de la spirométrie expiratoire.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 28'),
  ('MG-ANES-000001-R48', 'L''analyse de la phase expiratoire du capnogramme peut aider à identifier certaines complications de la ventilation au cours du transport.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 29'),
  ('MG-ANES-000001-R49', 'En mode VS-AI-PEP (invasive ou non), le ventilateur de transport doit avoir les caractéristiques générales requises (performances, monitorage) pour garantir la qualité de ventilation.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 30'),
  ('MG-ANES-000001-R50', 'Certains ventilateurs de transport proposent des modes pouvant évoquer la VS-AI-PEP mais qui n''en sont pas réellement : il ne faut pas les utiliser.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 31'),
  ('MG-ANES-000001-R51', 'En mode CPAP, les systèmes à débit libre indépendants des ventilateurs doivent être utilisés en tenant compte de leur consommation d''oxygène importante, ce mode n''étant pas assez performant sur les ventilateurs de transport.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 32'),
  ('MG-ANES-000001-R52', 'Un dispositif de mesure invasive et continue de la pression artérielle doit être utilisé lors du TIH si le patient est traité par des agents vaso-actifs et/ou en cas d''instabilité hémodynamique, et s''il en bénéficie déjà dans son unité.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 33'),
  ('MG-ANES-000001-R53', 'Le monitorage de la pression veineuse centrale n''est pas recommandé lors du TIH.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 34'),
  ('MG-ANES-000001-R54', 'Un stimulateur-défibrillateur doit être facilement accessible au cours du transport ; au mieux, il s''intègre dans un moniteur multiparamétrique.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 35'),
  ('MG-ANES-000001-R55', 'Si le patient est dépendant d''un pacemaker externe, les seuils de celui-ci doivent être impérativement vérifiés et adaptés, ainsi que l''état de la batterie ; un pacemaker externe de rechange doit être impérativement disponible.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 36'),
  ('MG-ANES-000001-R56', 'En présence d''électrodes de stimulation péricardiques temporaires, un stimulateur de transport doit être impérativement connecté.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 37'),
  ('MG-ANES-000001-R57', 'Le remplacement dans les meilleurs délais d''un matériel indisponible (maintenance, panne) doit être organisé selon une procédure écrite.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 38'),
  ('MG-ANES-000001-R58', 'Les matériels utilisés pour le TIH doivent faire l''objet d''une procédure de contrôle régulière et tracée (check-list).', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 39'),
  ('MG-ANES-000001-R59', 'Après utilisation, le ventilateur doit être nettoyé et désinfecté selon une procédure écrite et tracée.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 40'),
  ('MG-ANES-000001-R60', 'Lors d''un TIH pédiatrique, un jeu complet de matériel et de médicaments de réanimation pédiatrique doit accompagner l''enfant, notamment un ballon autogonflable, un masque facial et du matériel d''intubation adaptés à l''âge, ainsi que du matériel de cathétérisme intra-osseux.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 41'),
  ('MG-ANES-000001-R61', 'Le monitorage de l''EtCO2 est recommandé lors du transport en cas de ventilation manuelle d''un enfant intubé, pour prévenir le risque d''hyperventilation.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 42'),
  ('MG-ANES-000001-R62', 'Pour les enfants de moins de 15 kg, il est nécessaire d''avoir un ventilateur pouvant délivrer des volumes courants faibles, assurer des fréquences élevées et permettre le maintien d''une pression positive de fin d''expiration.', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 43'),
  ('MG-ANES-000001-R63', 'La taille et la compliance des tuyaux du circuit doivent être adaptées à l''âge et au poids de l''enfant pour réduire au maximum le volume compressible (petits tuyaux pour un poids inférieur à 15 kg).', 'Fort', 'Champ 2 — Matériels, monitorage et maintenance (44 propositions), proposition 44'),
  ('MG-ANES-000001-R64', 'Il faut faire une évaluation précise de l''état clinique du patient avant le départ pour un TIH et évaluer le bénéfice/risque du transport ; ces éléments doivent être colligés dans le dossier médical.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 1'),
  ('MG-ANES-000001-R65', 'Il faut vérifier l''absence de contre-indication aux examens complémentaires.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 2'),
  ('MG-ANES-000001-R66', 'Le patient doit être porteur d''un bracelet d''identification.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 3'),
  ('MG-ANES-000001-R67', 'Il faut au minimum un abord veineux perméable et, si nécessaire, une voie supplémentaire spécifiquement dédiée aux amines et identifiée ; les voies d''abord doivent être propres et solidement fixées.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 4'),
  ('MG-ANES-000001-R68', 'Les pousse-seringues électriques doivent être identifiés et la quantité des thérapeutiques adaptée à la durée du TIH ; les cordons d''alimentation doivent être présents durant le transport et rebranchés sur secteur dès que possible.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 5'),
  ('MG-ANES-000001-R69', 'Chez les patients nécessitant un contrôle strict de la PaCO2, un prélèvement artériel doit être réalisé avant le TIH afin de mesurer le gradient PaCO2-EtCO2.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 6'),
  ('MG-ANES-000001-R70', 'Le monitorage de la pression de perfusion cérébrale (PPC) doit être poursuivi au cours du transport chez les patients neurologiques.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 7'),
  ('MG-ANES-000001-R71', 'La position optimale du patient en réanimation doit être poursuivie pendant le TIH.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 8'),
  ('MG-ANES-000001-R72', 'Il faut anticiper, évaluer et traiter les douleurs pouvant être induites par le TIH et/ou les soins qui seront réalisés.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 9'),
  ('MG-ANES-000001-R73', 'Il faut poursuivre la sédation et/ou l''analgésie durant le transport ; elle peut être modifiée le cas échéant.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 10'),
  ('MG-ANES-000001-R74', 'La mobilisation du patient curarisé doit faire l''objet de précautions particulières.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 11'),
  ('MG-ANES-000001-R75', 'Le matériel d''intubation complet (comprenant un mandrin d''Eschmann) doit être disponible immédiatement.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 12'),
  ('MG-ANES-000001-R76', 'À chaque mobilisation du patient, la vérification de la bonne position des dispositifs invasifs doit être effectuée.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 13'),
  ('MG-ANES-000001-R77', 'Un BAVU avec masque adapté, réservoir d''oxygène, prolongateur d''O2 et filtre de rechange doivent accompagner le patient.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 14'),
  ('MG-ANES-000001-R78', 'Il faut prévenir l''hypothermie pendant le TIH, notamment chez l''enfant où la température devra être monitorée.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 15'),
  ('MG-ANES-000001-R79', 'Le matériel à usage unique doit être privilégié.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 16'),
  ('MG-ANES-000001-R80', 'La pression du ballonnet du dispositif intratrachéal doit être vérifiée avant et au retour du TIH.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 17'),
  ('MG-ANES-000001-R81', 'Un sac d''intervention d''urgence doit accompagner le patient.', 'Fort', 'Champ 3 — Préparation du malade avant transport (18 propositions), proposition 18'),
  ('MG-ANES-000001-R82', 'Une formation initiale et régulière est obligatoire pour l''ensemble des personnels assurant les TIH, sur le fonctionnement et la surveillance des matériels utilisés (ventilateur, moniteur multiparamétrique, défibrillateur...).', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 1'),
  ('MG-ANES-000001-R83', 'Il faut une formation au transport pédiatrique, initiale et régulière, du personnel médical et paramédical assurant les TIH des enfants de moins de 15 kg.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 2'),
  ('MG-ANES-000001-R84', 'La formation des personnels en charge des TIH peut se faire sous la forme d''une simulation de transport.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 3'),
  ('MG-ANES-000001-R85', 'L''appréciation du risque et les modalités liées au TIH sont sous la responsabilité du médecin senior en charge du patient.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 4'),
  ('MG-ANES-000001-R86', 'L''équipe de TIH d''un patient à risque vital doit être composée au minimum d''un médecin expérimenté et d''une personne formée au TIH.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 5'),
  ('MG-ANES-000001-R87', 'Une procédure d''appel à l''aide pour un renfort médical et/ou infirmier doit être disponible et connue de tous en cas de problème lors du TIH.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 6'),
  ('MG-ANES-000001-R88', 'Un perfusionniste ou équivalent qualifié doit faire partie de l''équipe de TIH lorsque le patient est sous circulation extracorporelle (CEC).', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 7'),
  ('MG-ANES-000001-R89', 'Si le TIH est confié à l''équipe médicale du Smur, celle-ci doit bénéficier d''une transmission complète et précise sur l''état du patient par le médecin en charge, et d''un compte rendu écrit.', 'Fort', 'Champ 4 — Soignants : ressources humaines et formation (8 propositions), proposition 8'),
  ('MG-ANES-000001-R90', 'L''horaire, le lieu de rendez-vous ainsi que la durée d''immobilisation du patient doivent être précisés et vérifiés avant le TIH.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 1'),
  ('MG-ANES-000001-R91', 'Le nom du médecin et les moyens techniques à disposition sur le lieu d''accueil du patient doivent être connus.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 2'),
  ('MG-ANES-000001-R92', 'Avant de partir pour un TIH, il faut s''assurer de la connaissance du circuit emprunté et de l''accessibilité des couloirs et ascenseurs, en privilégiant le chemin le plus court et le plus sécurisé.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 3'),
  ('MG-ANES-000001-R93', 'Le service d''accueil est prévenu de l''arrivée imminente du patient.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 4'),
  ('MG-ANES-000001-R94', 'La traçabilité des paramètres monitorés lors du TIH doit faire l''objet d''un recueil spécifique sur une feuille de surveillance, ensuite intégrée au dossier du patient.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 5'),
  ('MG-ANES-000001-R95', 'Une traçabilité imprimable des données du monitorage au cours du TIH est souhaitable.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 6'),
  ('MG-ANES-000001-R96', 'Si le médecin qui accueille le patient est compétent pour assurer sa surveillance, l''équipe de TIH lui transmettra toutes les informations nécessaires.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 7'),
  ('MG-ANES-000001-R97', 'En l''absence d''un médecin compétent pour la surveillance du patient sur le lieu d''accueil, l''équipe du TIH en conservera la charge.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 8'),
  ('MG-ANES-000001-R98', 'L''organisation du TIH doit faire l''objet d''une procédure institutionnelle.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 9'),
  ('MG-ANES-000001-R99', 'Le TIH doit être un acte valorisé en termes d''activité.', 'Fort', 'Champ 5 — Organisation, architecture et traçabilité (10 propositions), proposition 10')
) as v(code, statement, grade, source_section)
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/09/2_AFAR_Transport-intrahospitalier-des-patients-a-risque-vital.pdf'
on conflict (recommendation_code) do nothing;
