-- Migration : Prise en charge des sujets en état de mort encéphalique dans l'optique d'un
-- prélèvement d'organes (SFAR/SRLF/Agence de la biomédecine, conférence d'experts 2005)
-- Source : rfe-sfar-website/build/content_mort_encephalique.json (142 recommandations/constats atomiques)
--
-- Méthodologie source : PAS de GRADE (1+/1-/2+/2-/AE) — cotation RAND/UCLA, médiane des votes du jury sur
-- une échelle 1-9 (zones : 1-3 désaccord, 4-6 indécision, 7-9 accord). Reproduite ici EXACTEMENT comme
-- publiée, y compris en notation décimale française pour les médianes à un demi-point ('7,5', '8,5' —
-- PAS un extrême dissident, cf. build/fiche_mort_encephalique.py pour le raisonnement de cette lecture,
-- confirmée par audit indépendant lors de la construction de la fiche). null quand le texte source
-- n'imprime aucun chiffre pour l'énoncé (jamais de cotation devinée).
--
-- Champ 'kind' NON stocké tel quel : les lignes extraites de target_table (objectifs numériques — ex.
-- pression artérielle moyenne, ventilation) et de reco_table (recommandations narratives) sont toutes
-- migrées comme des recommendations de plein droit ; source_section porte la distinction ('param.' vs 'réf.').

insert into public.documents (title, doc_type, original_language, publication_date, source_url, pdf_url, grading_system, freshness_status)
values (
  'Prise en charge des sujets en état de mort encéphalique dans l''optique d''un prélèvement d''organes',
  'RFE', 'fr', '2005-06-15',
  'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf',
  'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf',
  'RAND/UCLA (médiane des cotations 1-9 ; zones désaccord 1-3 / indécision 4-6 / accord 7-9), pas de GRADE',
  'a_jour'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf'
  and s.acronym in ('SFAR', 'SRLF') and s.country_or_region = 'France'
on conflict do nothing;

-- L'Agence de la biomédecine (ABM), 3e co-signataire (cf. content_mort_encephalique.json), n'existe pas
-- dans le seed Annexe B (qui liste explicitement "puis autres sociétés par spécialité" comme non
-- exhaustif, 14.1) — insérée ici, statut 'a_valider' comme tout le reste du seed, pas de nom développé
-- deviné au-delà de ce qui est déjà de notoriété publique (agence publique française, gestion des
-- greffes et du don d'organes) et déjà documenté dans build/fiche_mort_encephalique.py.
insert into public.societies (acronym, country_or_region)
values ('ABM', 'France')
on conflict (acronym, country_or_region) do nothing;
insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf'
  and s.acronym = 'ABM' and s.country_or_region = 'France'
on conflict do nothing;

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf'
  and s.slug in ('anesthesie_reanimation', 'medecine_intensive_reanimation')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, condition_topic, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.condition_topic, v.source_section,
  'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf',
  'draft'
from public.documents d, (values
  ('MG-ANES-000003-R001', 'Une anamnèse cohérente complète et un examen clinique neurologique sans ambiguïté sont essentiels pour porter le diagnostic de ME ; ces éléments doivent être consignés par écrit.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.1'),
  ('MG-ANES-000003-R002', 'Élimination systématique des facteurs confondants cliniques : hypothermie (température centrale < 35 °C), imprégnation médicamenteuse ou toxique susceptible d''interférer avec l''examen clinique.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.2'),
  ('MG-ANES-000003-R003', 'En l''absence de facteurs confondants, l''examen neurologique doit observer un coma non réactif (Glasgow à 3) associé à l''abolition des réflexes du tronc cérébral et de la ventilation spontanée.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.3'),
  ('MG-ANES-000003-R004', 'Épreuve d''hypercapnie sous oxygénothérapie efficace contrôlée par SpO2 (après ventilation en normocapnie) : atteindre en apnée une PaCO2 proche de 60 mmHg pour affirmer l''absence de mouvements respiratoires.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.4'),
  ('MG-ANES-000003-R005', 'Dans l''optique du don, le diagnostic clinique de ME doit être confirmé par un examen complémentaire exigé par la loi : soit deux EEG nuls et non réactifs pendant 30 minutes, effectués à 4 heures d''intervalle, soit une angiographie cérébrale objectivant l''arrêt de perfusion des 4 axes.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.5'),
  ('MG-ANES-000003-R006', 'La vélocimétrie Doppler transcrânienne n''a pas de valeur réglementaire pour le diagnostic de ME. Non invasive et répétable au lit du malade, elle est prédictive de ME avec une spécificité de 100 % et une sensibilité d''environ 90 % en visualisant un flux oscillant systolodiastolique (arrêt circulatoire cérébral).', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.6'),
  ('MG-ANES-000003-R007', 'Quand l''examen clinique est compatible avec la ME, l''examen Doppler peut permettre d''évoquer de manière rapide et précoce le diagnostic d''arrêt circulatoire cérébral.', '7', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.7'),
  ('MG-ANES-000003-R008', 'Cela permet la mise en route sans retard des procédures réglementaires de confirmation de ME et peut raccourcir le délai entre la mort et le prélèvement.', '8', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.7b'),
  ('MG-ANES-000003-R009', 'L''EEG (silence électrocérébral, amplitude < 5 µV) est le test de confirmation de ME prévu par la réglementation, à condition d''exclure l''influence de la sédation ou de troubles métaboliques.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.8'),
  ('MG-ANES-000003-R010', 'Avant d''utiliser les deux EEG comme moyen paraclinique, il convient de s''assurer que les dosages sanguins/urinaires ne décèlent aucun médicament du SNC à dose susceptible d''interférer avec l''interprétation de l''EEG — non coté dans le texte source.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.8b'),
  ('MG-ANES-000003-R011', 'L''hypothermie modérée (température voisine de 30 °C) n''empêche pas l''interprétation de l''EEG.', '7', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.8c'),
  ('MG-ANES-000003-R012', 'Cependant, en l''absence de donnée confirmant ce fait en contexte de ME, une hypothermie entre 30 et 35 °C peut gêner l''attestation de nullité de l''EEG — non coté dans le texte source.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.8d'),
  ('MG-ANES-000003-R013', 'Les potentiels évoqués (PE), intéressants chez les patients sédatés, n''ont pas de valeur réglementaire en France pour la confirmation de ME.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.9'),
  ('MG-ANES-000003-R014', 'L''angiographie cérébrale (voie artérielle ou veineuse) est la seconde méthode de confirmation prévue par la réglementation. L''angioscanner par voie veineuse est recommandé comme moyen de confirmation de l''arrêt circulatoire encéphalique.', '8', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.10'),
  ('MG-ANES-000003-R015', 'Le compte rendu écrit de l''examen électrophysiologique ou de l''angiographie doit être signé immédiatement par un médecin qualifié.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.11'),
  ('MG-ANES-000003-R016', 'En cas de ME clinique, adapter sans délai les méthodes de réanimation et contacter la coordination hospitalière (« donneur potentiel »).', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.12'),
  ('MG-ANES-000003-R017', 'La décision d''amener le sujet au prélèvement relève du médecin du donneur (absence d''opposition, absence de contre-indication générale) ; la décision de prélever tel ou tel organe relève uniquement du médecin transplanteur, via la coordination hospitalière.', '8', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.12b'),
  ('MG-ANES-000003-R018', 'L''accompagnement de la famille doit respecter et prendre en compte ses convictions religieuses et différences culturelles ; la qualité de l''accueil des familles et des proches est déterminante pour l''acceptation ou le refus du don.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.13'),
  ('MG-ANES-000003-R019', 'Les entretiens doivent se dérouler dans un local décent, permettant de faire asseoir les participants et de préserver l''intimité et la confidentialité.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.14'),
  ('MG-ANES-000003-R020', 'Ils interviennent après confirmation paraclinique de la ME et assurance par la coordination de la faisabilité des prélèvements.', '8', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.14b'),
  ('MG-ANES-000003-R021', 'Objectifs de l''entretien (non cotés dans le texte source) : annoncer le décès ; informer sur la ME, le don et sa finalité ; rechercher le refus de prélèvement exprimé du vivant du défunt.', null, 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.14c'),
  ('MG-ANES-000003-R022', 'L''entretien doit au mieux être mené à deux (le réanimateur et un membre de la coordination hospitalière), qui doivent se présenter à la famille.', '9', 'Chapitre 1 — La mort encéphalique : historique, concept et diagnostic', 'Chapitre 1 — Diagnostic de la mort encéphalique — Chapitre 1 — La mort encéphalique : historique, concept et diagnostic — réf. 1.15'),
  ('MG-ANES-000003-R023', 'Reconnaissance précoce de l''instabilité hémodynamique afin de permettre des mesures thérapeutiques immédiates. Conditionnement minimal de tout donneur potentiel : électrocardioscope, oxymétrie de pouls, cathétérisme de l''artère radiale (si possible gauche ou aux membres supérieurs), voie veineuse profonde, surveillance de la température centrale, sondage vésical.', '9', 'Chapitre 2 — Prise en charge en réanimation du donneur potentiel', 'Chapitre 2 — Réanimation du donneur (hémodynamique) — Chapitre 2 — Prise en charge en réanimation du donneur potentiel — réf. 2.1'),
  ('MG-ANES-000003-R024', 'Il n''existe pas de signe clinique spécifique de l''hypovolémie au cours de la ME ; elle doit être dépistée précocement. Bien que non validée en contexte de ME, l''utilisation de critères dynamiques de réponse au remplissage vasculaire (lever de jambe passif, variabilité respiratoire de la pression artérielle, du flux aortique ou du diamètre de la veine cave supérieure en échocardiographie Doppler) est recommandée.', '8,5', 'Chapitre 2 — Prise en charge en réanimation du donneur potentiel', 'Chapitre 2 — Réanimation du donneur (hémodynamique) — Chapitre 2 — Prise en charge en réanimation du donneur potentiel — réf. 2.2'),
  ('MG-ANES-000003-R025', 'Le dépistage de la dysfonction myocardique repose sur l''échocardiographie Doppler, qui permet une meilleure prise en charge du donneur tout en évaluant la qualité du greffon cardiaque éventuel.', '9', 'Chapitre 2 — Prise en charge en réanimation du donneur potentiel', 'Chapitre 2 — Réanimation du donneur (hémodynamique) — Chapitre 2 — Prise en charge en réanimation du donneur potentiel — réf. 2.3'),
  ('MG-ANES-000003-R026', 'L''intérêt des marqueurs biologiques (créatinine kinase et fraction MB, troponine Ic, BNP/ProBNP) pour la reconnaissance d''une dysfonction myocardique est encore mal connu au cours de la ME.', null, 'Chapitre 2 — Prise en charge en réanimation du donneur potentiel', 'Chapitre 2 — Réanimation du donneur (hémodynamique) — Chapitre 2 — Prise en charge en réanimation du donneur potentiel — réf. 2.4'),
  ('MG-ANES-000003-R027', 'En cas de défaillance cardiocirculatoire non contrôlée, le recours à une technique d''exploration hémodynamique (échocardiographie, cathétérisme cardiaque droit, Doppler œsophagien, système Picco…), laissé au choix de l''opérateur, est recommandé.', '9', 'Chapitre 2 — Prise en charge en réanimation du donneur potentiel', 'Chapitre 2 — Réanimation du donneur (hémodynamique) — Chapitre 2 — Prise en charge en réanimation du donneur potentiel — réf. 2.5'),
  ('MG-ANES-000003-R028', '65 à 100 mmHg', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. Pression artérielle moyenne'),
  ('MG-ANES-000003-R029', '1 à 1,5 ml/kg/h', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. Diurèse'),
  ('MG-ANES-000003-R030', '35,5 à 38 °C', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. Température centrale'),
  ('MG-ANES-000003-R031', '> 80 mmHg', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. PaO2'),
  ('MG-ANES-000003-R032', '> 7 g/dl', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. Hémoglobine'),
  ('MG-ANES-000003-R033', 'normal', '7', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — param. Lactate artériel'),
  ('MG-ANES-000003-R034', 'Remplissage vasculaire (RV) modéré : cristalloïdes ou colloïdes indifféremment ; au-delà de 3 000 ml, utiliser les colloïdes plutôt que les cristalloïdes.', '7,5', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.6'),
  ('MG-ANES-000003-R035', 'Le contrôle précoce du diabète insipide permet d''éviter un RV massif, délétère pour un éventuel prélèvement pulmonaire ; compléter par des transfusions sanguines et traitements substitutifs si besoin.', null, 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.7'),
  ('MG-ANES-000003-R036', 'Le recours aux vasopresseurs, si nécessaire, repose en première intention sur la noradrénaline.', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.8'),
  ('MG-ANES-000003-R037', 'Traitement du diabète insipide : précoce, par desmopressine intraveineuse en fonction de la diurèse et, si nécessaire, compensation de la diurèse par un soluté adapté à l''osmolalité sanguine.', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.9'),
  ('MG-ANES-000003-R038', 'En cas de dysfonction myocardique : adjonction d''un inotrope (dobutamine) ou remplacement de la noradrénaline par de l''adrénaline.', '9', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.10'),
  ('MG-ANES-000003-R039', 'Certaines études montrent que l''hormonothérapie substitutive (hormone thyroïdienne, cortisol et arginine-vasopressine) apporterait un bénéfice hémodynamique chez le donneur et sur la qualité des greffons.', '7', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.10b'),
  ('MG-ANES-000003-R040', 'De plus, l''arginine-vasopressine pourrait permettre une réduction des besoins en catécholamines.', '6', 'Objectifs thérapeutiques recommandés — donneur potentiel', 'Chapitre 2 — Objectifs thérapeutiques — Objectifs thérapeutiques recommandés — donneur potentiel — réf. 2.10c'),
  ('MG-ANES-000003-R041', '35 à 40 mmHg', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. PaCO2'),
  ('MG-ANES-000003-R042', '80 à 100 mmHg', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. PaO2 (FiO2 minimale)'),
  ('MG-ANES-000003-R043', 'minimale, ≈ 5 cmH2O', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. PEP'),
  ('MG-ANES-000003-R044', 'contrôle régulier, avant transfert au bloc', null, 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. Rapport PaO2/FiO2'),
  ('MG-ANES-000003-R045', 'recommandées', '8,5', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. Manœuvres de recrutement alvéolaire'),
  ('MG-ANES-000003-R046', 'L''intérêt du scanner thoracique systématique n''a pas été évalué dans cette indication, mais le suivi radiologique thoracique peut anticiper les mesures correctives en cas de dégradation.', null, 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.11'),
  ('MG-ANES-000003-R047', 'Fibroscopie bronchique systématique si un prélèvement pulmonaire est envisagé (identification d''une cause réversible de dégradation de l''hématose). Une positivité de l''examen bactériologique direct ne contre-indique pas le prélèvement pulmonaire, en l''absence de pneumonie — non coté dans le texte source.', null, 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.12'),
  ('MG-ANES-000003-R048', 'La connaissance de la flore bactérienne du donneur oriente l''antibiothérapie prophylactique et curative des receveurs en cas de pneumonie bactérienne postopératoire précoce.', null, 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.13'),
  ('MG-ANES-000003-R049', 'Les perturbations de l''hémostase (CIVD, fibrinolyse, fibrinogénolyse) sont fréquentes au cours de la ME et sont liées à l''atteinte cérébrale.', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.14'),
  ('MG-ANES-000003-R050', 'Exploration de l''hémostase — 1er groupe de dosages : TP, TCA, fibrinogène, facteur V, plaquettes.', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.15'),
  ('MG-ANES-000003-R051', 'Exploration de l''hémostase — 2e groupe de dosages : D-dimères, complexes solubles.', '7', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.16'),
  ('MG-ANES-000003-R052', '> 50 G/l', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. Plaquettes'),
  ('MG-ANES-000003-R053', '> 1 g/l', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. Fibrinogène'),
  ('MG-ANES-000003-R054', 'TP > 40 % et TCA ratio < 1,5', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — param. TP / TCA'),
  ('MG-ANES-000003-R055', 'L''acceptabilité du donneur atteint d''affection bactérienne ou fongique reste controversée. Prélèvements bactériologiques standards (hémocultures, urocultures, prélèvements bronchiques) systématiques ; recherche précoce d''une documentation bactérienne pulmonaire, technique laissée au praticien.', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.17'),
  ('MG-ANES-000003-R056', 'Une infection avérée chez le donneur potentiel n''est pas une contre-indication formelle au prélèvement si l''agent pathogène est isolé et un traitement efficace instauré depuis au moins 24-48 h.', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.18'),
  ('MG-ANES-000003-R057', 'Chaque situation nécessite une évaluation du bénéfice/risque, notamment pour les germes à tropisme vasculaire.', '9', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.18b'),
  ('MG-ANES-000003-R058', 'En cas de prélèvement de poumons ou cœur-poumons : antibiothérapie par amoxicilline-acide clavulanique 1 g/8 h.', '8', 'Optimisation pulmonaire, hémostase, infection, pédiatrie', 'Chapitre 2 — Poumon, hémostase, infection, pédiatrie — Optimisation pulmonaire, hémostase, infection, pédiatrie — réf. 2.18c'),
  ('MG-ANES-000003-R059', 'Contre-indications réglementaires (sécurité sanitaire) : ESB ou maladie équivalente, infection par le VIH, le VHC ou le VHB, tuberculose active, syphilis — diverses dérogations validées ou en cours de discussion (notamment VHB et syphilis).', null, '3.1 — Critères communs à tous les organes', 'Chapitre 3 — Critères organes : général & cœur — 3.1 — Critères communs à tous les organes — réf. 3.1.1'),
  ('MG-ANES-000003-R060', 'Contre-indications médicales : cancers avérés ou métastasés (exception possible pour certaines tumeurs cérébrales).', null, '3.1 — Critères communs à tous les organes', 'Chapitre 3 — Critères organes : général & cœur — 3.1 — Critères communs à tous les organes — réf. 3.1.2'),
  ('MG-ANES-000003-R061', 'Évaluation au cas par cas du rapport risque/bénéfice : maladies de système, allergies, la plupart des intoxications, infections bactériennes, donneurs âgés.', null, '3.1 — Critères communs à tous les organes', 'Chapitre 3 — Critères organes : général & cœur — 3.1 — Critères communs à tous les organes — réf. 3.1.3'),
  ('MG-ANES-000003-R062', 'Données morphologiques requises pour chaque organe : si un scanner cérébral est pratiqué pour confirmer la ME, réaliser en même temps une tomodensitométrie thoraco-abdominale.', null, '3.1 — Critères communs à tous les organes', 'Chapitre 3 — Critères organes : général & cœur — 3.1 — Critères communs à tous les organes — réf. 3.1.4'),
  ('MG-ANES-000003-R063', 'L''examen clinique et l''anamnèse ne sont pas suffisamment sensibles/spécifiques pour l''évaluation du greffon ; évaluer la fonction et la structure du cœur par échographie transthoracique, complétée au moindre doute par une échographie transœsophagienne.', '9', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.1'),
  ('MG-ANES-000003-R064', 'Les anomalies ECG isolées (sus/sous-décalage ST, inversion de l''onde T, allongement du QT) ne sont pas à prendre en compte ; les arythmies ventriculaires répétitives sans anomalie hydroélectrolytique évidente sont en revanche de mauvais pronostic.', '7,5', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.2'),
  ('MG-ANES-000003-R065', 'L''absence de coronarographie au-delà de 55 ans ne doit pas être une contre-indication au prélèvement.', '8', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.3'),
  ('MG-ANES-000003-R066', 'L''utilisation de catécholamines n''est plus en soi une contre-indication au prélèvement cardiaque ; il est actuellement impossible de définir une dose seuil.', '9', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.4'),
  ('MG-ANES-000003-R067', 'Devant une altération de la fonction systolique chez un patient < 55 ans sans facteur de risque cardiopathique : réanimation agressive avant de décréter le cœur non prélevable.', '9', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.5'),
  ('MG-ANES-000003-R068', 'Dans ce cas, il est recommandé de pratiquer une nouvelle échographie cardiaque après chaque ajustement thérapeutique.', '7', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.6'),
  ('MG-ANES-000003-R069', 'Contre-indications absolues (7 des 8 critères cotés « 9 » ; voir 3.2.8 pour le 8e) : intoxication au CO (taux > 20 %), arythmies ventriculaires graves, infarctus du myocarde documenté (quelle que soit l''ancienneté), malformation cardiaque non corrigée, tumeur cardiaque, hypokinésie globale (FEVG < 0,3), lésions sévères en coronarographie.', '9', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.7'),
  ('MG-ANES-000003-R070', 'Contre-indication absolue supplémentaire : hypoxémie sévère (SaO2 < 80 %).', '7,5', '3.2 — Prélèvement cardiaque', 'Chapitre 3 — Critères organes : général & cœur — 3.2 — Prélèvement cardiaque — réf. 3.2.8'),
  ('MG-ANES-000003-R071', 'Antécédents respiratoires chroniques/tabagisme et examen clinique détaillé sont indispensables mais insuffisants pour la sélection pulmonaire ; évaluation régulière de l''hématose et de l''imagerie recommandée.', null, '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.1'),
  ('MG-ANES-000003-R072', 'La durée de ventilation n''est plus un critère de non-prélèvement, mais une analyse au cas par cas des conditions de ventilation et de colonisation des voies aériennes est indispensable.', '8', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.2'),
  ('MG-ANES-000003-R073', 'Une radiographie ou un scanner thoracique normal est un excellent critère de prélèvement.', '8', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.3'),
  ('MG-ANES-000003-R074', 'Optimiser la ventilation mécanique avant d''utiliser les critères d''imagerie et d''hématose.', '8,5', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.4'),
  ('MG-ANES-000003-R075', 'L''utilisation de catécholamines n''est plus un critère de non-prélèvement.', '9', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.5'),
  ('MG-ANES-000003-R076', 'Contre-indications absolues : âge du donneur > 70 ans ; opacités alvéolaires bilatérales non réversibles après fibroaspiration/déplétion hydrosodée/optimisation ventilatoire ; rapport PaO2/FiO2 < 250 après optimisation.', '9', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.6'),
  ('MG-ANES-000003-R077', 'Contre-indication absolue supplémentaire, non cotée dans le texte source : antécédents de maladie respiratoire chronique non réversible.', null, '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.7'),
  ('MG-ANES-000003-R078', 'Contre-indication absolue supplémentaire : ischémie froide > 8 heures.', '8', '3.3 — Prélèvement pulmonaire', 'Chapitre 3 — Poumon & foie — 3.3 — Prélèvement pulmonaire — réf. 3.3.8'),
  ('MG-ANES-000003-R079', 'La bonne qualité du greffon fourni par certains donneurs de 80 ans ou plus a été largement démontrée.', '8,5', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.1'),
  ('MG-ANES-000003-R080', 'Le diabète et l''HTA ne sont pas en soi des contre-indications ; l''éthylisme chronique ne contre-indique pas le prélèvement si le foie est macroscopiquement normal et sans altération biologique majeure ; une anomalie aiguë de la biologie hépatique (cytolyse) ne contre-indique pas non plus.', null, '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.2'),
  ('MG-ANES-000003-R081', 'Une natrémie > 170 mmol/l peut être une contre-indication au prélèvement hépatique.', '7', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.3'),
  ('MG-ANES-000003-R082', 'Les infections virales nécessitent une attention particulière (tropisme hépatique) mais ne contre-indiquent pas systématiquement le prélèvement.', '8', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.4'),
  ('MG-ANES-000003-R083', 'Imagerie hépatique et abdominale indispensable (échographie et/ou scanner) pour rechercher stéatose ou tumeur parenchymateuse.', null, '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.5'),
  ('MG-ANES-000003-R084', 'Biopsie hépatique indiquée en cas de maladie inflammatoire de l''intestin, ou d''obésité morbide.', '8', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.6'),
  ('MG-ANES-000003-R085', 'Biopsie hépatique également indiquée lorsque le foie est macroscopiquement douteux.', '9', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.7'),
  ('MG-ANES-000003-R086', 'La stéatose microvésiculaire, même massive, ne contre-indique pas le prélèvement.', null, '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.8'),
  ('MG-ANES-000003-R087', 'La stéatose macro-vacuolaire peut contre-indiquer la greffe au-delà de 30-60 %, selon le degré d''urgence de la transplantation.', '7,5', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.9'),
  ('MG-ANES-000003-R088', 'En cas de doute, la décision relève de l''équipe de transplantation.', '9', '3.4 — Prélèvement hépatique', 'Chapitre 3 — Poumon & foie — 3.4 — Prélèvement hépatique — réf. 3.4.10'),
  ('MG-ANES-000003-R089', 'L''âge du donneur, même très avancé, n''est pas une contre-indication ; la qualité du greffon devra être analysée au vu des comorbidités, des problèmes survenus en réanimation et du temps d''ischémie froide, à réduire au maximum.', '9', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.1'),
  ('MG-ANES-000003-R090', 'Une HTA de plus de dix ans est à prendre en compte pour la décision de prélèvement.', '8', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.2'),
  ('MG-ANES-000003-R091', 'Examens indispensables : créatininémie, ECBU, étude du sédiment urinaire, imagerie rénale (échographie ou scanner).', '9', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.3'),
  ('MG-ANES-000003-R092', 'Le taux de créatininémie à l''admission (ou les jours précédents) et le calcul de la clairance par la formule de Cockcroft sont des critères déterminants de la qualité du greffon.', '9', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.4'),
  ('MG-ANES-000003-R093', 'Une hématurie/protéinurie modérées ou une insuffisance rénale aiguë apparue en réanimation ne contre-indiquent pas le prélèvement.', '8', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.5'),
  ('MG-ANES-000003-R094', 'Un arrêt cardiaque < 30 minutes ou une instabilité hémodynamique, même sous fortes doses de catécholamines, ne contre-indiquent pas non plus le prélèvement — non coté dans le texte source.', null, '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.5b'),
  ('MG-ANES-000003-R095', 'Limiter la multiplication des actes d''imagerie avec opacification vasculaire (impact des produits de contraste iodés chez le donneur).', '7,5', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.6'),
  ('MG-ANES-000003-R096', 'Contre-indications : clairance de la créatinine < 30 ml/min, glomérulosclérose > 50 %, lésions athéromateuses majeures.', '9', '3.5 — Prélèvement rénal', 'Chapitre 3 — Rein & pancréas — 3.5 — Prélèvement rénal — réf. 3.5.7'),
  ('MG-ANES-000003-R097', 'Pancréas total : âge du donneur < 45 ans, sauf traumatisé sans antécédent (jusqu''à 55 ans).', '7,5', '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.1'),
  ('MG-ANES-000003-R098', 'Îlots de Langerhans : âge entre 18 et 70 ans, meilleur résultat au-delà de 50 ans — non coté dans le texte source.', null, '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.1b'),
  ('MG-ANES-000003-R099', 'Double greffe rein-pancréas : IMC préférentiellement < 27 — non coté dans le texte source.', null, '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.1c'),
  ('MG-ANES-000003-R100', 'Un taux d''amylase égal au double de la norme ne contre-indique pas le prélèvement.', '8', '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.2'),
  ('MG-ANES-000003-R101', 'Une imagerie pancréatique est recommandée avant le prélèvement — non cotée dans le texte source.', null, '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.2b'),
  ('MG-ANES-000003-R102', 'L''instabilité hémodynamique et l''arrêt cardiaque sont des facteurs de risque de pancréatite aiguë et de thrombose des vaisseaux pancréatiques chez le receveur ; une héparinothérapie pourrait être maintenue/envisagée pour prévenir les microthromboses du greffon.', '7', '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.3'),
  ('MG-ANES-000003-R103', 'Durée de séjour en réanimation avant prélèvement : ne devrait pas dépasser 5 jours (discussion au cas par cas au-delà) — non coté dans le texte source.', null, '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.4'),
  ('MG-ANES-000003-R104', 'Ischémie froide : < 8 h pour les îlots de Langerhans, < 18 h pour le pancréas total.', '8', '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.4b'),
  ('MG-ANES-000003-R105', 'L''aspect macroscopique du pancréas au bloc opératoire est le critère final déterminant pour le prélèvement.', null, '3.6 — Prélèvement pancréatique', 'Chapitre 3 — Rein & pancréas — 3.6 — Prélèvement pancréatique — réf. 3.6.5'),
  ('MG-ANES-000003-R106', 'Pas de limite inférieure d''âge pour les donneurs pédiatriques. Greffe isolée d''intestin : poids du donneur < 4 fois celui du receveur ; greffe combinée foie-intestin : ratio < 2.', null, '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.1'),
  ('MG-ANES-000003-R107', 'Une laparotomie antérieure ne contre-indique pas le prélèvement.', '8', '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.2'),
  ('MG-ANES-000003-R108', 'Des antécédents de maladie chronique de l''intestin contre-indiquent le prélèvement.', '9', '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.3'),
  ('MG-ANES-000003-R109', 'Greffes combinées foie + intestin : transaminases < 3 fois la normale et γ-GT normales.', null, '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.4'),
  ('MG-ANES-000003-R110', 'Un arrêt cardiaque prolongé et/ou une instabilité hémodynamique contre-indiquent le prélèvement (risque d''ischémie mésentérique).', '8', '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.5'),
  ('MG-ANES-000003-R111', 'De même, l''utilisation d''adrénaline/noradrénaline au-delà de 2 µg/kg/min doit faire contre-indiquer le prélèvement.', '7,5', '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.5b'),
  ('MG-ANES-000003-R112', 'Une hypernatrémie au moment du prélèvement est associée à un taux élevé de perte de greffons.', null, '3.7 — Prélèvement intestinal', 'Chapitre 3 — Intestin & tissus — 3.7 — Prélèvement intestinal — réf. 3.7.6'),
  ('MG-ANES-000003-R113', 'Nombreux tissus prélevables : cornées, membranes amniotiques, os massifs, tissus mous de l''appareil locomoteur, vaisseaux, valves cardiaques, peau. Prélèvements réalisables lors d''un PMO ou à la morgue ; organisation toujours gérée par la coordination hospitalière. Pas de limite d''âge pour le donneur.', null, '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.1'),
  ('MG-ANES-000003-R114', 'Contrôle qualité de chaque greffon réalisé par la banque de tissus qui le réceptionne.', null, '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.2'),
  ('MG-ANES-000003-R115', 'Les antécédents de cancer solide ne contre-indiquent pas le prélèvement de cornée.', '9', '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.3'),
  ('MG-ANES-000003-R116', 'Les infections virales ne sont pas une contre-indication systématique au prélèvement de tissus.', '8', '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.3b'),
  ('MG-ANES-000003-R117', 'Les échantillons sanguins prélevés après le décès pour la sécurité sanitaire doivent être centrifugés au plus vite pour éviter les erreurs d''interprétation ; au mieux, récupérer du sang pré-mortem au laboratoire de l''hôpital.', '9', '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.4'),
  ('MG-ANES-000003-R118', 'Il est souhaitable de développer les réseaux de prélèvement et les échanges interbanques de tissus, notamment pour les cornées.', '9', '3.8 — Prélèvements de tissus', 'Chapitre 3 — Intestin & tissus — 3.8 — Prélèvements de tissus — réf. 3.8.5'),
  ('MG-ANES-000003-R119', 'Le prélèvement d''organes et de tissus est une activité médicale dans laquelle tous les centres hospitaliers doivent s''inscrire, organisée sur l''unité de coordination hospitalière selon des procédures écrites respectant les recommandations de l''Agence de la biomédecine.', null, 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.1'),
  ('MG-ANES-000003-R120', 'L''unité de coordination hospitalière doit être structurée et visible, individualisant les tâches respectives de chacun.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.2'),
  ('MG-ANES-000003-R121', 'Critères d''évaluation de l''activité hospitalière : exhaustivité du recueil des comas graves ; appel systématique et précoce de la coordination dès que le diagnostic de ME est envisagé ; appel au service de régulation et d''appui dès l''intention de prélever ; intégration réelle du prélèvement dans l''activité chirurgicale d''urgence ; qualité de la tenue du dossier de coordination.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.3'),
  ('MG-ANES-000003-R122', 'La coordination hospitalière vérifie la qualité de la restitution du corps, accompagne la famille dans les démarches et reste disponible pour un suivi ultérieur des proches.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.4'),
  ('MG-ANES-000003-R123', 'Au niveau national, l''Agence de la biomédecine valide les critères de sélection et garantit la sécurité sanitaire des greffons ; au niveau inter-régional (SRA), elle valide la procédure de prélèvement, participe à la qualification des greffons, et les répartit/attribue selon la réglementation.', null, 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.5'),
  ('MG-ANES-000003-R124', 'La prise en charge peropératoire du sujet en ME doit être effectuée par un médecin qualifié en anesthésie-réanimation ; le transport entre réanimation et bloc opératoire est une période à risque maximum — sujet monitoré, accompagné par une équipe médicalisée.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.6'),
  ('MG-ANES-000003-R125', 'L''utilisation d''analgésiques et de myorelaxants chez un sujet en ME est justifiée.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.7'),
  ('MG-ANES-000003-R126', 'La prise en charge instituée en réanimation doit être maintenue en période peropératoire, avec mise en place d''un monitorage supplémentaire si l''état hémodynamique l''exige ; les règles de transfusion et d''apport de produits sanguins restent valables en période peropératoire.', '9', 'Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir', 'Chapitre 4 — Organisation du prélèvement — Chapitre 4 — Organisation du prélèvement d''organes : présent et avenir — réf. 4.8'),
  ('MG-ANES-000003-R127', 'Tout participant à un PMO doit avoir un comportement consensuel, courtois, et veiller à une bonne coordination entre équipes ; le chirurgien doit avoir été formé spécifiquement à la technique du PMO.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.9'),
  ('MG-ANES-000003-R128', 'Le PMO est une urgence chirurgicale qui ne doit passer qu''après les urgences hémorragiques et obstétricales ; il est recommandé de l''effectuer dans une salle dédiée avec une équipe spécifique, sans perturber les autres activités chirurgicales.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.10'),
  ('MG-ANES-000003-R129', 'Veiller à ce que l''installation du malade convienne à toutes les équipes chirurgicales.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.11'),
  ('MG-ANES-000003-R130', 'Aucun geste à fort risque hémorragique (canulation aortique, contrôle de l''aorte cœliaque, canulation de la VCI) ne doit être réalisé tant que les différentes équipes ne sont pas prêtes à clamper — non coté dans le texte source.', null, 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.12'),
  ('MG-ANES-000003-R131', 'Pour raccourcir au maximum la durée d''ischémie froide des prélèvements à visée immunologique, faire parvenir au laboratoire au moins 3 ganglions de bonne qualité (0,5 cm de diamètre) le plus tôt possible.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.13'),
  ('MG-ANES-000003-R132', 'Prélèvements sanguins/tissulaires pour tests immunologiques et sérologies réglementaires (typage HLA, cross-matches) : le plus tôt possible, résultats rendus en urgence — sans attendre la confirmation de ME ni l''accord des proches.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.14'),
  ('MG-ANES-000003-R133', 'Conditionnement des organes : immersion dans un liquide de préservation à 4 °C, triple emballage stérile, placés dans la glace, accompagnés d''un tube de sang à température ambiante pour vérification ultime du groupe sanguin.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.15'),
  ('MG-ANES-000003-R134', 'Pas de consensus sur la solution de conservation des organes à utiliser ; les solutions de type extracellulaire sont à privilégier. Utiliser la même solution de conservation pour le prélèvement simultané des viscères intra-abdominaux.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.16'),
  ('MG-ANES-000003-R135', 'Pendant toute la durée de l''ischémie froide, la température de conservation des greffons doit être strictement maintenue entre 2 et 4 °C.', null, 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.17'),
  ('MG-ANES-000003-R136', 'Prélèvement bactériologique et mycologique du liquide de conservation systématique avant l''implantation de chaque greffon.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.18'),
  ('MG-ANES-000003-R137', 'Avant toute transplantation rénale ou pancréatique, le cross-match doit être réalisé en urgence.', '9', 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.19'),
  ('MG-ANES-000003-R138', 'Avant tout prélèvement à des fins thérapeutiques, qualification des organes par recherche d''infection : VIH, VHB, VHC, HTLV, CMV, EBV, syphilis, toxoplasmose — l''appariement peut ne pas tenir compte du statut sérologique du receveur selon l''infection détectée, avec situations dérogatoires selon l''organe et l''urgence.', null, 'Prélèvement multi-organes (PMO) — organisation pratique', 'Chapitre 4 — PMO : chronologie & traçabilité — Prélèvement multi-organes (PMO) — organisation pratique — réf. 4.20'),
  ('MG-ANES-000003-R139', 'Dans certains pays, les prélèvements sur donneurs à cœur arrêté ont augmenté significativement le nombre de transplantations ; avec des critères de sélection stricts des donneurs et des receveurs, cette technique procure aux équipes entraînées des résultats de survie et de fonction des greffons rénaux comparables aux prélèvements sur donneurs à cœur battant.', '8', 'Donneurs à cœur arrêté (Maastricht)', 'Chapitre 4 — Cœur arrêté & sources — Donneurs à cœur arrêté (Maastricht) — réf. 4.21'),
  ('MG-ANES-000003-R140', 'La pose de la sonde de Gillot, l''exsanguination et la réfrigération du donneur potentiel ont été approuvées par le comité d''éthique de l''Agence de la biomédecine, qui considère ces gestes possibles dès le constat du décès et dans l''attente de l''entrevue avec la famille.', null, 'Donneurs à cœur arrêté (Maastricht)', 'Chapitre 4 — Cœur arrêté & sources — Donneurs à cœur arrêté (Maastricht) — réf. 4.22'),
  ('MG-ANES-000003-R141', 'Les prélèvements à cœur arrêté supposent des aménagements réglementaires en cours de développement et ne concerneront pas les donneurs relevant de la catégorie III (arrêt de soins) de la classification de Maastricht.', null, 'Donneurs à cœur arrêté (Maastricht)', 'Chapitre 4 — Cœur arrêté & sources — Donneurs à cœur arrêté (Maastricht) — réf. 4.23'),
  ('MG-ANES-000003-R142', 'Le choix de ce type de prélèvement nécessite une organisation médicale et paramédicale spécifique.', '8', 'Donneurs à cœur arrêté (Maastricht)', 'Chapitre 4 — Cœur arrêté & sources — Donneurs à cœur arrêté (Maastricht) — réf. 4.24')
) as v(code, statement, grade, condition_topic, source_section)
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Prise-en-charge-des-sujets-en-etat-de-mort-encephalique-dans-loptique-dun-prelevement-dorganes.pdf'
on conflict (recommendation_code) do nothing;
