-- Migration : Prise en charge des crises d'asthme aiguës graves de l'adulte et de l'enfant
-- (à l'exclusion du nourrisson) — SRLF, révision 2002 d'une Conférence de Consensus 1988
-- Source : rfe-sfar-website/build/content_asthme_aigu_grave.json (62 recommandations
-- atomiques, grille SRLF à DEUX axes distincts : "Preuve" (a>b>c>d, niveau de preuve de la
-- référence bibliographique) et "Force" (1>2>3, niveau de recommandation — imprimé
-- seulement quand le jury l'a jugé possible, "—" sinon).
--
-- PREMIÈRE migration de ce corpus à utiliser `evidence_level` ET `grade` comme deux champs
-- réellement distincts et tous deux renseignés (les documents précédents n'avaient soit
-- qu'un grade, soit des citations NP non structurées) : Force -> `grade`, Preuve ->
-- `evidence_level`, conformément au commentaire de schema_v2.sql ("grade / evidence_level :
-- EXACTEMENT ceux de la source, jamais devinés ni moyennés"). Quand le jury n'a pas imprimé
-- de Force pour un énoncé ("—" dans la source), `grade` est laissé NULL — pas déduit de la
-- Preuve, qui est un axe différent (a/b/c/d qualifie la référence bibliographique, pas la
-- force de la recommandation elle-même). `condition_topic` porte le "Thème" (repère de
-- colonne gauche de chaque ligne, pas un code Rx.x — cette conférence de consensus de 2002
-- ne numérote pas individuellement ses énoncés).
--
-- PÉRIMÈTRE — deux tableaux volontairement pas migrés (référence, pas des recommandations
-- graduées) : le "Tableau I" de classification de gravité (Catégorie | Critères, 9 lignes,
-- sans colonne Preuve/Force) et le "Tableau II" des formes galéniques de bêta-2 mimétiques
-- (Molécule | Forme galénique | Dosages, 11 lignes, table de référence pharmacologique).
--
-- À VÉRIFIER (disclosure, pas une invention) :
-- 1. Document de 2002 (révision d'une conférence de 1988) : le contenu construit disclose
--    lui-même explicitement que "les pratiques de prise en charge de l'asthme aigu grave
--    ont évolué depuis 2002" (place élargie du sulfate de magnésium notamment) —
--    `freshness_status` ci-dessous reste 'a_jour' faute d'information de retrait dans
--    `library_final.json` (`status: "en vigueur"`), mais un relecteur humain devrait
--    vérifier l'existence d'une actualisation avant publication.
-- 2. Seule la SRLF a coordonné cette conférence de consensus (pas de co-signataires
--    multiples comme pour d'autres documents de ce corpus) — liée seule en
--    document_societies, sans disclosure de société manquante à faire ici.

insert into public.documents (title, doc_type, original_language, publication_date, source_url, pdf_url, grading_system, freshness_status)
values (
  'Prise en charge des crises d''asthme aiguës graves de l''adulte et de l''enfant (à l''exclusion du nourrisson)',
  'CC', 'fr', '2002-01-01',
  'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf',
  'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf',
  'Grille SRLF à deux axes : Preuve (a>b>c>d, niveau de preuve de la référence : a = essais prospectifs contrôlés randomisés, b = études non randomisées/cohortes, c = mises au point/revues/séries de cas, d = opinion non revue) et Force (1>2>3, niveau de recommandation, imprimé seulement quand le jury l''a jugé possible).',
  'a_jour'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf'
  and s.acronym = 'SRLF' and s.country_or_region = 'France'
on conflict do nothing;

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf'
  and s.slug in ('medecine_intensive_reanimation', 'medecine_d_urgence', 'pneumologie', 'pediatrie')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, evidence_level, condition_topic, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.evidence_level, v.condition_topic, v.source_section,
  'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf',
  'draft'
from public.documents d, (values
  ('MG-ANES-000013-R01', 'Mesure proposée par le texte de 1988, peu utilisée en routine en France (difficultés et erreurs de mesure sur le terrain, intérêt réel peu probable) : son recueil peut être abandonné.', '3', 'c', 'Pouls paradoxal', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R02', 'Sexe masculin ; hospitalisation pour crise d''asthme durant l''année précédente ; antécédent d''intubation ; corticothérapie dans les trois mois précédents pour crise d''asthme.', null, 'b', 'Facteurs de risque épidémiologiques', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R03', 'Tabagisme, également considéré comme facteur de risque d''AAG.', null, 'b', 'Facteurs de risque (suite)', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R04', 'Abus de sédatifs, hypnotiques, stupéfiants, également considéré comme facteur de risque d''AAG.', null, 'c', 'Facteurs de risque (suite)', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R05', 'Il n''existe toujours pas de score clinique validé permettant de prédire la gravité d''une crise d''asthme dès l''admission.', null, null, 'Score clinique', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R06', 'Le suivi évolutif du débit expiratoire de pointe, mesuré 30 min à 2 h après un traitement initial optimal, est proposé chez les patients présentant un asthme aigu sévère.', '2', 'b', 'Suivi du DEP', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R07', 'Critères superposables à l''adulte (importance du caractère évolutif du DEP et des gaz du sang artériel), en dehors des particularités de l''examen clinique (Tableau I).', null, null, 'Enfant — critères de gravité', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R08', 'L''utilisation du DEP est indispensable chez l''enfant de plus de six ans.', '2', null, 'Enfant — DEP après 6 ans', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R09', 'Mesure possible chez plus de la moitié des enfants âgés de cinq à neuf ans, et chez les trois quarts des enfants de plus de dix ans.', null, 'a', 'Enfant — DEP entre 5 et 10 ans', 'Question 1 — Peut-on prévoir la gravité immédiate d''une crise d''asthme ?'),
  ('MG-ANES-000013-R10', 'Les bêta-2 mimétiques sont les bronchodilatateurs les plus puissants et les plus rapides, à index thérapeutique élevé : ils constituent indiscutablement la priorité du traitement de la crise d''asthme.', '1', 'a', 'Priorité du traitement', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R11', 'La voie inhalée est prioritaire dans tous les cas, en raison de son efficacité liée à la pénétration locale et de ses effets systémiques limités.', '1', 'a', 'Voie prioritaire', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R12', 'Les bêta-2 mimétiques d''action prolongée (formotérol, salmétérol) ainsi que les formes orales n''ont pas leur place dans le traitement de l''AAG (non coté).', null, null, 'Molécules à écarter', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R13', 'La supériorité de la nébulisation par rapport à la voie intraveineuse est établie, en termes de rapport efficacité/tolérance, dans le traitement initial de l''AAG.', '1', 'a', 'Nébulisation — supériorité', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R14', 'Utilisable quel que soit l''âge, sans nécessiter la coopération du patient ; utilisable même en cas d''obstruction bronchique majeure ou de troubles de conscience débutants.', '1', 'a', 'Nébulisation — modalités', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R15', '2,5 à 7,5 mg de salbutamol, ou 5 mg de terbutaline, au masque avec 6-8 L/min d''O2, 10-15 min, répétée toutes les 20 min. Posologie licite : 3 × 5 mg/h durant la première heure.', '2', 'a', 'Nébulisation — posologie adulte (1re heure)', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R16', 'Puis une nébulisation de 5 mg toutes les 3 h (ou 2,5 mg/h) pendant les six heures suivantes.', '3', 'b', 'Nébulisation — posologie adulte (heures suivantes)', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R17', 'Pas de différence significative entre nébulisation continue et intermittente à posologie cumulée identique. Le mélange hélium-oxygène comme gaz vecteur ne semble pas supérieur à l''oxygène seul.', null, 'a', 'Nébulisation continue vs intermittente', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R18', '0,05 à 0,15 mg/kg (dose minimale 0,5-1,5 mg) ; doses usuelles de 2,5 mg (< 20 kg) et 5 mg (> 20 kg). Nébulisation continue proposée en cas d''obstruction persistante malgré les nébulisations intermittentes.', '2', 'b', 'Nébulisation — enfant', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R19', 'N''ont pas leur place dans cette situation, en raison d''un maniement difficile et d''une efficacité limitée par l''insuffisance de la dose délivrée.', '1', 'a', 'Aérosols doseurs seuls', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R20', 'Alternative intéressante à la nébulisation, sous réserve d''une utilisation adéquate du dispositif : 2 à 4 bouffées de 100 µg répétées toutes les 5-10 min si besoin. La nécessité d''une aide pour tenir la chambre chez les patients les plus graves est un obstacle éventuel à leur utilisation (non coté).', '2', 'a', 'Aérosols doseurs + chambre d''inhalation — adulte', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R21', 'À proposer en première intention chez l''enfant : 5 à 10 bouffées de 100 µg à renouveler.', '1', 'a', 'Aérosols doseurs + chambre d''inhalation — enfant', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R22', 'Une utilisation adéquate des dispositifs disponibles et la coopération de l''enfant sont des conditions nécessaires à leur utilisation.', null, 'c', 'Aérosols doseurs + chambre d''inhalation — enfant (conditions d''utilisation)', 'Question 2 — Voie d''utilisation préférentielle des bêta-2 mimétiques et schéma thérapeutique'),
  ('MG-ANES-000013-R23', 'Indication formelle, débit ≥ 6-8 L/min, préférentiellement au masque à réserve.', '2', null, 'Oxygénothérapie — indication', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R24', 'L''hypoxémie (inhomogénéité VA/Q, aggravée par les bêta-2 mimétiques) est corrigée sans difficulté par l''enrichissement en O2 ; l''aggravation potentielle de l''hypercapnie n''est que théorique.', null, 'c', 'Oxygénothérapie — hypercapnie', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R25', 'Monitorage de la SpO2 indispensable tant que persistent les signes de gravité.', '3', null, 'Oxygénothérapie — surveillance', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R26', 'Intérêt de la prescription précoce et systématique non discuté (bases physiopathologiques établies : effets anti-inflammatoires, augmentation du nombre et de l''affinité des récepteurs bêta-2), efficacité clinique en 6-8 h.', null, 'b', 'Corticothérapie — principe', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R27', 'Les posologies élevées sont inutiles.', '1', 'a', 'Corticothérapie — posologies élevées', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R28', '1 à 2 mg/kg/j d''équivalent méthylprednisolone.', '2', 'b', 'Corticothérapie — posologie recommandée', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R29', 'De nombreuses études tendent à prouver une équivalence de la voie orale par rapport à la voie IV (la plus utilisée en pratique).', null, 'a', 'Corticothérapie — équivalence des voies', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R30', 'En l''absence de contre-indication, la voie orale peut être utilisée (utile si un abord veineux n''est pas encore disponible, ex. domicile).', '2', 'a', 'Corticothérapie — voie orale en pratique', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R31', 'Pas leur place chez l''adulte dans cette indication ; preuves insuffisantes chez l''enfant pour les juger aussi efficaces que la voie systémique (non coté par le jury).', null, null, 'Corticothérapie — corticoïdes inhalés', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R32', 'Effet bronchodilatateur moins puissant et plus progressif que les bêta-2 mimétiques : maximal entre 30 et 90 min après inhalation, persistant 3 à 9 h.', null, 'a', 'Anticholinergiques — profil pharmacologique', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R33', 'Place dans l''AAG discutée, mais les formes les plus graves répondraient mieux ; effets secondaires minimes même à doses élevées.', null, 'b', 'Anticholinergiques — efficacité & tolérance', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R34', 'Bromure d''ipratropium : 3 nébulisations de 500 µg dans la première heure, couplées aux nébulisations de bêta-2 mimétique (pas de données au-delà de ce délai).', '3', 'c', 'Anticholinergiques — posologie adulte', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R35', '3 nébulisations de 250 µg (< 6 ans) ou 500 µg (> 6 ans) de bromure d''ipratropium dans la première heure, en association aux bêta-2 mimétiques (pas de données sur la durée optimale au-delà).', '1', 'a', 'Anticholinergiques — posologie enfant', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R36', 'Aucun argument ne permet d''affirmer une supériorité de l''adrénaline par rapport aux bêta-2 mimétiques, tant pour la forme inhalée que parentérale.', null, 'a', 'Adrénaline — profil', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R37', 'Effets systémiques modérés en cas d''utilisation de la voie nébulisée, pour des posologies inférieures à 3 mg.', null, 'b', 'Adrénaline — tolérance en nébulisée', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R38', 'Formes graves résistantes : administration IV continue proposée par certaines équipes, sans étude validant cette pratique. Voie SC (0,25-0,5 mg adulte, 10 µg/kg enfant) encore utilisée dans les pays anglo-saxons et en pédiatrie (non coté par le jury).', null, null, 'Adrénaline — usages non validés', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R39', 'Utilisation des dérivés xanthiques injustifiée chez l''adulte (index thérapeutique faible, interactions médicamenteuses), y compris en association aux bêta-2 en cas de résistance au traitement conventionnel.', '1', 'a', 'Aminophylline — adulte', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R40', 'Garde sa place en deuxième intention pour certaines équipes : attaque de 6 à 10 mg/kg sur une heure, puis entretien de 0,7 à 1 mg/kg/h, sous réserve de mesurer la théophyllinémie et de réduire les doses de bêta-2 mimétiques.', '3', 'b', 'Aminophylline — enfant', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R41', 'Mécanisme mal précisé ; pourrait être réservé aux patients victimes d''une crise grave (DEP < 30 % de la valeur théorique et/ou non-réponse au traitement initial bien conduit). Posologie IV usuelle 1-2 g en 20 min chez l''adulte (doses plus élevées parfois administrées, non recommandables) ; 40 mg/kg IV chez l''enfant (bonne tolérance rapportée).', '3', 'b', 'Sulfate de magnésium', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R42', 'Gaz rare sans effet biologique ni propriété bronchodilatatrice propres ; intérêt théorique lié à sa basse densité et haute viscosité (réduction des résistances des voies aériennes), perdu si la FiO2 dépasse 40 à 60 %. Résultats des études cliniques trop divergents pour établir une recommandation.', null, 'b', 'Mélange hélium-oxygène', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R43', 'Antibiotiques réservés aux patients présentant une infection broncho-pulmonaire patente.', '2', 'b', 'Antibiothérapie — indication', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R44', 'Bêta-lactamines préférentiellement utilisées hors allergie vraie antérieurement connue.', '1', 'c', 'Antibiothérapie — choix', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R45', 'Évoquer la présence d''un micro-organisme atypique (Mycoplasma pneumoniae) chez l''enfant âgé de plus de quatre ans (non coté par le jury).', null, null, 'Antibiothérapie — cas particulier pédiatrique', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R46', 'N''a pas démontré d''efficacité spécifique dans l''AAG.', null, 'c', 'Kinésithérapie', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R47', 'Réhydratation non systématique (indiquée en cas de fièvre, sueurs abondantes, signes de déshydratation, polypnée). Agents mucolytiques non recommandés (risque de diminuer les possibilités de toux et d''aggraver l''obstruction, voire de majorer le bronchospasme). Anxiolytiques et hypnotiques contre-indiqués dans les formes sévères d''AAG.', '3', 'c', 'Mesures adjuvantes non systématiques', 'Question 3 — Place des autres thérapeutiques à la phase initiale'),
  ('MG-ANES-000013-R48', 'En l''absence de score clinique validé, l''évolution imprévisible et la nécessité d''une surveillance continue imposent le transfert en milieu hospitalier de toute crise d''asthme présentant des signes de gravité.', '1', 'b', 'Transfert hospitalier', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R49', 'Ces patients doivent être pris en charge en préhospitalier par une équipe médicalisée, envoyée dans les plus brefs délais au domicile ; admission dans une structure disposant du personnel/matériel de surveillance continue et pouvant mettre en œuvre rapidement une ventilation mécanique.', '2', 'c', 'Prise en charge préhospitalière', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R50', 'Fondés sur l''évolution du DEP après traitement bronchodilatateur. À 2 h : DEP ≥ 70 % → bonne réponse (retour possible au domicile) ; DEP < 70 % → réponse insuffisante, traitement complémentaire. Réévaluation 3-4 h plus tard : DEP > 70 % → retour au domicile ; DEP 50-70 % → orientation au cas par cas ; DEP < 50 % → hospitalisation.', '2', 'b', 'Critères prédictifs — adulte', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R51', 'Réduction du taux d''hospitalisation sans hausse notable du taux de rechute à 2 semaines, mais ces schémas ont été validés pour une population générale d''asthme aigu sévère et non spécifiquement pour l''AAG — en aucun cas un patient ayant présenté des signes cliniques de gravité ne peut être renvoyé directement à domicile (précision de la source, non un ajout de cette fiche).', null, null, 'Limite disclosed de ces critères', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R52', 'Poursuivie en milieu pneumologique, afin d''optimiser la fonction respiratoire, d''initier un traitement de fond si absent, et d''entreprendre l''éducation du patient.', null, null, 'Suite de prise en charge', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R53', 'Poursuite de l''hospitalisation non indispensable si, après 2 h de traitement : DEP > 60 % (ou 70 % si facteurs de risque), FR < 30/min (> 5 ans), absence de tirage/battement des ailes du nez, enfant se disant bien, parents comprenant le plan de traitement et les signes d''aggravation, accès rapide à l''hôpital possible, médicaments disponibles, SpO2 > 91 % sous air.', '2', 'b', 'Critères de sortie — enfant', 'Question 4 — Indications et modalités de l''hospitalisation'),
  ('MG-ANES-000013-R54', 'Morbidité et mortalité immédiate non négligeables. À envisager lors d''une dégradation clinique malgré un traitement conventionnel bien conduit, ou lorsque la présentation est grave d''emblée (trouble significatif de la conscience, bradypnée, cyanose, voire arrêt cardio-respiratoire).', null, 'c', 'Indications de l''intubation', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R55', 'En l''absence d''arrêt circulatoire : décubitus dorsal, préoxygénation, induction en séquence rapide en position assise. La kétamine associée à un curare d''action rapide pourrait être intéressante (propriétés bronchodilatatrices potentielles).', '2', 'c', 'Modalités d''induction', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R56', 'Sonde à ballonnet du plus grand diamètre possible recommandée, même chez l''enfant.', '3', 'c', 'Choix de la sonde', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R57', 'Objectif : améliorer l''oxygénation sans pressions des voies aériennes trop élevées. Fréquence basse (6-10/min adulte, 8-12/min grand enfant), volume courant restreint (6-8 mL/kg), débit d''insufflation élevé, FiO2 augmentée. Cible : pression de plateau télé-inspiratoire (Pplat) ≈ 30 cmH2O et PaO2 ≥ 80 mmHg, sans utiliser la capnie comme critère de décision. Mode volumétrique préféré par certaines équipes (Ppointe plus élevée sans effet délétère théorique attendu). Pas d''indication à ajouter une PEP en ventilation contrôlée en dehors de situations mécaniques particulières.', '2', 'b', 'Réglages ventilatoires', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R58', 'Sédation profonde le plus souvent requise par la stratégie d''hypoventilation contrôlée (pas de recommandation spécifique). Curarisation, si jugée nécessaire chez un patient sédaté au préalable de façon optimale, préférentiellement par bolus intermittents sous surveillance par neurostimulateur, compte tenu de la relation entre risque neuromyopathique et dose totale de curares.', '2', 'c', 'Sédation et curarisation', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R59', 'Pas d''étude comparant nébulisation et voie IV chez le patient ventilé. Poursuite logique du traitement bronchodilatateur si conditions techniques adéquates (aérosols doseurs avec chambre d''inhalation sur le circuit inspiratoire, nébuliseurs pneumatiques ou ultrasoniques) ; les rares études comparatives plaident pour les dispositifs ultrasoniques (masses inhalées plus élevées).', null, null, 'Nébulisation chez le patient ventilé', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R60', 'Habituellement rapide, sans problème particulier. Des difficultés de sevrage alors que l''obstruction est levée doivent faire évoquer une atteinte neuro-myopathique, le plus souvent liée à l''association corticostéroïdes + curarisation non dépolarisante, combinaison fréquente lors de la VM pour asthme grave.', '3', 'c', 'Sevrage ventilatoire', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R61', 'Action broncho-dilatatrice connue mais mécanismes mal élucidés ; respirateurs de réanimation actuels ne permettant en règle pas leur usage (à l''exception du Servo 900 C™). Halothane à proscrire (toxicité hépatique). Isoflurane bien évalué en réanimation, effet bronchodilatateur important et rapide — usage en routine non recommandé faute d''études suffisantes.', '1', null, 'Agents halogénés', 'Question 5 — Modalités de la ventilation mécanique'),
  ('MG-ANES-000013-R62', 'Intérêt suggéré par quelques séries cliniques, mais difficultés pratiques chez le patient asthmatique et caractère anecdotique des études disponibles : usage au cours de l''AAG non recommandé par le jury.', null, null, 'Ventilation non invasive (VNI)', 'Question 5 — Modalités de la ventilation mécanique')) as v(code, statement, grade, evidence_level, condition_topic, source_section)
where d.source_url = 'https://sfar.org/wp-content/uploads/2015/10/REANIMATION_Prise-en-charge-des-crises-dasthme-aigues-graves-de-ladulte-et-de-lenfant-.pdf'
on conflict (recommendation_code) do nothing;
