-- Migration : Prise en charge en situation d'urgence et en réanimation des états de mal
-- épileptiques (EME) de l'adulte et de l'enfant (nouveau-né exclu) — Recommandations
-- Formalisées d'Experts sous l'égide de la SRLF, avec la participation du GFRUP (Groupe
-- francophone de réanimation et urgences pédiatriques) et de la SFMU. H. Outin, T. Blanc,
-- I. Vinatier et 19 experts. Réanimation 2009;18:4-12, doi:10.1016/j.reaurg.2008.07.008.
-- Source : rfe-sfar-website/build/content_mal_epileptique.json.
--
-- DOCUMENT LE PLUS VOLUMINEUX DE CE CORPUS À CE JOUR — 163 recommandations migrées, dix
-- champs + une classification dédiée. Numérotation `recommendation_code` sur 3 chiffres
-- ("R001"-"R163") au lieu des 2 chiffres habituels de ce corpus (toutes les autres fiches
-- migrées ont eu ≤ 99 recommandations) — cohérent avec le format `MG-ANES-{séquence}-R{rang}`
-- documenté dans MIGRATION_PROGRESS.md (rang à largeur variable, aucune contrainte DB sur le
-- nombre de chiffres).
--
-- MÉTHODOLOGIE — UN SEUL AXE, méthode dérivée de la RAND/UCLA (PAS GRADE, PAS de système à
-- deux axes NGP+Accord comme `glycemie`/0022) : chaque proposition porte un unique tag de
-- force d'accord, coté sur une échelle continue 1-9, deux tours de cotation. Trois zones
-- (désaccord 1-3, indécision 4-6, accord 7-9) ; accord "fort" si l'intervalle de médiane
-- reste dans une zone, "faible" s'il empiète sur une borne. `grade` reproduit littéralement
-- le chip source ('Fort'/'Faible'), cohérent avec la convention déjà utilisée pour ce type
-- de cotation à un seul axe dans ce corpus (ex. `eer`/0020). `evidence_level` laissé NULL.
--
-- COMPTAGE — DIVERGENCE SUBSTANTIELLE DISCLOSÉE, NON RÉSOLUE SILENCIEUSEMENT (principe 1.5
-- du projet, cas le plus important de ce corpus à ce jour) : le panneau méthodologique du
-- contenu construit lui-même affirme que le texte source contient 190 occurrences brutes du
-- tag accord (167 « fort » + 23 « faible »), consolidées par ses soins en "149 lignes de
-- recommandation (141 en tableaux thématiques + 8 dans la classification dédiée du champ 1),
-- par regroupement strict des tags IDENTIQUES au sein d'un même item clinique... jamais de
-- fusion entre tags différents". **Un parcours direct et exhaustif du contenu JSON
-- effectivement livré (toutes les tables "Thème | Recommandation | Accord" + la table de
-- classification), avec vérification programmatique d'absence de doublon (aucun statement
-- dupliqué trouvé), donne 163 lignes distinctes (155 thématiques + 8 classification), avec
-- 140 « Fort » + 23 « Faible » = 163.** Le nombre de tags "Faible" (23) correspond
-- EXACTEMENT au chiffre brut annoncé par la source — aucune consolidation ne semble avoir
-- affecté les tags "Faible". En revanche 140 "Fort" trouvés vs 167 annoncés (écart
-- compatible avec une consolidation partielle déjà appliquée dans le JSON) et surtout 155
-- lignes thématiques trouvées vs 141 annoncées (écart de 14 lignes, sens inverse de ce
-- qu'une consolidation supplémentaire produirait). Cette migration reproduit fidèlement les
-- 163 lignes RÉELLEMENT présentes dans le contenu construit JSON (l'artefact de build faisant
-- foi pour ce projet), plutôt que de retrancher arbitrairement des lignes pour forcer une
-- correspondance avec le chiffre "149" annoncé par un panneau méthodologique visiblement
-- désynchronisé de la version finale du tableau — aucune ligne fabriquée, aucune ligne
-- supprimée pour "faire correspondre" un total.
--
-- CLASSIFICATION OPÉRATIONNELLE DE L'EME (champ 1, 8 formes cliniques) : contrairement aux
-- tableaux de classification purement descriptifs exclus ailleurs dans ce corpus (WFNS,
-- Hunt&Hess, Fisher dans `hsa`/0023 — AUCUNE cotation individuelle), CE tableau porte un tag
-- Accord Fort/Faible sur CHAQUE forme clinique listée — c'est donc une cotation individuelle
-- au même titre que les recommandations narratives, migrée comme telle (R008-R015
-- ci-dessous), reformulée en phrase déclarative complète ("Il est classé... que la forme
-- clinique « X » correspond à la catégorie « Y »") à partir du triplet
-- catégorie/forme/accord du tableau source — reformulation structurelle uniquement, aucun
-- contenu ajouté ni retranché.
--
-- SPÉCIFICITÉS PÉDIATRIQUES : la source elle-même dit les avoir "tissées dans chaque champ
-- concerné" plutôt que rassemblées en un chapitre séparé, avec un repère littéral « (enfant) »
-- sur les Thèmes concernés — ce repère, préservé verbatim dans le contenu construit, a été
-- utilisé ici pour renseigner `population = 'Pédiatrie'` sur les 18 lignes concernées.
--
-- PÉRIMÈTRE ET FRAÎCHEUR — À VÉRIFIER (disclosure, pas une invention) :
-- 1. **Document de 2008, dont la source elle-même prévoit sa propre péremption** : la
--    dernière recommandation migrée (R163) est littéralement « Ces recommandations,
--    établies début 2008, devront être réactualisées dans un délai maximum de trois ans » —
--    soit une échéance dépassée de plus de 14 ans à la date de cette migration (2026).
--    `freshness_status` mis à `revision_detectee` pour cette raison, malgré
--    `library_final.json` indiquant `"status": "en vigueur"` — divergence disclosée, à
--    vérifier en priorité par un relecteur humain (la place de l'EEG continu, des nouvelles
--    molécules — lévétiracétam, lacosamide — et des scores pronostiques a notablement évolué
--    depuis 2008 dans la littérature sur l'EME).
-- 2. SRLF et SFMU (toutes deux dans le seed Annexe B) sont liées en document_societies ;
--    GFRUP (participant pédiatrique) n'est pas dans le seed.

insert into public.documents (title, doc_type, original_language, publication_date, doi, source_url, pdf_url, grading_system, freshness_status)
values (
  'Prise en charge en situation d''urgence et en réanimation des états de mal épileptiques de l''adulte et de l''enfant (nouveau-né exclu)',
  'RFE', 'fr', '2008-07-26',
  '10.1016/j.reaurg.2008.07.008',
  'https://sfar.org/prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant-nouveau-ne-exclu/',
  'https://sfar.org/wp-content/uploads/2015/10/3_REANIMATION_Prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant.pdf',
  'Méthode dérivée RAND/UCLA, un seul axe de force d''accord (Fort/Faible), cotation continue 1-9 sur 2 tours, PAS de GRADE ni de NGP distinct. La source annonce 190 occurrences brutes de tag (167 fort + 23 faible) consolidées en 149 lignes (141 thématiques + 8 classification) ; un parcours exhaustif et dédupliqué du contenu construit JSON en trouve 163 (155 thématiques + 8 classification, 140 fort + 23 faible) — divergence disclosée et non résolue, la totalité des 163 lignes réellement présentes dans le JSON de build est migrée.',
  'revision_detectee'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant-nouveau-ne-exclu/'
  and s.acronym in ('SRLF', 'SFMU') and s.country_or_region = 'France'
on conflict do nothing;

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant-nouveau-ne-exclu/'
  and s.slug in ('anesthesie_reanimation', 'medecine_intensive_reanimation', 'neurologie', 'medecine_d_urgence', 'pediatrie')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, population, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.population, v.source_section,
  'https://sfar.org/prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant-nouveau-ne-exclu/',
  'draft'
from public.documents d, (values
  ('MG-ANES-000032-R001', 'L''EME est défini, de façon générale, par des crises continues ou par la succession de crises sans amélioration de la conscience sur une période de 30 minutes.', 'Fort', null, 'Champ 1 — Définitions de l''EME — Thème : Définition générale'),
  ('MG-ANES-000032-R002', 'Du fait de sa gravité, l''EME tonicoclonique généralisé requiert une définition spécifique impliquant une prise en charge plus précoce. Cette définition opérationnelle fait référence à des crises continues ou subintrantes pendant au moins cinq minutes.', 'Fort', null, 'Champ 1 — Définitions de l''EME — Thème : EME tonicoclonique généralisé'),
  ('MG-ANES-000032-R003', 'L''EME larvé correspond à l''évolution défavorable d''un EME tonicoclonique généralisé non traité ou traité de façon inadéquate. Il se caractérise par l''atténuation, voire la disparition des manifestations motrices chez un patient comateux contrastant avec la persistance d''un EME électrique.', 'Fort', null, 'Champ 1 — Définitions de l''EME — Thème : EME larvé — définition'),
  ('MG-ANES-000032-R004', 'Les crises sérielles avec récupération de la conscience antérieure entre les crises peuvent évoluer vers un état de mal mais ne rentrent pas dans la définition de celui-ci.', 'Fort', null, 'Champ 1 — Définitions de l''EME — Thème : Crises sérielles'),
  ('MG-ANES-000032-R005', 'Chez l''enfant, les définitions sont les mêmes. L''état de conscience en pédiatrie étant très fluctuant, il est d''autant plus difficile à apprécier que l''enfant est plus jeune.', 'Fort', 'Pédiatrie', 'Champ 1 — Définitions de l''EME — Thème : Définitions chez l''enfant (enfant)'),
  ('MG-ANES-000032-R006', 'On distingue sur un plan clinique les EME convulsifs, dont le diagnostic repose sur les seules données cliniques, des EME non convulsifs, dont le diagnostic plus difficile nécessite la réalisation d''un électroencéphalogramme (EEG).', 'Fort', null, 'Formes cliniques et classification — Thème : EME convulsif vs non convulsif'),
  ('MG-ANES-000032-R007', 'Une classification « opérationnelle » basée sur le pronostic et donc sur le degré d''urgence thérapeutique est indispensable dans la pratique quotidienne. La classification proposée prend en compte trois degrés de mise en jeu du pronostic (détail ci-dessous).', 'Fort', null, 'Formes cliniques et classification — Classification opérationnelle'),
  ('MG-ANES-000032-R008', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME convulsif généralisé tonicoclonique (d''emblée ou secondairement généralisé) » correspond à la catégorie « Pronostic vital engagé à court terme ».', 'Fort', null, 'Formes cliniques et classification — Classification EME — EME convulsif généralisé tonicoclonique (d''emblée ou secondairement généralisé)'),
  ('MG-ANES-000032-R009', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME larvé » correspond à la catégorie « Pronostic vital engagé à court terme ».', 'Fort', null, 'Formes cliniques et classification — Classification EME — EME larvé'),
  ('MG-ANES-000032-R010', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME confusionnel partiel complexe » correspond à la catégorie « Pronostic vital et/ou fonctionnel engagé à moyen terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — EME confusionnel partiel complexe'),
  ('MG-ANES-000032-R011', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME convulsif focal avec ou sans marche Bravais-Jacksonienne » correspond à la catégorie « Pronostic vital et/ou fonctionnel engagé à moyen terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — EME convulsif focal avec ou sans marche Bravais-Jacksonienne'),
  ('MG-ANES-000032-R012', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME convulsif généralisé myoclonique » correspond à la catégorie « N''engageant pas le pronostic vital à court terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — EME convulsif généralisé myoclonique'),
  ('MG-ANES-000032-R013', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME absence » correspond à la catégorie « N''engageant pas le pronostic vital à court terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — EME absence'),
  ('MG-ANES-000032-R014', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « EME à symptomatologie élémentaire, donc sans rupture de contact (hallucinations, aphasie...) » correspond à la catégorie « N''engageant pas le pronostic vital à court terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — EME à symptomatologie élémentaire, donc sans rupture de contact (hallucinations, aphasie...)'),
  ('MG-ANES-000032-R015', 'Il est classé, en termes de degré d''urgence pronostique, que la forme clinique « Épilepsie partielle continue » correspond à la catégorie « N''engageant pas le pronostic vital à court terme ».', 'Faible', null, 'Formes cliniques et classification — Classification EME — Épilepsie partielle continue'),
  ('MG-ANES-000032-R016', 'Dans le cadre des encéphalopathies épileptiques, chez l''enfant comme chez l''adulte, il faut savoir tolérer les EME toniques (que les benzodiazépines peuvent aggraver), cloniques ou myocloniques et ne pas avoir systématiquement recours à des traitements agressifs.', 'Faible', 'Pédiatrie', 'Formes cliniques et classification — Thème : Encéphalopathies épileptiques — tolérance (enfant)'),
  ('MG-ANES-000032-R017', 'Tout patient hospitalisé pour un EME doit être secondairement réévalué par un neurologue, afin de préciser, à distance de l''épisode aigu, le diagnostic positif, syndromique et différentiel de l''EME, et d''adapter les éventuels traitements antiépileptiques.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Réévaluation neurologique'),
  ('MG-ANES-000032-R018', 'Face à des manifestations motrices prolongées atypiques suggérant un EME convulsif, il convient systématiquement d''évoquer un pseudo état de mal (origine psychogène).', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Évocation systématique'),
  ('MG-ANES-000032-R019', 'Les éléments cliniques faisant évoquer ce diagnostic doivent être connus de tout médecin prenant en charge un EME tonicoclonique : fermeture des yeux, résistance à l''ouverture des yeux, atypie des mouvements et contact possible avec le patient.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Signes cliniques évocateurs'),
  ('MG-ANES-000032-R020', 'En cas de doute diagnostique, l''EEG (idéalement couplé à un enregistrement vidéo) est utile pour distinguer un EME d''un pseudo état de mal.', 'Faible', null, 'Champ 2 — Diagnostic différentiel — Thème : EEG en cas de doute'),
  ('MG-ANES-000032-R021', 'En cas de mouvement anormal dont l''origine épileptique est suspectée, chez un patient en réanimation, l''enregistrement d''un EEG devrait comporter au moins une dérivation d''électromyogramme, et doit être au mieux couplé à un enregistrement vidéo simultané.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : EEG + EMG'),
  ('MG-ANES-000032-R022', 'La suppression d''un mouvement anormal par l''injection de benzodiazépine ne prouve pas son origine épileptique.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Test benzodiazépine non probant'),
  ('MG-ANES-000032-R023', 'L''encéphalopathie postanoxique s''accompagne souvent de myoclonies non épileptiques d''importance variable, typiquement à prédominance axiale, parfois déclenchées par des stimulations sonores et tactiles. Elle ne s''accompagne que rarement de crise d''épilepsie voire d''un EME convulsif.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Clinique'),
  ('MG-ANES-000032-R024', 'L''EEG lors d''une encéphalopathie postanoxique montre des anomalies variées, en particulier des pointes périodiques généralisées qui ne doivent pas faire évoquer des crises voire un état de mal. Des myoclonies non épileptiques peuvent être associées ou non à ces anomalies EEG.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : EEG — pointes périodiques'),
  ('MG-ANES-000032-R025', 'Dans un contexte d''anoxie cérébrale, des pointes périodiques généralisées sur l''EEG, qui ne s''organisent pas en décharge rythmique, et sans symptôme clinique autre qu''un coma, reflètent un trouble de l''électrogenèse corticale et ne doivent pas conduire à un traitement.', 'Fort', null, 'Champ 2 — Diagnostic différentiel — Thème : Pas de traitement'),
  ('MG-ANES-000032-R026', 'Le diagnostic différentiel chez l''enfant entre crise d''épilepsie occipitale prolongée et migraine avec aura est parfois difficile.', 'Fort', 'Pédiatrie', 'Champ 2 — Diagnostic différentiel — Thème : Diagnostic différentiel (enfant)'),
  ('MG-ANES-000032-R027', 'Le traitement d''un EME dont le diagnostic est évident doit débuter sans attendre l''EEG.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Traitement sans attendre l''EEG'),
  ('MG-ANES-000032-R028', 'Celui-ci devrait idéalement être disponible 24 h/24 pour le diagnostic et le suivi des formes graves.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Disponibilité de l''EEG'),
  ('MG-ANES-000032-R029', 'Un EEG en urgence est indiqué dans les EME convulsifs généralisés, sans en retarder la prise en charge thérapeutique initiale.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : EME convulsif généralisé'),
  ('MG-ANES-000032-R030', 'Un EEG en urgence est indiqué en cas de suspicion d''EME non convulsif à expression confusionnelle.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Suspicion EME non convulsif'),
  ('MG-ANES-000032-R031', 'Un EEG en urgence est indiqué en cas de doute persistant sur un pseudo état de mal.', 'Faible', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Doute persistant — pseudo EM'),
  ('MG-ANES-000032-R032', 'Tout patient hospitalisé pour un EME doit bénéficier d''un EEG le plus tôt possible.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : EEG systématique'),
  ('MG-ANES-000032-R033', 'Un enregistrement EEG standard avec au moins huit voies, et idéalement 21 voies, durant au moins 20 minutes, et au mieux 30 minutes, est l''examen de référence.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Caractéristiques de l''EEG standard'),
  ('MG-ANES-000032-R034', 'Il doit être au mieux couplé à un enregistrement vidéo.', 'Faible', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Couplage vidéo'),
  ('MG-ANES-000032-R035', 'Il permet de confirmer le diagnostic d''EME, d''écarter les diagnostics différentiels, de préciser le cas échéant le diagnostic syndromique voire étiologique, de guider la prise en charge thérapeutique, et de participer au suivi évolutif de l''EME.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Utilité de l''EEG'),
  ('MG-ANES-000032-R036', 'Un test d''injection d''un antiépileptique d''action rapide lors d''un EEG n''est en faveur d''une activité épileptique que s''il corrige les anomalies EEG et améliore cliniquement le patient. Ce test thérapeutique doit se faire en présence d''un médecin.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Test d''injection antiépileptique'),
  ('MG-ANES-000032-R037', 'L''interprétation de l''EEG doit utiliser un vocabulaire facilement compréhensible et comporter une conclusion qui stipule la présence (ou la persistance) ou non d''un EME.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Vocabulaire et conclusion'),
  ('MG-ANES-000032-R038', 'Il ne s''interprète qu''à la lumière des données cliniques et des différents traitements reçus par le patient.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Interprétation contextualisée'),
  ('MG-ANES-000032-R039', 'L''expertise visuelle est plus fiable que les logiciels d''analyse de l''EEG.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Expertise visuelle'),
  ('MG-ANES-000032-R040', 'La présence d''anomalies EEG diffuses et périodiques, et a fortiori celle d''ondes triphasiques, ne doivent pas faire évoquer le diagnostic d''EME non convulsif, mais plutôt différents types d''encéphalopathies (postanoxique, métabolique, infectieuse, toxique et spongiforme).', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Anomalies diffuses/périodiques — piège'),
  ('MG-ANES-000032-R041', 'Dans un contexte postanoxique, l''existence de figures épileptiques diffuses (comme des pointes, des polypointes), n''évoluant pas de façon rythmique, en décharge, mais de façon périodique, même si elles sont très fréquentes, ne signe habituellement pas l''existence d''une crise ou d''un EME.', 'Fort', null, 'Champ 3 — Place de l''électroencéphalogramme — Thème : Contexte postanoxique — figures périodiques'),
  ('MG-ANES-000032-R042', 'Chez l''enfant, l''EEG de longue durée (>12 heures) est très utile au diagnostic positif d''EME non convulsif et pour surveiller l''efficacité des traitements.', 'Fort', 'Pédiatrie', 'Champ 3 — Place de l''électroencéphalogramme — Thème : EEG de longue durée (enfant)'),
  ('MG-ANES-000032-R043', 'La recherche étiologique doit être effectuée rapidement, sans retarder ni la mise en œuvre du traitement antiépileptique ni les manœuvres de réanimation.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Recherche rapide'),
  ('MG-ANES-000032-R044', 'Un EME répond souvent à plusieurs étiologies.', 'Faible', null, 'Champ 4 — Enquête étiologique — Thème : EME multi-étiologique'),
  ('MG-ANES-000032-R045', 'Si une étiologie n''est pas diagnostiquée et maîtrisée, elle peut être un facteur d''entretien de l''EME.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Étiologie non maîtrisée'),
  ('MG-ANES-000032-R046', 'La recherche de certains troubles métaboliques est incontournable. Une hypoglycémie, une hyponatrémie et une hypocalcémie doivent être recherchées et corrigées en urgence.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Troubles métaboliques'),
  ('MG-ANES-000032-R047', 'Chez le patient épileptique connu, la première cause d''EME est un sevrage de médicaments antiépileptiques relatif ou absolu par non-observance thérapeutique, adjonction d''un traitement inducteur enzymatique ou au cours du changement de médicament antiépileptique.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Patient épileptique connu — 1re cause'),
  ('MG-ANES-000032-R048', 'Les principales autres causes sont l''intoxication ou le sevrage alcoolique, la prescription de médicaments proconvulsivants et les infections intercurrentes.', 'Faible', null, 'Champ 4 — Enquête étiologique — Thème : Patient épileptique connu — autres causes'),
  ('MG-ANES-000032-R049', 'En l''absence de facteur déclenchant évident, en cas de doute étiologique ou d''EME persistant, l''enquête doit être identique à celle réalisée devant un EME inaugural, du fait de l''intrication fréquente des étiologies.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Enquête si doute étiologique'),
  ('MG-ANES-000032-R050', 'En cas d''EME inaugural, les principales étiologies sont les souffrances cérébrales aiguës, qu''elles soient structurelles (méningoencéphalites, accidents vasculaires cérébraux, traumatismes...) ou fonctionnelles (hyponatrémie aiguë, intoxications médicamenteuses ou par substances illicites...).', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : EME inaugural — étiologies principales'),
  ('MG-ANES-000032-R051', 'Plus rarement, car dans ces cas le patient peut déjà avoir présenté des crises : les lésions cérébrales subaiguës évolutives (comme les tumeurs, la toxoplasmose cérébrale), les affections dégénératives.', 'Faible', null, 'Champ 4 — Enquête étiologique — Thème : EME inaugural — étiologies plus rares'),
  ('MG-ANES-000032-R052', 'Les lésions cicatricielles (comme les séquelles d''accident vasculaire cérébral et de traumatisme) figurent également parmi les étiologies possibles, plus rares, d''un EME inaugural.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : EME inaugural — lésions cicatricielles'),
  ('MG-ANES-000032-R053', 'Dans moins de 10 % des cas, l''enquête est négative.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Enquête négative'),
  ('MG-ANES-000032-R054', 'Les indications de l''imagerie cérébrale doivent rester larges. Il faut tenir compte, chez le patient épileptique connu, des circonstances de survenue de l''état de mal (par exemple traumatisme en cours de crise) et des caractéristiques électrocliniques habituelles des crises.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Principe — indications larges'),
  ('MG-ANES-000032-R055', 'L''imagerie cérébrale (scanner cérébral sans et avec injection, ou IRM) est indiquée en urgence, en tenant compte de l''état neurologique antérieur : s''il existe des signes de localisation ; si une ponction lombaire est nécessaire ; en cas de notion de traumatisme crânien ; en cas de notion de néoplasie ; en cas de notion d''immunodépression (VIH, corticothérapie...) ; si la cause demeure obscure.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Indications en urgence'),
  ('MG-ANES-000032-R056', 'L''imagerie cérébrale est également indiquée en urgence si le début électro-clinique de l''EME est partiel.', 'Faible', null, 'Champ 4 — Enquête étiologique — Thème : Début électroclinique partiel'),
  ('MG-ANES-000032-R057', 'Une ponction lombaire, en dehors de ses contre-indications, est préconisée dans un contexte infectieux et en cas d''immunodépression.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Indications'),
  ('MG-ANES-000032-R058', 'Une ponction lombaire est également préconisée en cas de négativité de la recherche étiologique.', 'Faible', null, 'Champ 4 — Enquête étiologique — Thème : Négativité de l''enquête'),
  ('MG-ANES-000032-R059', 'Chez l''adulte et plus encore chez l''enfant, en cas d''état de mal convulsif fébrile, lorsque la ponction lombaire ne peut être réalisée immédiatement, il est recommandé de débuter sans délai par voie veineuse un traitement antibiotique probabiliste et de l''acyclovir vis-à-vis d''une possible encéphalite herpétique.', 'Fort', 'Pédiatrie', 'Champ 4 — Enquête étiologique — Thème : Fébrile — ATB + acyclovir sans délai (enfant)'),
  ('MG-ANES-000032-R060', 'La persistance de l''EME sans étiologie identifiée impose la poursuite des examens, en s''aidant dès que possible des conseils d''un neurologue.', 'Fort', null, 'Champ 4 — Enquête étiologique — Thème : Persistance sans étiologie'),
  ('MG-ANES-000032-R061', 'Chez l''enfant, une hypocalcémie profonde (calcémie ionisée < 0,8 mmol/l) ou une hypomagnésémie (< 0,5 mmol/l) peuvent être responsables d''un EME ; sa correction par voie veineuse ne sera effectuée qu''après dosage sanguin.', 'Faible', 'Pédiatrie', 'Champ 4 — Enquête étiologique — Thème : Hypocalcémie/hypomagnésémie (enfant)'),
  ('MG-ANES-000032-R062', 'En l''absence de cause évidente à un EME convulsif chez un nourrisson, une injection de pyridoxine doit être proposée (50 à 100 mg/kg) en milieu de réanimation sous monitorage et enregistrement EEG.', 'Fort', 'Pédiatrie', 'Champ 4 — Enquête étiologique — Thème : Pyridoxine — nourrisson (enfant)'),
  ('MG-ANES-000032-R063', 'La qualité de la prise en charge améliore le pronostic.', 'Fort', null, 'Facteurs pronostiques — Thème : Qualité de la prise en charge'),
  ('MG-ANES-000032-R064', 'Le pronostic fonctionnel (séquelles motrices, cognitives, apparition ou aggravation d''une maladie épileptique) est difficile à déterminer indépendamment des facteurs étiologiques sous-jacents et des complications liées à la prise en charge.', 'Fort', null, 'Facteurs pronostiques — Thème : Pronostic fonctionnel'),
  ('MG-ANES-000032-R065', 'Chez l''adulte comme chez l''enfant, les trois principaux déterminants de la mortalité et des séquelles neurologiques d''un EME sont l''âge, sa cause et sa durée.', 'Fort', null, 'Facteurs pronostiques — Thème : Trois déterminants (adulte et enfant)'),
  ('MG-ANES-000032-R066', 'Par rapport à des crises épileptiques inaugurales, un EME de novo augmente le risque de développer une épilepsie.', 'Fort', null, 'Facteurs pronostiques — Thème : EME de novo — risque d''épilepsie'),
  ('MG-ANES-000032-R067', 'Le caractère réfractaire d''un EME augmente le risque de mortalité, le risque de récidive d''EME et possiblement celui de développer une maladie épileptique.', 'Fort', null, 'Facteurs pronostiques — Thème : Caractère réfractaire'),
  ('MG-ANES-000032-R068', 'Chez l''enfant, le pronostic de l''EME est plus sévère lorsqu''il est fébrile, compte tenu du risque de lésions hippocampiques.', 'Fort', 'Pédiatrie', 'Facteurs pronostiques — Thème : Pronostic plus sévère si fébrile (enfant)'),
  ('MG-ANES-000032-R069', 'La prise en charge symptomatique de l''EME convulsif généralisé est une urgence. Elle nécessite, en préhospitalier, l''intervention d''une équipe médicale d''urgence. L''hospitalisation est systématique. Le transfert en réanimation est indiqué en cas de persistance des crises, du trouble de la vigilance ou de défaillances associées.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Hospitalisation et transfert en réanimation'),
  ('MG-ANES-000032-R070', 'Dans tous les cas, le contrôle des facteurs d''agression cérébrale est impératif, ce d''autant que l''EME est consécutif à des lésions cérébrales aiguës.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Contrôle des facteurs d''agression cérébrale'),
  ('MG-ANES-000032-R071', 'Les mesures de prise en charge immédiate comportent : la mise en position latérale de sécurité, le maintien de la liberté des voies aériennes supérieures, une oxygénation avec pour objectif une SpO2 supérieure ou égale à 95 %, la mise en place d''une voie veineuse périphérique avec perfusion de sérum physiologique, la mesure de la glycémie capillaire et la correction d''une éventuelle hypoglycémie.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Mesures de prise en charge immédiate'),
  ('MG-ANES-000032-R072', 'L''intubation et la ventilation mécanique ne sont pas systématiques d''emblée. Elles sont indiquées en cas de recours à des agents anesthésiques, de détresse respiratoire aiguë ou d''altération profonde et prolongée de la vigilance, malgré l''arrêt des convulsions.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Intubation/VM non systématique'),
  ('MG-ANES-000032-R073', 'En préhospitalier, la sécurité du transport autorise un délai plus court de recours à la ventilation mécanique.', 'Faible', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Préhospitalier — délai de recours à la VM'),
  ('MG-ANES-000032-R074', 'La technique d''induction anesthésique recommandée est celle de la procédure à séquence rapide. L''utilisation de succinylcholine est recommandée. Les curares de longue durée d''action doivent être évités. Le thiopental, le propofol, ou l''étomidate peuvent être utilisés comme agent d''induction. Le midazolam n''est pas recommandé en induction.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Technique d''induction anesthésique'),
  ('MG-ANES-000032-R075', 'En préhospitalier, l''entretien d''une sédation chez les patients ventilés est souvent nécessaire. Le midazolam est recommandé et l''adjonction d''un morphinomimétique est utile. Les curares de longue durée d''action doivent être évités afin de ne pas masquer des convulsions.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Sédation d''entretien en préhospitalier'),
  ('MG-ANES-000032-R076', 'En dehors des situations d''hypertension intracrânienne, l''interruption de la sédation est conseillée à l''arrivée du patient en réanimation, afin de faciliter l''évaluation de l''état neurologique et de l''activité épileptique.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Interruption de la sédation à l''arrivée'),
  ('MG-ANES-000032-R077', 'Chez le malade intubé et ventilé, le recours à une curarisation ponctuelle peut s''avérer nécessaire pour éliminer les artéfacts musculaires sur l''EEG et pour réaliser une ponction lombaire ou une imagerie cérébrale.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Curarisation ponctuelle'),
  ('MG-ANES-000032-R078', 'Lorsque la sédation et la ventilation restent nécessaires, l''objectif est d''obtenir une normoxie et une normocapnie (35 à 40 mmHg). La ventilation en hypocapnie est contre-indiquée, y compris en cas d''œdème cérébral.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Objectif ventilatoire — normocapnie'),
  ('MG-ANES-000032-R079', 'Il est recommandé de maintenir une pression artérielle moyenne entre 70 et 90 mmHg.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Objectif hémodynamique'),
  ('MG-ANES-000032-R080', 'La surveillance continue du tracé électrocardiographique et la réalisation dès que possible d''un électrocardiogramme sont indispensables.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Surveillance ECG'),
  ('MG-ANES-000032-R081', 'La détection et le traitement d''une hyperthermie font partie intégrante de la prise en charge de l''EME. Les vertus neuroprotectrices de l''hypothermie n''ont pas été confirmées en pratique clinique.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Hyperthermie / hypothermie'),
  ('MG-ANES-000032-R082', 'Le monitorage et le contrôle de la glycémie (en prévenant tout épisode d''hypoglycémie) et celui de la natrémie sont systématiques. L''acidose métabolique se corrige généralement avec l''arrêt des crises, sans que l''administration de bicarbonates soit nécessaire.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Monitorage glycémie/natrémie'),
  ('MG-ANES-000032-R083', 'Chez l''éthylique connu ou suspecté, l''injection de thiamine (vitamine B1 : 100 mg en intraveineux lent) est recommandée.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Éthylique — thiamine'),
  ('MG-ANES-000032-R084', 'En cas d''hypertension intracrânienne potentielle ou avérée (traumatisme crânien, pathologie cérébrale vasculaire, infectieuse, tumorale...), l''EME est considéré comme un véritable facteur d''agression secondaire susceptible d''aggraver l''hypertension intracrânienne.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : HTIC — facteur d''agression secondaire'),
  ('MG-ANES-000032-R085', 'Aucune molécule à visée neuroprotectrice ne peut être recommandée actuellement.', 'Fort', null, 'Champ 5 — Prise en charge non spécifique de l''EME convulsif généralisé — Thème : Neuroprotection médicamenteuse'),
  ('MG-ANES-000032-R086', 'Un traitement antiépileptique doit être, une fois le diagnostic établi, administré en urgence devant des crises convulsives généralisées continues ou subintrantes persistant au moins cinq minutes. La pérennisation de l''EME convulsif augmente le risque de lésions cérébrales et induit une pharmacorésistance dont les mécanismes sont mal connus.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Urgence thérapeutique'),
  ('MG-ANES-000032-R087', 'L''EME larvé nécessite une prise en charge immédiate sans attendre l''EEG si l''histoire clinique et les manifestations observées sont évocatrices.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : EME larvé — PEC immédiate'),
  ('MG-ANES-000032-R088', 'Dans tous les cas, un monitorage de la fréquence cardiaque et respiratoire, de la pression artérielle et de la saturation en oxygène est mis en place.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Monitorage systématique'),
  ('MG-ANES-000032-R089', 'La survenue d''une hypotension ou de troubles du rythme cardiaque impose la diminution du débit de perfusion de l''antiépileptique en cours ou son arrêt (éventuellement transitoire) en fonction de la sévérité.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Hypotension sous traitement'),
  ('MG-ANES-000032-R090', 'Quand le patient est pris en charge entre cinq et 30 minutes après le début des convulsions, une benzodiazépine en monothérapie est recommandée par voie intraveineuse lente (en une à deux minutes au moins). En cas de persistance des convulsions au bout de cinq minutes, on procédera à une seconde injection de la même benzodiazépine, à la même dose, associée à un autre médicament antiépileptique en intraveineux.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Schéma initial 5—30 minutes'),
  ('MG-ANES-000032-R091', 'Quand le patient est pris en charge au-delà de 30 minutes après le début des convulsions, une injection de benzodiazépine est effectuée, d''emblée associée à un autre médicament antiépileptique en intraveineux. En cas de persistance des convulsions, au bout de cinq minutes, on procédera à une seconde injection de la même benzodiazépine à la même dose.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Schéma initial au-delà de 30 minutes'),
  ('MG-ANES-000032-R092', 'Le médicament antiépileptique donné en association avec la benzodiazépine sera de la phénytoïne/fosphénytoïne ou du phénobarbital. Le choix tiendra compte de leurs contre-indications, de l''appréciation de leurs risques iatrogènes et de leur rapidité d''action. Dans des situations particulières, le valproate de sodium (qui n''a pas l''AMM dans l''EME) pourra être utilisé.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Choix du médicament associé'),
  ('MG-ANES-000032-R093', 'Quelle que soit l''évolution des convulsions, y compris une éventuelle cessation, l''intégralité de la dose prescrite doit être administrée.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Dose intégrale à administrer'),
  ('MG-ANES-000032-R094', 'Le schéma proposé pour l''EME larvé est celui décrit pour l''EME convulsif évoluant depuis plus de 30 minutes.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : EME larvé — schéma applicable'),
  ('MG-ANES-000032-R095', 'On proposera le recours au médicament antiépileptique non utilisé en première intention (phénobarbital après phénytoïne/fosphénytoïne, et vice versa) si toutes les conditions suivantes sont satisfaites : EME évoluant depuis moins de 60 minutes ; probabilité faible de lésion cérébrale aiguë ; pas de facteur incontrôlé d''agression cérébrale (instabilité hémodynamique, hypoxie, hyperthermie majeure).', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Recours au 2e antiépileptique'),
  ('MG-ANES-000032-R096', 'Ce recours au second antiépileptique de première ligne suppose en outre l''absence d''EME larvé.', 'Faible', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Condition additionnelle'),
  ('MG-ANES-000032-R097', 'Dans les autres situations, le recours à un traitement par thiopental, midazolam ou propofol, sous couvert d''une assistance respiratoire, est proposé.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Autres situations — anesthésie générale'),
  ('MG-ANES-000032-R098', 'Le valproate de sodium peut être utilisé dans des situations où la mise en œuvre d''une anesthésie générale avec ventilation mécanique est déraisonnable (limitation de soins).', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Valproate — limitation de soins'),
  ('MG-ANES-000032-R099', 'L''attitude qui consiste à administrer un complément de dose de phénytoïne, fosphénytoïne ou phénobarbital ne repose sur aucune donnée clinique validée.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Compléments de dose — non fondés'),
  ('MG-ANES-000032-R100', 'Un relais par benzodiazépines par voie entérale (clobazam : 5 à 10 mg × 3 ou clonazépam : 1 à 2 mg × 3) ou parentérale discontinue est indispensable. Ce relais doit être immédiat si l''EME a été contrôlé par une seule dose de diazépam ou de midazolam, en raison du risque de récidive à court terme.', 'Fort', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Relais par benzodiazépines'),
  ('MG-ANES-000032-R101', 'Pour l''instauration ou l''adaptation d''un éventuel traitement antiépileptique de fond, un avis spécialisé devra être pris. Le phénobarbital devrait être évité au long cours.', 'Faible', null, 'Champ 7 — Schéma thérapeutique initial (EME convulsif généralisé) — Thème : Phénobarbital au long cours'),
  ('MG-ANES-000032-R102', 'La durée d''action prolongée de plusieurs heures du clonazépam amène à privilégier son utilisation en France. S''il n''est pas disponible, le diazépam sera utilisé.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Choix de la benzodiazépine'),
  ('MG-ANES-000032-R103', 'La posologie du clonazépam est de 0,015 mg/kg, celle du diazépam de 0,15 mg/kg.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Posologie clonazépam / diazépam'),
  ('MG-ANES-000032-R104', 'Le lorazépam, benzodiazépine d''action prolongée validée dans des essais contrôlés, n''est pas disponible en France sauf dans le cadre de l''ATU. La posologie du lorazépam est de 0,1 mg/kg.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Lorazépam'),
  ('MG-ANES-000032-R105', 'Lorsque l''administration de benzodiazépines par voie intraveineuse est impossible, le midazolam en intramusculaire (0,15 mg/kg) ou par voie buccale (0,3 mg/kg) peut être employé.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Voie IV impossible'),
  ('MG-ANES-000032-R106', 'Le phénobarbital est utilisé en intraveineux à la posologie de 15 mg/kg à un débit de perfusion maximum de 100 mg/min.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Posologie IV'),
  ('MG-ANES-000032-R107', 'Il est contre-indiqué chez l''insuffisant respiratoire sévère. Il induit une dépression de la vigilance, qui peut gêner l''appréciation de l''état neurologique, et une dépression respiratoire modérée.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Contre-indication et effets'),
  ('MG-ANES-000032-R108', 'Le phénobarbital a un délai d''action rapide qui permet de juger en pratique de sa pleine efficacité 20 minutes après le début de la perfusion.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Délai d''action'),
  ('MG-ANES-000032-R109', 'La fosphénytoïne (ampoules de 500 mg en équivalents de phénytoïne sodique) est utilisée à la posologie de 20 mg/kg en équivalents de phénytoïne sodique, à un débit de perfusion maximum de 150 mg/min. Ce débit pourra être réduit chez des patients considérés comme fragiles (sujet âgé, coronarien).', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Fosphénytoïne — posologie'),
  ('MG-ANES-000032-R110', 'La phénytoïne (ampoules de 250 mg) est utilisée à la posologie de 20 mg/kg avec un débit de perfusion maximum de 50 mg/min. Ce débit pourra être réduit chez des patients considérés comme fragiles (sujet âgé, coronarien).', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Phénytoïne — posologie'),
  ('MG-ANES-000032-R111', 'La phénytoïne et la fosphénytoïne sont contre-indiquées en cas de troubles de la conduction ou de cardiopathie sévère. Elles influent peu sur la vigilance et la fonction respiratoire.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Contre-indications et effets'),
  ('MG-ANES-000032-R112', 'La phénytoïne nécessite un cathéter périphérique de gros calibre et une voie unique. La meilleure tolérance locale et la facilité d''administration de la fosphénytoïne (compatibilité avec les solutés de perfusion et autres médicaments) la font privilégier à la phénytoïne.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Fosphénytoïne préférée'),
  ('MG-ANES-000032-R113', 'La phénytoïne et la fosphénytoïne, bien qu''administrées à un débit différent (trois fois plus rapide pour la fosphénytoïne), agissent dans le même délai. En pratique, leur pleine efficacité ne pourra être évaluée que 30 minutes après le début de la perfusion.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Délai d''efficacité'),
  ('MG-ANES-000032-R114', 'Le valproate de sodium en intraveineux est indiqué en première intention (associé aux benzodiazépines) à la dose de 25 mg/kg en dose de charge puis, selon les taux sanguins, de 1 à 4 mg/kg par heure par voie intraveineuse, en cas de contre-indication à la fosphénytoïne et au phénobarbital, et en cas d''état de mal secondaire à un sevrage en valproate de sodium.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Posologie et indications'),
  ('MG-ANES-000032-R115', 'Il est contre-indiqué en cas d''hépatopathie préexistante.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Contre-indication'),
  ('MG-ANES-000032-R116', 'Lors de l''éclampsie, outre les benzodiazépines et l''extraction du fœtus en urgence, il est recommandé d''associer du sulfate de magnésium (4 g en 20 minutes puis 1 g/h en intraveineux continu).', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Éclampsie'),
  ('MG-ANES-000032-R117', 'Lors des crises aiguës de porphyrie, on utilise le clonazépam ou le lorazépam. L''intérêt potentiel du propofol doit être souligné. Sont notamment contre-indiqués le diazépam, la phénytoïne et la fosphénytoïne, les barbituriques, le valproate de sodium, l''étomidate et la kétamine (www.drugs-porphyria.org).', 'Faible', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Porphyrie aiguë'),
  ('MG-ANES-000032-R118', 'Lors des intoxications par médicaments ou substances illicites, les benzodiazépines puis les barbituriques (si nécessaires) sont conseillés.', 'Fort', null, 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Intoxications aiguës'),
  ('MG-ANES-000032-R119', 'Les posologies des benzodiazépines sont les suivantes : 0,1 mg/kg pour le lorazépam (maximum : 4 mg) ; 0,02 à 0,04 mg/kg pour le clonazépam (maximum : 1 mg) ; 0,2 à 0,4 mg/kg pour le diazépam (maximum : 5 mg chez l''enfant de moins de cinq ans, 10 mg pour l''enfant de cinq ans et plus).', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Benzodiazépines (enfant)'),
  ('MG-ANES-000032-R120', 'Lorsque l''administration d''une benzodiazépine est impossible par voie intraveineuse, peuvent être utilisés le diazépam par voie intrarectale (0,3 à 0,5 mg/kg), ou le midazolam par voie nasale (0,2 à 0,3 mg/kg), buccale (0,2 à 0,3 mg/kg) ou intramusculaire (0,2 à 0,5 mg/kg). Le choix sera avant tout fonction de l''expérience et des préférences des professionnels ou des parents.', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Voies alternatives (enfant)'),
  ('MG-ANES-000032-R121', 'Le phénobarbital est utilisé par voie veineuse à la posologie de 15 à 20 mg/kg avec un débit de perfusion maximum de 100 mg/min.', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Phénobarbital (enfant)'),
  ('MG-ANES-000032-R122', 'La dose de charge de phénytoïne par voie veineuse est de 20 mg/kg (maximum 1 g) sans dépasser un débit de perfusion de 1 mg/kg par minute.', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Phénytoïne — dose de charge (enfant)'),
  ('MG-ANES-000032-R123', 'Chez l''enfant, il n''y a pas actuellement de données cliniques suffisamment fortes pour recommander d''utiliser la fosphénytoïne à la place de la phénytoïne. La fosphénytoïne n''a l''AMM que chez l''enfant de plus de cinq ans.', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Fosphénytoïne — restriction d''AMM (enfant)'),
  ('MG-ANES-000032-R124', 'Elle est utilisée à la posologie de 20 mg/kg d''équivalent phénytoïne avec un débit de perfusion maximum de 3 mg/kg par minute d''équivalent phénytoïne.', 'Fort', 'Pédiatrie', 'Arsenal thérapeutique — posologies (EME non réfractaire) — Thème : Fosphénytoïne — posologie (enfant)'),
  ('MG-ANES-000032-R125', 'En général, il n''est pas indiqué d''induire un coma médicamenteux dans les EME réfractaires non convulsifs et partiels moteurs. Un avis spécialisé est nécessaire.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Non convulsif/partiel moteur'),
  ('MG-ANES-000032-R126', 'Il n''existe pas de définition consensuelle de l''EME réfractaire.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Absence de définition consensuelle'),
  ('MG-ANES-000032-R127', 'En général, on peut définir un EME comme réfractaire lorsqu''il existe une résistance à au moins deux médicaments antiépileptiques différents administrés à posologie adaptée.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Définition pragmatique'),
  ('MG-ANES-000032-R128', 'Les patients en EME convulsif intubés ventilés, n''ayant pas reçu l''association benzodiazépine—autre médicament antiépileptique telle qu''elle a été décrite dans le champ 7, ne doivent pas être considérés comme étant en EME réfractaire ; le traitement devra être complété avant de les traiter comme tel.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Traitement initial incomplet'),
  ('MG-ANES-000032-R129', 'Les diagnostics de pseudo état de mal (origine psychogène) ou de mouvements anormaux d''autre étiologie qu''épileptique doivent être considérés avant de retenir le diagnostic d''état de mal réfractaire.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Écarter les diagnostics différentiels'),
  ('MG-ANES-000032-R130', 'Dans un contexte d''encéphalopathie postanoxique, les myoclonies sont rarement en rapport avec un état de mal réfractaire nécessitant un traitement antiépileptique.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Encéphalopathie postanoxique'),
  ('MG-ANES-000032-R131', 'Les barbituriques, le propofol et le midazolam sont les trois traitements utilisés dans l''EME réfractaire. Il n''y a pas de donnée comparative contrôlée concernant ces trois molécules lors de leur utilisation en cas d''état de mal réfractaire.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Trois traitements de référence'),
  ('MG-ANES-000032-R132', 'Il faut toujours associer des médicaments antiépileptiques aux agents anesthésiques et s''assurer de taux sanguins efficaces des antiépileptiques.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Association systématique'),
  ('MG-ANES-000032-R133', 'Les barbituriques ont l''avantage d''être connus depuis de nombreuses années, et le désavantage de présenter une thésaurisation tissulaire qui en prolonge considérablement la demi-vie plasmatique lors d''administration en continu.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Barbituriques — propriétés'),
  ('MG-ANES-000032-R134', 'Le thiopental est administré en plusieurs bolus de 2 mg/kg en 20 secondes toutes les cinq minutes jusqu''à arrêt des convulsions et selon la tolérance hémodynamique, puis en attendant l''EEG, avec un débit de 3 à 5 mg/kg par heure. La dose d''entretien est adaptée sur les données EEG, et dépend de la tolérance hémodynamique.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Thiopental — posologie'),
  ('MG-ANES-000032-R135', 'Le propofol a l''avantage d''une courte demi-vie d''élimination, et le désavantage d''exposer au risque de développer un syndrome de perfusion de propofol (SPP ou Propofol Infusion Syndrome « PRIS »). Le « SPP » constitue une complication probablement rare mais potentiellement fatale chez les patients en EME réfractaire.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Propofol — profil et risque SPP'),
  ('MG-ANES-000032-R136', 'Le propofol est administré en bolus initial de 2 mg/kg, titré jusqu''à arrêt clinique des convulsions (bolus de 1 mg/kg toutes les cinq minutes), puis en attendant l''EEG à un débit de 2 à 5 mg/kg par heure (parfois transitoirement jusqu''à 10 mg/kg par heure). La dose d''entretien sera adaptée sur les données EEG. Il est recommandé d''y associer des benzodiazépines et de ne pas dépasser la dose de 5 mg/kg par heure au-delà de 48 heures.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Propofol — posologie'),
  ('MG-ANES-000032-R137', 'L''utilisation du propofol, particulièrement à des fortes posologies et au-delà de 48 heures, impose une détermination au moins biquotidienne des lactates, des triglycérides et des enzymes musculaires afin de dépister rapidement un « SPP » qui implique son arrêt immédiat.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Propofol — surveillance du SPP'),
  ('MG-ANES-000032-R138', 'Le midazolam induit une tachyphylaxie importante lors de l''administration prolongée.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Midazolam — tachyphylaxie'),
  ('MG-ANES-000032-R139', 'Le midazolam est administré en bolus initial de 0,1 mg/kg, titré jusqu''à arrêt clinique des convulsions (bolus de 0,05 mg/kg toutes les cinq minutes), puis en attendant l''EEG à un débit de 0,05 à 0,6 mg/kg par heure. La dose d''entretien sera adaptée sur les données EEG et la tolérance hémodynamique.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Midazolam — posologie'),
  ('MG-ANES-000032-R140', 'Dans les cas d''EME réfractaires résistant aux traitements usuels (barbituriques, propofol, midazolam), il peut être utile de les associer entre eux. Le topiramate, le lévétiracétam, la kétamine (contre-indiquée en cas d''hypertension intracrânienne et associée à des benzodiazépines), voire des anesthésiques inhalés peuvent également être, entre autres, considérés.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Associations en cas de résistance'),
  ('MG-ANES-000032-R141', 'La durée de l''administration des médicaments anesthésiques et la cinétique de leur décroissance ne sont pas déterminées.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Durée de traitement non déterminée'),
  ('MG-ANES-000032-R142', 'Il est bien entendu indispensable d''obtenir la suppression clinique de l''EME convulsif. L''objectif minimal sur l''EEG est la suppression des crises.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Suppression clinique et EEG minimal'),
  ('MG-ANES-000032-R143', 'La profondeur optimale de la suppression électroencéphalographique — seule suppression des crises, bouffées-suppressions (burst-suppression) ou tracé isoélectrique — n''est pas établie.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Profondeur de suppression non établie'),
  ('MG-ANES-000032-R144', 'L''administration d''un médicament anesthésique ayant pour cible EEG un tracé de bouffées-suppressions (burst-suppression) pendant 12 à 24 heures est proposée, suivie d''un sevrage progressif sur 12 à 24 heures.', 'Faible', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Cible burst-suppression proposée'),
  ('MG-ANES-000032-R145', 'En cas de reprise de l''EME au décours de l''arrêt du traitement, on peut soit reprendre l''administration du traitement déjà utilisé, soit passer à une autre substance.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Reprise de l''EME après arrêt'),
  ('MG-ANES-000032-R146', 'La poursuite du traitement, même après plusieurs semaines d''EME réfractaire, est justifiée tant qu''il n''y a pas d''argument qui atteste d''une atteinte irréversible du cerveau.', 'Fort', null, 'Champ 8 — État de mal épileptique réfractaire — Thème : Poursuite au long cours'),
  ('MG-ANES-000032-R147', 'Le thiopental est très efficace, mais ses nombreux effets secondaires conduisent à proposer de le réserver aux formes les plus rebelles et de débuter par une perfusion continue de benzodiazépines à fortes doses. La posologie proposée est identique à celle de l''adulte (bolus de 2 mg/kg répétés jusqu''à arrêt des convulsions, suivis d''une perfusion continue de 3 à 5 mg/kg par heure).', 'Fort', 'Pédiatrie', 'Champ 8 — État de mal épileptique réfractaire — Thème : Thiopental (enfant)'),
  ('MG-ANES-000032-R148', 'Le midazolam est la benzodiazépine la mieux étudiée, mais le diazépam semble aussi efficace. Les posologies proposées comportent une dose de charge de 0,15 à 0,50 mg/kg suivie d''une perfusion continue de 0,12 mg/kg par heure, qui peut être augmentée rapidement par paliers jusqu''à 1,4 mg/kg par heure.', 'Fort', 'Pédiatrie', 'Champ 8 — État de mal épileptique réfractaire — Thème : Midazolam — posologie (enfant)'),
  ('MG-ANES-000032-R149', 'La facilité d''emploi du midazolam (hydrosoluble, demi-vie courte) doit être pondérée par la plus grande fréquence de récidives des convulsions observée avec ce médicament.', 'Fort', 'Pédiatrie', 'Champ 8 — État de mal épileptique réfractaire — Thème : Midazolam — mise en garde (enfant)'),
  ('MG-ANES-000032-R150', 'Il est recommandé de ne pas utiliser le propofol dans le traitement des états de mal convulsifs réfractaires chez l''enfant, en raison de l''absence de supériorité démontrée par rapport aux autres traitements et du risque d''accident mortel lié au syndrome de perfusion de propofol, plus fréquent chez l''enfant que chez l''adulte.', 'Fort', 'Pédiatrie', 'Champ 8 — État de mal épileptique réfractaire — Thème : Propofol NON RECOMMANDÉ (enfant)'),
  ('MG-ANES-000032-R151', 'L''expression clinique d''un EME non convulsif est le plus souvent une confusion mentale d''intensité variable.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Expression clinique'),
  ('MG-ANES-000032-R152', 'La réalisation d''un EEG est nécessaire dès que possible lors de la suspicion clinique d''un EME non convulsif.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : EEG nécessaire dès que possible'),
  ('MG-ANES-000032-R153', 'Une collaboration étroite entre le médecin qui demande l''EEG et celui qui l''interprète est indispensable, car le diagnostic d''EME non convulsif est clinique et électroencéphalographique.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Collaboration prescripteur/interprète'),
  ('MG-ANES-000032-R154', 'L''injection d''une benzodiazépine au cours de l''EEG constitue un test diagnostique et thérapeutique qui est positif lorsqu''il normalise l''EEG et fait céder la confusion ou les signes neurologiques. Cependant, sa négativité n''élimine pas ce diagnostic.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Test diagnostique et thérapeutique BZD'),
  ('MG-ANES-000032-R155', 'L''enquête étiologique des états d''absence de novo du sujet âgé doit comporter en premier lieu la recherche de facteurs toxiques et/ou métaboliques comme un sevrage en benzodiazépines ou une imprégnation chronique en médicaments psychotropes.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : États d''absence de novo — sujet âgé'),
  ('MG-ANES-000032-R156', 'Il faut savoir évoquer, chez un sujet épileptique qui présente des états d''absence récurrents, la possibilité d''une aggravation paradoxale de l''épilepsie par certains médicaments antiépileptiques tels que la carbamazépine, la phénytoïne, le vigabatrin, la gabapentine, la tiagabine, dans le cadre d''une épilepsie généralisée idiopathique.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Aggravation paradoxale'),
  ('MG-ANES-000032-R157', 'Le bilan étiologique d''un EME partiel non convulsif inaugural impose de rechercher en premier lieu une affection aiguë du système nerveux central.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Bilan étiologique — EME partiel inaugural'),
  ('MG-ANES-000032-R158', 'La résistance aux benzodiazépines concerne essentiellement les états de mal partiels non convulsifs. Une approche graduelle doit être privilégiée. La phénytoïne ou la fosphénytoïne semblent être les molécules de choix.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Résistance aux benzodiazépines'),
  ('MG-ANES-000032-R159', 'Les comas dus à des encéphalopathies ou agressions cérébrales sévères qui s''accompagnent d''anomalies paroxystiques diffuses à l''EEG doivent être exclus du cadre nosographique des états de mal non convulsifs. La présence d''activités EEG paroxystiques généralisées peut en effet traduire une atteinte cérébrale sévère (en particulier postanoxique), sans phénomène épileptique associé.', 'Faible', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Comas à exclure du cadre nosographique'),
  ('MG-ANES-000032-R160', 'Les anomalies EEG paroxystiques généralisées parfois rencontrées lors d''un coma consécutif à une agression cérébrale sévère (post-traumatique, postanoxique...) sont à différencier de l''EME larvé, terme évolutif d''un EME convulsif généralisé non ou insuffisamment traité, et surtout de l''EME non convulsif qui peut s''accompagner au maximum d''un état catatonique mais non d''un coma.', 'Faible', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Différencier de l''EME larvé/non convulsif'),
  ('MG-ANES-000032-R161', 'La prise en charge thérapeutique d''anomalies EEG paroxystiques généralisées parfois rencontrées lors d''un coma postagression cérébrale n''est pas codifiée. Si un traitement antiépileptique devait être instauré, en particulier devant des anomalies clairement organisées en décharges successives, l''absence d''amélioration électroclinique nette ne doit pas conduire à une escalade thérapeutique.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : PEC thérapeutique non codifiée'),
  ('MG-ANES-000032-R162', 'La mise en place de protocoles dans les diverses structures amenées à prendre en charge des EME est recommandée.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Protocoles de service'),
  ('MG-ANES-000032-R163', 'Ces recommandations, établies début 2008, devront être réactualisées dans un délai maximum de trois ans.', 'Fort', null, 'Champ 9 — États de mal épileptiques non convulsifs — Thème : Actualisation à trois ans')
) as v(code, statement, grade, population, source_section)
where d.source_url = 'https://sfar.org/prise-en-charge-en-situation-durgence-et-en-reanimation-des-etats-de-mal-epileptiques-de-ladulte-et-de-lenfant-nouveau-ne-exclu/'
on conflict (recommendation_code) do nothing;
