-- Migration : Sécurisation des procédures à risques en réanimation (risque
-- infectieux exclu) — Recommandations d'experts SRLF-SFAR, 2008. Méthode
-- RAND/UCLA appropriateness method adaptée SRLF-SFAR (PAS GRADE). Source :
-- rfe-sfar-website/build/content_securisation_proc.json (198 propositions
-- réparties en 8 champs cliniques + 1 zone d'indécision transversale de 3
-- propositions).
--
-- MÉTHODOLOGIE — UN SEUL AXE, PAS DE GRADE DE PREUVE : chaque expert cote
-- sur une échelle continue de 1 à 9 (1 = désaccord total, 9 = accord
-- total) ; trois zones selon la position de la médiane : (1-3) désaccord,
-- (4-6) indécision, (7-9) accord. L'accord (ou le désaccord) est dit
-- "fort" si l'intervalle de la médiane reste à l'intérieur d'une des trois
-- zones, "faible" dans le cas contraire. AUCUN grade de preuve 1+/1-/2+/2-
-- n'est utilisé dans ce document (disclosure explicite de la source
-- elle-même) — `grade` reproduit littéralement 'Fort'/'Faible'/
-- 'Indécision' selon le tag source, jamais converti en une échelle GRADE.
-- `evidence_level` laissé NULL (aucun axe de preuve distinct dans cette
-- méthodologie, contrairement à asthme_aigu_grave/civd/glycemie).
--
-- COMPTAGE — 198 propositions numérotées R001-R198, TOUTES tirées des
-- tableaux "Thème | Recommandation | Accord" des 8 champs + la section
-- transversale "Zone d'indécision". Répartition directe vérifiée par
-- inventaire programmatique exhaustif du JSON : 155 Fort, 35 Faible, 5
-- non cotées ('?', cf. ci-dessous), 3 Indécision (155+35+5+3=198). Le
-- contenu construit ne publie PAS de total officiel agrégé pour ce
-- document (contrairement à plusieurs autres fiches du corpus) — rien à
-- réconcilier, comptage direct retenu tel quel.
--
-- 5 PROPOSITIONS NON COTÉES ('?') DISCLOSÉES PAR LA SOURCE ELLE-MÊME
-- (Champ 3.1 "Structures" uniquement) : le contenu construit introduit
-- explicitement un tag '?' = "Non coté — proposition sans tag d'accord
-- dans le texte source (5 cas, Champ 3.1, disclosure)". Ces 5 propositions
-- SONT migrées (elles appartiennent à la structure numérotée du document,
-- au même titre que les autres), mais avec `grade = NULL` plutôt qu'un
-- grade inventé ou qu'un tag littéral '?' qui ne serait pas une valeur de
-- grade réelle — disclosure fidèle à l'absence de cotation constatée dans
-- la source, jamais un chip fabriqué.
--
-- 3 PROPOSITIONS EN "ZONE D'INDÉCISION" (section transversale, hors des 8
-- champs numérotés, tag 'Indécision' distinct de 'Fort'/'Faible') :
-- catégorie EXPLICITEMENT identifiée comme telle par les auteurs eux-mêmes
-- (médiane 4-6, ni accord ni désaccord) — migrées avec `grade =
-- 'Indécision'`, JAMAIS reclassées en "Fort" ou "Faible" (principe 1.5 du
-- projet : ne jamais résoudre silencieusement une catégorie distincte de
-- la source).
--
-- PÉRIMÈTRE : champ d'application limité aux pratiques de sécurité
-- ("safety practices") pour les patients de réanimation — le RISQUE
-- INFECTIEUX est explicitement exclu du champ de ce document par la
-- source elle-même (couvert par d'autres référentiels SFAR/SRLF/CLIN),
-- disclosure de portée, pas une restriction de mon fait. Recommandations
-- adulte et enfant (Champs 1-7), spécificités pédiatriques regroupées au
-- Champ 8 — `population` laissée NULL sauf pour les 12 lignes du Champ 8
-- (Pédiatrie), taguées `population = 'Pédiatrie'` (voir requête ci-dessous
-- : Réf. 187-198... — indices confirmés par le script d'extraction, cf.
-- disclosure en fin de fichier). Aucune figure, tableau de référence
-- chiffré ou algorithme distinct des tableaux "Thème/Recommandation/
-- Accord" dans ce document (vérifié par la structure JSON) — rien d'autre
-- à exclure.
--
-- SOURCE_SECTION : format "Champ N — <intitulé du champ> (<thème
-- sous-groupe>) [Réf. <rang>]" — ce document ne porte PAS de numérotation
-- Rx.y propre par recommandation dans le texte source (contrairement à la
-- majorité des RFE GRADE du corpus) ; le rang `[Réf. N]` utilisé ici est
-- un ordre de lecture séquentiel du tableau JSON, PAS un identifiant
-- imprimé par la source elle-même — disclosure explicite (même pattern
-- que eer/0020 pour son Champ 4.3 sans repères Rx.y.z individuels).
--
-- À VÉRIFIER (disclosure, pas une invention) :
-- 1. SFAR et SRLF (toutes deux dans le seed Annexe B) liées en
--    document_societies — méthode explicitement décrite comme
--    "SRLF-SFAR", panneau final citant les deux sociétés.
-- 2. Document volumineux (198 recommandations) — 2e plus grande migration
--    de ce corpus après mal_epileptique/0032 (163) — extraction réalisée
--    par script Python (walk programmatique du JSON, pas une
--    transcription manuelle), contrôlée par inventaire exhaustif et tally
--    (155+35+5+3=198, cohérent) avant écriture du fichier SQL final.
-- 3. `freshness_status = 'a_jour'` retenu (cohérent avec `library_final.json`
--    "en vigueur") : CONTRAIREMENT à eclsa/0019, glycemie/0022, hsa/0023 et
--    mal_epileptique/0032, le contenu construit de CETTE fiche ne contient
--    AUCUNE mention explicite d'obsolescence ou d'invitation à se référer à
--    des pratiques plus récentes — seul le document daterait de 2008
--    (technologies/dispositifs médicaux potentiellement évolués depuis),
--    mais en l'absence de disclosure positive de la source elle-même, pas
--    de `revision_detectee` inventé ici (principe : ne jamais déduire une
--    obsolescence non disclosée par la source, même par analogie avec
--    d'autres fiches anciennes du corpus).

insert into public.documents (title, doc_type, original_language, publication_date, source_url, pdf_url, grading_system, freshness_status)
values (
  'Sécurisation des procédures à risques en réanimation : risque infectieux exclu',
  'RFE', 'fr', '2008-01-01',
  'https://sfar.org/securisation-des-procedures-a-risques-en-reanimation-risque-infectieux-exclu/',
  'https://sfar.org/wp-content/uploads/2015/10/2a_AFAR_Texte_court_Securisation-des-procedures-a-risques-en-reanimation.pdf',
  'Méthode RAND/UCLA appropriateness method adaptée SRLF-SFAR (PAS GRADE) : cotation continue 1-9 par les experts, 3 zones (désaccord 1-3, indécision 4-6, accord 7-9) ; "Fort" si la médiane reste dans une zone, "Faible" si elle empiète sur une borne. Aucun grade de preuve 1+/1-/2+/2-. 198 propositions (155 Fort, 35 Faible, 5 non cotées, 3 en zone d''indécision explicite) réparties en 8 champs cliniques, comptage direct sans total officiel source à réconcilier.',
  'a_jour'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/securisation-des-procedures-a-risques-en-reanimation-risque-infectieux-exclu/'
  and s.acronym in ('SFAR', 'SRLF') and s.country_or_region = 'France'
on conflict do nothing;

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/securisation-des-procedures-a-risques-en-reanimation-risque-infectieux-exclu/'
  and s.slug in ('anesthesie_reanimation', 'medecine_intensive_reanimation', 'pediatrie')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, population, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.population, v.source_section,
  'https://sfar.org/securisation-des-procedures-a-risques-en-reanimation-risque-infectieux-exclu/',
  'draft'
from public.documents d, (values
  ('MG-ANES-000041-R001', 'Un événement indésirable (EI) est une situation qui s''écarte des procédures ou résultats habituellement escomptés, potentiellement source de dommage ; inclut les erreurs humaines (procédures) et les EI patients (résultats).', 'Faible', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 1]'),
  ('MG-ANES-000041-R002', 'L''erreur humaine est un écart par rapport à un objectif non atteint lors d''une séquence programmée d''activité mentale ou physique.', 'Faible', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 2]'),
  ('MG-ANES-000041-R003', 'Les événements porteurs de risque (EPR), définis par le décret sur l''accréditation des médecins des spécialités à risque, sont des EI à l''exclusion des EI graves.', 'Faible', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 3]'),
  ('MG-ANES-000041-R004', 'Un événement indésirable patient est une complication directement liée aux soins et non à la pathologie sous-jacente du patient.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 4]'),
  ('MG-ANES-000041-R005', 'Un événement indésirable grave patient est une complication directement liée aux soins entraînant un risque vital, une prolongation de séjour, la nécessité de gestes invasifs, ou des séquelles invalidantes.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 5]'),
  ('MG-ANES-000041-R006', 'Un EI ou un EPR doit être considéré comme inévitable lorsque les soins ont été délivrés conformément à l''état de l''art.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 6]'),
  ('MG-ANES-000041-R007', 'Un EI ou un EPR doit être considéré comme évitable ou possiblement évitable lorsqu''on a mis en évidence une ou plusieurs erreurs médicales associées ou non à un ou plusieurs défauts système (structure, organisation, management), ou un ou plusieurs défauts système sans erreur médicale.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 7]'),
  ('MG-ANES-000041-R008', 'En dehors des situations caricaturales, seule une analyse fine pourra distinguer les EI évitables de ceux qui ne le sont pas, en raison de l''importance des comorbidités comme facteurs de risque.', 'Faible', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 8]'),
  ('MG-ANES-000041-R009', 'Les procédures à risque pour le patient de réanimation sont principalement des procédures invasives.', 'Faible', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 9]'),
  ('MG-ANES-000041-R010', 'La sécurisation des procédures à risque est une démarche qui permet d''identifier et de traiter les différentes sources de risque afin de réduire au minimum le risque pour les patients.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 10]'),
  ('MG-ANES-000041-R011', 'Les procédures de sécurisation (« safety practices ») sont des procédures de soins et/ou structurelles/organisationnelles qui préviennent, diminuent la fréquence de survenue, ou atténuent les conséquences des erreurs et des EI.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (EI / EPR) [Réf. 11]'),
  ('MG-ANES-000041-R012', 'La mise en place d''un indicateur nécessite au préalable d''avoir défini l''objectif de sécurisation des soins surveillé par cet indicateur.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (Indicateurs) [Réf. 12]'),
  ('MG-ANES-000041-R013', 'Un indicateur doit être analysé systématiquement et de façon régulière.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (Indicateurs) [Réf. 13]'),
  ('MG-ANES-000041-R014', 'En cas de variation d''un indicateur susceptible d''être le témoin d''un EPR, une analyse systémique doit être réalisée afin d''identifier les causes racines de l''EPR.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (Indicateurs) [Réf. 14]'),
  ('MG-ANES-000041-R015', 'Un indicateur doit être acceptable, valide, pertinent, fiable et compréhensible.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (Indicateurs) [Réf. 15]'),
  ('MG-ANES-000041-R016', 'Les indicateurs concernant la sécurisation d''une procédure de soins doivent être en nombre limité.', 'Fort', null, 'Champ 1 — Sécurisation des soins et indicateurs : taxonomie générale (Indicateurs) [Réf. 16]'),
  ('MG-ANES-000041-R017', 'Il faut standardiser les définitions concernant les erreurs médicales, les EI et leur évitabilité.', 'Fort', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 17]'),
  ('MG-ANES-000041-R018', 'Les erreurs médicales et les EI patients doivent être classés en fonction de leur gravité.', 'Fort', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 18]'),
  ('MG-ANES-000041-R019', 'La standardisation de la méthode de recueil des erreurs médicales et des événements indésirables patients est nécessaire.', 'Fort', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 19]'),
  ('MG-ANES-000041-R020', 'Quelle que soit la méthode, il est recommandé que ce recueil soit non punitif, confidentiel et indépendant.', 'Faible', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 20]'),
  ('MG-ANES-000041-R021', 'Le recueil régulier par la déclaration volontaire, bien que source de biais, permet de développer une culture sécurité.', 'Fort', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 21]'),
  ('MG-ANES-000041-R022', 'Il est recommandé de privilégier l''analyse des erreurs médicales et des EI patients évitables.', 'Faible', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 22]'),
  ('MG-ANES-000041-R023', 'Il est important de pouvoir identifier indépendamment les erreurs des EI patients.', 'Faible', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 23]'),
  ('MG-ANES-000041-R024', 'Il est important d''étudier les facteurs permettant la détection et la récupération de ces erreurs.', 'Fort', null, 'Champ 2 — Épidémiologie (Épidémiologie) [Réf. 24]'),
  ('MG-ANES-000041-R025', 'Le service de réanimation doit comporter des chambres individuelles et des lits d''USC situés à proximité des lits de réanimation.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 25]'),
  ('MG-ANES-000041-R026', 'Le service de réanimation doit pouvoir disposer de résultats biologiques fiables, obtenus rapidement et dont la traçabilité est assurée (pneumatique, biologie délocalisée).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 26]'),
  ('MG-ANES-000041-R027', 'Il existe une procédure chariot d''urgence.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 27]'),
  ('MG-ANES-000041-R028', 'Informatisation de l''unité de soins.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 28]'),
  ('MG-ANES-000041-R029', 'L''identitovigilance est assurée.', null, null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 29]'),
  ('MG-ANES-000041-R030', 'L''informatisation du dossier médical et de la prescription doit être développée.', null, null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 30]'),
  ('MG-ANES-000041-R031', 'La dispensation médicamenteuse est personnalisée.', null, null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 31]'),
  ('MG-ANES-000041-R032', 'Les résultats des examens biologiques et d''imagerie médicale sont disponibles dans le service.', null, null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 32]'),
  ('MG-ANES-000041-R033', 'Il existe une procédure partagée avec le plateau médico-technique pour la transmission des résultats urgents (par exemple : hyperkaliémie).', null, null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.1 Structures) [Réf. 33]'),
  ('MG-ANES-000041-R034', 'Il existe une relation entre le volume d''actes réalisés et la performance en termes de sécurité patient.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.2 Activité) [Réf. 34]'),
  ('MG-ANES-000041-R035', 'Lorsqu''une technique médicale n''est pas disponible localement, celle-ci doit faire l''objet d''une convention formalisée avec un service prestataire.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.2 Activité) [Réf. 35]'),
  ('MG-ANES-000041-R036', 'Le responsable médical du service et/ou du pôle doit être impliqué dans la gestion du recrutement du personnel soignant.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3 Organisation) [Réf. 36]'),
  ('MG-ANES-000041-R037', 'Les compétences médicales et paramédicales doivent être identiques en réanimation et en USC.', 'Faible', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3 Organisation) [Réf. 37]'),
  ('MG-ANES-000041-R038', 'Si le médecin de garde ne fait pas partie de l''équipe médicale du service, un médecin de cette équipe doit pouvoir être consulté pendant la garde.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.1 Travail médical) [Réf. 38]'),
  ('MG-ANES-000041-R039', 'Il existe une procédure d''appel du médecin réanimateur (bip, téléphone…).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.1 Travail médical) [Réf. 39]'),
  ('MG-ANES-000041-R040', 'Il existe un programme de formation dans le service concernant les internes et les médecins de l''équipe.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.1 Travail médical) [Réf. 40]'),
  ('MG-ANES-000041-R041', 'Il existe un cadre de santé de proximité dont l''activité est dédiée à la réanimation.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 41]'),
  ('MG-ANES-000041-R042', 'Les nouvelles IDE doivent bénéficier d''une période d''intégration d''un mois, faisant l''objet d''une traçabilité (livret d''intégration) ; la présence d''un infirmier tuteur est souhaitable durant cette période.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 42]'),
  ('MG-ANES-000041-R043', 'Une attention particulière doit être portée sur les équipes de nuit, qui doivent bénéficier soit de formations spécifiques, soit de périodes de rotation de jour.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 43]'),
  ('MG-ANES-000041-R044', 'Les transmissions entre équipes médicales et/ou soignantes doivent être formalisées.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 44]'),
  ('MG-ANES-000041-R045', 'Il est nécessaire d''identifier, selon la dimension du service, un ou plusieurs agents responsables de la logistique (matériel, chariot d''urgence et de déplacement extérieur).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 45]'),
  ('MG-ANES-000041-R046', 'Il est souhaitable que le service dispose d''outils permettant l''évaluation ponctuelle de la charge de travail.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.2 Travail soignant) [Réf. 46]'),
  ('MG-ANES-000041-R047', 'L''organisation protocolisée est souhaitable ; les protocoles concernant les procédures de soins doivent être produits localement ou faire l''objet d''une appropriation locale s''il s''agit de protocoles extérieurs, et doivent faire l''objet de fréquents rappels (affiches, aide-mémoire de poche, informatique, staff).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 47]'),
  ('MG-ANES-000041-R048', 'Les procédures et/ou situations cliniques à risque doivent périodiquement faire l''objet de procédures de formation (prise en charge de l''arrêt cardiorespiratoire, de l''intubation difficile, tamponnade).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 48]'),
  ('MG-ANES-000041-R049', 'Ces situations doivent faire l''objet, a posteriori, de réunions de débriefing de l''ensemble de l''équipe médicale et paramédicale.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 49]'),
  ('MG-ANES-000041-R050', 'D''une manière générale, le service doit disposer de check-lists pour les procédures à risques reconnues et identifiées localement, a fortiori lorsqu''elles ont fait l''objet de recommandations par les sociétés savantes (SFAR/SRLF).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 50]'),
  ('MG-ANES-000041-R051', 'Le service doit disposer d''une procédure écrite de régulation d''admission des patients.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 51]'),
  ('MG-ANES-000041-R052', 'Le service doit disposer d''une procédure écrite de sortie des patients, comportant impérativement une fiche de liaison IDE et une synthèse médicale afin d''assurer la continuité des soins.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.3.3 Protocoles) [Réf. 52]'),
  ('MG-ANES-000041-R053', 'Le service de réanimation doit organiser périodiquement des réunions de morbi-mortalité, souhaitablement conformes aux recommandations des sociétés savantes (SFAR/SRLF).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 53]'),
  ('MG-ANES-000041-R054', 'Le service dispose d''une méthode de recueil des EI ; chaque service détermine, a priori, quels EI il va surveiller à partir de quels indicateurs et avec quel objectif.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 54]'),
  ('MG-ANES-000041-R055', 'Certaines procédures à risque doivent faire l''objet d''une réflexion bénéfice/risque dont la traçabilité est assurée dans le dossier patient.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 55]'),
  ('MG-ANES-000041-R056', 'Les audits de soins peuvent être intégrés dans l''évaluation des pratiques professionnelles (EPP) pour le personnel médical ; ils sont réalisés au mieux à partir des documents élaborés par les sociétés savantes (SFAR/SRLF).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 56]'),
  ('MG-ANES-000041-R057', 'Le service doit disposer d''indicateurs d''alerte d''épuisement professionnel (demandes de changement, absentéisme).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 57]'),
  ('MG-ANES-000041-R058', 'Il existe une procédure d''aide pour les agents en difficultés (raisons personnelles ou professionnelles).', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 58]'),
  ('MG-ANES-000041-R059', 'Il existe une formalisation et une traçabilité dans le dossier du patient des décisions de limitation et d''arrêt des thérapeutiques actives et de toute décision éthique.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.4 Culture sécurité) [Réf. 59]'),
  ('MG-ANES-000041-R060', 'Le service de réanimation tient un registre des refus d''admission indiquant les motifs.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.5 Tableau de bord) [Réf. 60]'),
  ('MG-ANES-000041-R061', 'Le service de réanimation dispose d''indicateurs de procédures et de résultats spécifiques concernant la sécurité des patients.', 'Fort', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.5 Tableau de bord) [Réf. 61]'),
  ('MG-ANES-000041-R062', 'Le service de réanimation dispose d''indicateurs de résultats permettant une comparaison interne ou externe.', 'Faible', null, 'Champ 3 — Procédures de sécurisation structurelles et managériales (3.5 Tableau de bord) [Réf. 62]'),
  ('MG-ANES-000041-R063', 'Les dispositifs médicaux (DM) induisent une série de risques de leur conception à leur mise au rebut, notamment le risque d''erreurs humaines qui doivent être maîtrisées.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 63]'),
  ('MG-ANES-000041-R064', 'D''une manière générale, les principaux éléments de sécurisation doivent reposer sur la formation des utilisateurs, l''entretien et la vérification des DM et l''application rigoureuse des règles de matériovigilance.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 64]'),
  ('MG-ANES-000041-R065', 'Une collaboration entre services cliniques et services biomédicaux est nécessaire.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 65]'),
  ('MG-ANES-000041-R066', 'Les différents acteurs intervenant dans la gestion des DM doivent être : un référent biomédical ingénieur par service (ou pôle) et/ou par type de matériel, un référent médical par service ou pôle, enfin un référent paramédical et/ou un technicien délocalisé par service ou pôle.', 'Faible', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 66]'),
  ('MG-ANES-000041-R067', 'Il est recommandé de mettre en place une gestion informatisée du parc des DM.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 67]'),
  ('MG-ANES-000041-R068', 'Le suivi informatisé d''un DM doit notamment prendre en compte la date de réception, le numéro de série, le lieu de stockage, l''agenda de maintenance et de mise à niveau, la notification des pannes (type, fréquence et durée d''immobilisation), enfin la fréquence des défauts utilisateurs.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.1 Principes) [Réf. 68]'),
  ('MG-ANES-000041-R069', 'Le cahier des charges définissant précisément le besoin qualitatif et quantitatif doit être établi en collaboration entre services cliniques et services biomédicaux.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.2 Implantation) [Réf. 69]'),
  ('MG-ANES-000041-R070', 'Il faut prendre en compte des éléments tels que : durée de garantie, contrat de maintenance, proximité et disponibilité du service après-vente.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.2 Implantation) [Réf. 70]'),
  ('MG-ANES-000041-R071', 'Les certificats de conformité aux textes réglementaires applicables à la classe du dispositif doivent être exigés.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.2 Implantation) [Réf. 71]'),
  ('MG-ANES-000041-R072', 'Avant implantation, il est recommandé d''effectuer un essai sur site en conditions réelles avec un panel représentatif d''utilisateurs pour identifier les situations locales spécifiques à risque.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.2 Implantation) [Réf. 72]'),
  ('MG-ANES-000041-R073', 'En cas de prêt de matériel, une fiche de mise à disposition doit être validée et signée par la société, les services cliniques et biomédicaux.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.2 Implantation) [Réf. 73]'),
  ('MG-ANES-000041-R074', 'Il faut programmer et effectuer la formation des services cliniques et biomédicaux avant la réception du DM ; cette formation doit faire l''objet d''une traçabilité.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.3 Mise en service) [Réf. 74]'),
  ('MG-ANES-000041-R075', 'À la livraison, il faut vérifier que l''équipement correspond à l''intégralité de la commande (accessoires et consommables éventuels).', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.3 Mise en service) [Réf. 75]'),
  ('MG-ANES-000041-R076', 'Le DM doit être inscrit à l''inventaire du service.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.3 Mise en service) [Réf. 76]'),
  ('MG-ANES-000041-R077', 'Si le DM est partagé par différents secteurs, il est recommandé de déterminer son périmètre fonctionnel (par exemple établissement d''une convention d''utilisation).', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.3 Mise en service) [Réf. 77]'),
  ('MG-ANES-000041-R078', 'L''établissement de check-lists adaptées localement et à chaque type de matériel est recommandé pour vérifier un bon fonctionnement du DM avant chaque utilisation ; ces check-lists doivent faire l''objet d''une traçabilité permettant d''identifier au minimum l''opérateur, la date, le type de dysfonctionnement et préciser la liste des fonctionnalités non opérationnelles « bloquantes ».', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 78]'),
  ('MG-ANES-000041-R079', 'Si des check-lists de contrôle sont prévues par le constructeur et intégrées au logiciel du matériel, il faut les respecter et les compléter éventuellement par les check-lists locales.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 79]'),
  ('MG-ANES-000041-R080', 'Il faut rédiger une fiche d''alerte incidente pour tout dysfonctionnement, panne ou arrêt intempestif, information écran fausse.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 80]'),
  ('MG-ANES-000041-R081', 'Les maintenances préventives et curatives doivent être organisées par le service biomédical et faire l''objet de procédures écrites et d''une traçabilité.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 81]'),
  ('MG-ANES-000041-R082', 'Une procédure en cas de panne, adaptée à chaque type de matériel, doit être prévue par le service biomédical et comporter au minimum la disponibilité du matériel de suppléance et l''identification des intervenants à contacter 24 h/24 et 7 j/7.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 82]'),
  ('MG-ANES-000041-R083', 'Il est recommandé d''organiser des formations régulièrement pour les utilisateurs en cas de renouvellement des personnels, en cas de fréquence anormale du nombre de défauts utilisateurs ou lors de mise à niveau des matériels.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 83]'),
  ('MG-ANES-000041-R084', 'Il faut éviter de laisser le parc atteindre l''obsolescence en anticipant le remplacement du DM quand nécessaire (année de mise en service, nombre d''heures d''utilisation, concept dépassé et disparition des consommables).', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 84]'),
  ('MG-ANES-000041-R085', 'Lors de la réforme du DM, il faut retirer également les consommables pour éviter toute confusion avec d''autres DM de même catégorie.', 'Fort', null, 'Champ 4 — Procédures de sécurisation du matériel (4.4 Utilisation) [Réf. 85]'),
  ('MG-ANES-000041-R086', 'Chaque unité de réanimation doit disposer d''un chariot d''intubation dont la composition, vérifiée quotidiennement, est conforme aux recommandations de la conférence d''experts sur intubation difficile.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 86]'),
  ('MG-ANES-000041-R087', 'Avant toute intubation en réanimation, il est recommandé de : scoper le patient et vérifier la présence du matériel nécessaire dans la chambre ; s''assurer du bon fonctionnement de l''aspiration et de la source d''oxygène (haut débit relié au ballon et au masque facial) ; vérifier le bon fonctionnement du respirateur auquel le patient sera branché immédiatement après l''intubation ; préoxygéner tous les patients avec une FiO2 à 1.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 87]'),
  ('MG-ANES-000041-R088', 'S''il n''y a pas de contre-indications, un remplissage vasculaire est souhaitable.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 88]'),
  ('MG-ANES-000041-R089', 'Deux opérateurs (deux médecins ou un médecin et une infirmière) doivent être présents systématiquement au moment de l''intubation.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 89]'),
  ('MG-ANES-000041-R090', 'Si l''indication d''une sédation continue a été posée, celle-ci doit être préparée avant et administrée immédiatement après l''intubation.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 90]'),
  ('MG-ANES-000041-R091', 'Il est préférable d''utiliser une lame métallique pour la laryngoscopie.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 91]'),
  ('MG-ANES-000041-R092', 'Il faut assurer une traçabilité dans le dossier médical de toutes les intubations (en particulier difficiles).', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 92]'),
  ('MG-ANES-000041-R093', 'En dehors des contre-indications, il faut utiliser l''induction à séquence rapide (ISR).', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 93]'),
  ('MG-ANES-000041-R094', 'Le contrôle de la bonne position de la sonde d''intubation à l''aide d''un capnographe (EtCO2) doit être privilégié si le service en est doté.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 94]'),
  ('MG-ANES-000041-R095', 'Les paramètres de la ventilation mécanique doivent être réadaptés à distance de l''intubation.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.1 Intubation) [Réf. 95]'),
  ('MG-ANES-000041-R096', 'La trachéotomie doit être réalisée sous anesthésie générale avec curarisation appropriée.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 96]'),
  ('MG-ANES-000041-R097', 'Si la technique percutanée a été choisie, un fibroscope bronchique doit être utilisé.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 97]'),
  ('MG-ANES-000041-R098', 'Lorsque l''indication d''une trachéotomie percutanée a été posée, il faut s''assurer qu''un chirurgien (ORL si possible) puisse, en cas d''échec, réaliser en urgence une trachéotomie chirurgicale.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 98]'),
  ('MG-ANES-000041-R099', 'L''hémostase doit être vérifiée (TP > 50 %, TCA < 1,5 fois le témoin, plaquettes > 50 000/mm³) et l''héparinothérapie standard curative interrompue de manière momentanée, avec respect d''un délai en cas d''HBPM.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 99]'),
  ('MG-ANES-000041-R100', 'Un plateau d''intubation doit être prêt en cas de difficultés, ainsi qu''une boîte chirurgicale si la technique percutanée a été choisie.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 100]'),
  ('MG-ANES-000041-R101', 'Le système d''aspiration murale avec canule d''aspiration stérile doit être vérifié.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.2 Trachéotomie) [Réf. 101]'),
  ('MG-ANES-000041-R102', 'La prévention de l''auto-extubation et de ses conséquences éventuelles nécessite : la présence d''un set complet d''intubation dont la vérification et la traçabilité dans un carnet de bord daté/signé est assurée quotidiennement ; la présence d''un protocole d''évaluation de la sédation et de la sevrabilité ; le repérage de la position des sondes après contrôle radiographique retranscrit lors des transmissions infirmières ; la surveillance de l''état cutané (escarres nez/bouche/oreilles) et l''adaptation des systèmes d''attaches.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.3 VM invasive) [Réf. 102]'),
  ('MG-ANES-000041-R103', 'La prévention des autres EI (pneumopathies nosocomiales notamment) nécessite : la surélévation de la tête du lit (> 30°) ; des soins de bouche une fois par équipe ; une procédure d''aspiration propre (sonde à usage unique, port de gants) ; le contrôle radiographique de la sonde gastrique.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.3 VM invasive) [Réf. 103]'),
  ('MG-ANES-000041-R104', 'L''optimisation de la ventilation mécanique en termes de sécurité patient nécessite : la vérification de l''intégrité des tuyaux/circuits et de la présence d''eau dans les humidificateurs (une fois par équipe) ; la surveillance de la pression du ballonnet une fois par équipe, retranscrite sur la feuille de surveillance ; la présence permanente d''un système d''aspiration fonctionnel ; la prescription écrite au démarrage de la VM des conditions de ventilation (alarmes incluses), refaite à chaque changement de réglage.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.3 VM invasive) [Réf. 104]'),
  ('MG-ANES-000041-R105', 'Le processus de sevrage doit être envisagé aussitôt que possible dans la prise en charge d''une IRA.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 105]'),
  ('MG-ANES-000041-R106', 'Il est recommandé d''évaluer quotidiennement la sevrabilité sur des critères simples de stabilité respiratoire, hémodynamique et neurologique, et de réaliser une épreuve de sevrage en VS dès que ces critères sont remplis — les deux étapes essentielles à l''identification des patients susceptibles d''être sevrés.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 106]'),
  ('MG-ANES-000041-R107', 'Les critères prédictifs de l''issue du sevrage ne doivent pas être attendus et/ou obtenus pour réaliser l''épreuve de sevrage.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 107]'),
  ('MG-ANES-000041-R108', 'La tolérance clinique d''une épreuve de sevrage doit être considérée comme le meilleur test pour juger a priori des capacités de déventilation d''un patient.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 108]'),
  ('MG-ANES-000041-R109', 'L''épreuve de sevrage doit être réalisée sur pièce en T (VS/T) ou en aide inspiratoire (AI) d''un niveau minimal de 7 cmH2O, avec ou sans PEP externe (≤ 5 cmH2O), pour une durée minimale de 30 minutes.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 109]'),
  ('MG-ANES-000041-R110', 'Le succès de l''épreuve de sevrage doit faire procéder à l''extubation dans les suites immédiates, après avoir éliminé des facteurs d''échec d''extubation.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 110]'),
  ('MG-ANES-000041-R111', 'L''échec de l''épreuve de sevrage doit faire imposer d''en rechercher la ou les causes et leur éventuelle réversibilité.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 111]'),
  ('MG-ANES-000041-R112', 'Chez le patient difficile ou potentiellement difficile à sevrer, la sécurisation du sevrage doit comprendre : la réalisation d''une épreuve de sevrage en AI ± PEP sur 120 minutes maximum ; la réalisation d''un gaz du sang artériel au cours ou en fin d''épreuve ; le recours à une stratégie de sevrage progressif privilégiant l''AI ± PEP dégressive.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 112]'),
  ('MG-ANES-000041-R113', 'La VNI peut être utilisée comme technique de sevrage permettant l''extubation précoce chez les patients BPCO hypercapniques.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 113]'),
  ('MG-ANES-000041-R114', 'Il peut être utile de mettre en place des protocoles de sevrage.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 114]'),
  ('MG-ANES-000041-R115', 'Il peut être utile d''utiliser des logiciels informatisés.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.4 Sevrage VM) [Réf. 115]'),
  ('MG-ANES-000041-R116', 'Avant d''envisager une extubation, il faut évaluer la capacité du patient à tousser et à évacuer ses sécrétions.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.5 Extubation) [Réf. 116]'),
  ('MG-ANES-000041-R117', 'Il n''y a pas lieu de réaliser systématiquement un test de fuite lors de l''extubation des patients de réanimation.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.5 Extubation) [Réf. 117]'),
  ('MG-ANES-000041-R118', 'Le test de fuite est recommandé chez les patients à risque.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.5 Extubation) [Réf. 118]'),
  ('MG-ANES-000041-R119', 'Chez les patients à très haut risque, chez qui la réalisation d''une trachéotomie peut être difficile, il faut discuter la pertinence d''une extubation réalisée au bloc opératoire en présence d''un chirurgien ORL.', 'Faible', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.5 Extubation) [Réf. 119]'),
  ('MG-ANES-000041-R120', 'La VNI doit représenter la stratégie ventilatoire sécuritaire pour la prise en charge de l''IRA hypercapnique des patients BPCO et de l''OAP cardiogénique.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 120]'),
  ('MG-ANES-000041-R121', 'Dans la prise en charge de l''IRA hypoxémique (cœur et poumons antérieurement sains), l''analyse du rapport bénéfices/risques doit prendre en compte le risque accru de mortalité en cas d''échec de la VNI.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 121]'),
  ('MG-ANES-000041-R122', 'L''application de la VNI à l''IRA hypoxémique doit dans tous les cas être menée dans un milieu sécurisé de réanimation pour ne pas retarder le moment de l''intubation.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 122]'),
  ('MG-ANES-000041-R123', 'Quel que soit le type d''IRA (hypercapnique ou hypoxémique), les patients les plus graves sous VNI doivent être pris en charge et surveillés en réanimation.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 123]'),
  ('MG-ANES-000041-R124', 'La maîtrise de la VNI doit représenter un objectif de formation théorique et pratique des personnels médicaux et paramédicaux au sein des services de réanimation.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 124]'),
  ('MG-ANES-000041-R125', 'La pratique de la VNI implique une bonne connaissance des indications, des contre-indications et des facteurs prédictifs d''échec de la technique.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 125]'),
  ('MG-ANES-000041-R126', 'L''élaboration de protocoles de soins, propres au service, est recommandée pour favoriser l''implantation de la technique et ses résultats.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 126]'),
  ('MG-ANES-000041-R127', 'Le matériel de VNI disponible (masques, ventilateurs, humidificateurs) doit être adapté à la pathologie et à la gravité des patients pris en charge.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 127]'),
  ('MG-ANES-000041-R128', 'La sécurisation de la VNI passe par l''optimisation de ses modalités pratiques : choix d''un masque facial en première intention ; humidification des gaz inspirés (humidificateur chauffant si hypercapnie grave/intolérance) ; retrait du raccord annelé en cas d''IRA hypercapnique ; choix d''un ventilateur de réanimation chez les patients les plus à risque d''échec ; choix d''un mode à double niveau de pression en première intention hors OAP cardiogénique ; augmentation graduelle du niveau d''assistance jusqu''au réglage optimal ; réglage du trigger inspiratoire, de la pente de pressurisation, du niveau d''AI et du cyclage inspiration/expiration ; réglage adapté des alarmes du ventilateur et de la ventilation d''apnée.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 128]'),
  ('MG-ANES-000041-R129', 'L''application continue de la VNI doit être privilégiée initialement jusqu''à une amélioration clinique et gazométrique franche, avant d''envisager un mode séquentiel (alternance VNI/VS).', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 129]'),
  ('MG-ANES-000041-R130', 'Les risques d''échec de la VNI doivent imposer une surveillance initiale rapprochée au cours des premières heures pour juger de la réponse à la technique.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 130]'),
  ('MG-ANES-000041-R131', 'La surveillance de la VNI doit être avant tout clinique, mais doit s''aider des gaz du sang, des paramètres et des courbes du ventilateur pour optimiser les réglages et la tolérance de la technique.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 131]'),
  ('MG-ANES-000041-R132', 'En l''absence d''échec, l''arrêt de la VNI suppose au préalable une évaluation clinique et gazométrique de l''autonomie ventilatoire du patient en VS sur une période de 6 à 12 heures.', 'Fort', null, 'Champ 5 — Sécurisation au cours de la ventilation mécanique (5.6 VNI) [Réf. 132]'),
  ('MG-ANES-000041-R133', 'Le rangement des drogues vasoactives doit tenir compte du risque de confusion entre différentes ampoules ; l''étiquetage des seringues doit être suffisamment explicite et clair pour éviter toute confusion.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 133]'),
  ('MG-ANES-000041-R134', 'Les médicaments vasoactifs doivent être administrés par voie intraveineuse et de façon continue grâce à une seringue pour perfusion continue.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 134]'),
  ('MG-ANES-000041-R135', 'La voie d''administration veineuse centrale doit toujours être privilégiée ; la voie périphérique est possible pour la dopamine et pour la dobutamine à faible dose (≤ 5 µg/kg/min) ; en urgence, en attente de l''insertion d''un cathéter veineux central, l''administration peut être débutée sur une voie veineuse périphérique.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 135]'),
  ('MG-ANES-000041-R136', 'L''utilisation de pompes de perfusion munies de logiciels permettant le relais automatique des seringues contenant une drogue vasoactive doit être privilégiée.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 136]'),
  ('MG-ANES-000041-R137', 'Le raccord de la voie de perfusion des amines vasoactives à la voie de perfusion principale doit se faire par l''intermédiaire d''une tubulure de petit calibre et le plus près possible du patient.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 137]'),
  ('MG-ANES-000041-R138', 'Les systèmes utilisés pour le relais des seringues destinées à l''administration de drogues vasoactives doivent être munis d''une pré-alarme sonore pour la validation de la procédure automatique du relais.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 138]'),
  ('MG-ANES-000041-R139', 'Le relais des seringues doit faire l''objet d''une procédure de soins standardisée dans le service de réanimation.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 139]'),
  ('MG-ANES-000041-R140', 'La dilution des drogues vasoactives doit faire l''objet d''une procédure de soins standardisée dans le service de réanimation.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.1 Vasoactifs) [Réf. 140]'),
  ('MG-ANES-000041-R141', 'Il faut utiliser du matériel entièrement transparent permettant d''identifier clairement les bulles présentes dans le circuit de cathétérisme central artériel ou veineux.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2 KT central) [Réf. 141]'),
  ('MG-ANES-000041-R142', 'Les connexions de la ligne de perfusion d''un cathéter central artériel ou veineux doivent utiliser un système à vis (type Luer-Lock).', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2 KT central) [Réf. 142]'),
  ('MG-ANES-000041-R143', 'Les robinets de la ligne de perfusion d''un cathéter central artériel ou veineux doivent être clairement identifiés afin d''éviter le risque d''injections accidentelles sur cette ligne.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2 KT central) [Réf. 143]'),
  ('MG-ANES-000041-R144', 'Après l''ablation d''un cathéter central artériel ou veineux, il faut vérifier qu''il a été retiré dans son ensemble.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2 KT central) [Réf. 144]'),
  ('MG-ANES-000041-R145', 'Un cathéter artériel ne doit pas être posé sur une artère terminale (artère humérale).', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 145]'),
  ('MG-ANES-000041-R146', 'Les sites d''insertion possibles d''un cathéter artériel sont les artères radiales, fémorales et pédieuses.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 146]'),
  ('MG-ANES-000041-R147', 'La recherche d''une circulation collatérale palmaire par le test d''Allen est un préalable à la pose par voie radiale ; ce test peut être remplacé par le signal de pléthysmographie aux premiers et derniers doigts de la main.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 147]'),
  ('MG-ANES-000041-R148', 'Un cathéter artériel ne doit pas être inséré dans des prothèses vasculaires ; il faut rechercher régulièrement une ischémie du membre d''aval (retrait du cathéter et exploration/surveillance de la vascularisation en cas de signe d''ischémie) ; privilégier les cathéters de petite longueur (3 à 5 cm) pour la voie radiale.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 148]'),
  ('MG-ANES-000041-R149', 'Il faut utiliser un système de purge du cathéter artériel assurant un débit continu d''au minimum 2 mL/h, incluant la possibilité d''une purge manuelle.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 149]'),
  ('MG-ANES-000041-R150', 'Il n''y a pas d''argument pour pratiquer une anticoagulation systématique de la ligne artérielle.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 150]'),
  ('MG-ANES-000041-R151', 'Après l''ablation du cathéter artériel, il faut comprimer le point de ponction pendant quelques minutes jusqu''à l''arrêt de tout saignement.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.1 KT artériel) [Réf. 151]'),
  ('MG-ANES-000041-R152', 'Le cathétérisme veineux central doit être effectué par ou avec l''aide d''un opérateur expérimenté.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 152]'),
  ('MG-ANES-000041-R153', 'La voie sous-clavière doit être évitée en cas d''anomalie de l''hémostase, en cas d''hypoxémie sévère (PaO2/FiO2 < 200) et en cas d''anomalie anatomique.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 153]'),
  ('MG-ANES-000041-R154', 'En cas d''anomalie importante de l''hémostase, la voie fémorale doit être préférée pour le cathétérisme veineux central.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 154]'),
  ('MG-ANES-000041-R155', 'Lorsque la deuxième tentative de ponction veineuse a échoué, il est conseillé de changer de site, d''opérateur ou de technique (repérage ultrasonographique).', 'Faible', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 155]'),
  ('MG-ANES-000041-R156', 'Le repérage ultrasonographique peut améliorer le taux de succès du cathétérisme veineux, surtout pour la voie jugulaire interne, sans augmenter le temps de cathétérisme.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 156]'),
  ('MG-ANES-000041-R157', 'Un contrôle radiographique du thorax doit être effectué après la pose d''un cathéter veineux sous-clavier afin de rechercher l''absence de pneumothorax et de contrôler la bonne position du cathéter.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 157]'),
  ('MG-ANES-000041-R158', 'Afin d''éviter toute érosion endovasculaire et effraction intra-péricardique, l''extrémité des cathéters veineux insérés dans le territoire cave supérieur doit être située au niveau de la carène ; en cas de mauvaise position, le cathéter doit être retiré de quelques centimètres.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.2.2 KT veineux central) [Réf. 158]'),
  ('MG-ANES-000041-R159', 'La sécurisation de la procédure de pose d''un cathéter veineux central s''applique à la pose du désilet préalable à l''insertion du cathéter artériel pulmonaire.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 159]'),
  ('MG-ANES-000041-R160', 'L''utilisation du cathéter artériel pulmonaire est contre-indiquée par la présence d''une sonde d''entraînement intracardiaque.', 'Faible', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 160]'),
  ('MG-ANES-000041-R161', 'Lors de l''introduction du cathéter dans les cavités cardiaques, une surveillance permanente du rythme doit être effectuée afin de rechercher les troubles du rythme cardiaque.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 161]'),
  ('MG-ANES-000041-R162', 'Un contrôle de la radiographie de thorax doit être effectué après l''insertion du cathéter artériel pulmonaire afin de vérifier sa position.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 162]'),
  ('MG-ANES-000041-R163', 'Le dégonflement du ballonnet doit être systématiquement vérifié après que ce dernier a été utilisé.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 163]'),
  ('MG-ANES-000041-R164', 'Le matériel et les médicaments nécessaires au traitement d''un trouble du rythme et d''un trouble conductif doivent être disponibles rapidement lors de la pose d''un cathéter artériel pulmonaire.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 164]'),
  ('MG-ANES-000041-R165', 'Le cathéter artériel pulmonaire doit être maintenu en place le moins longtemps possible ; une durée maximale de trois jours est conseillée.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 165]'),
  ('MG-ANES-000041-R166', 'La calibration du zéro de référence doit se faire au niveau de l''oreillette droite et sa recalibration doit s''effectuer régulièrement et en cas de doute sur les mesures de pression affichées.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 166]'),
  ('MG-ANES-000041-R167', 'La mesure de SvO2 nécessite une calibration régulière par co-oxymétrie.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 167]'),
  ('MG-ANES-000041-R168', 'Le contrôle radiographique quotidien de la position de la sonde n''est pas nécessaire ; en cas d''anomalie d''obtention du tracé, la radiographie de thorax de contrôle s''impose.', 'Faible', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 168]'),
  ('MG-ANES-000041-R169', 'À l''ablation du cathéter artériel pulmonaire, il faut vérifier son intégrité.', 'Fort', null, 'Champ 6 — « Procédures circulatoires » : vasoactifs et abords vasculaires (6.3 KT artériel pulmonaire) [Réf. 169]'),
  ('MG-ANES-000041-R170', 'La prescription d''une séance d''épuration extra-rénale (EER) intermittente ou continue doit comporter au minimum : la durée ; le type de membrane ; le débit de la pompe à sang ; le type et la posologie de l''anticoagulation du circuit extracorporel ; la perte hydrique horaire ou totale ; le débit de dialysat ; la composition du dialysat en sodium, potassium, calcium, soluté tampon et glucose ; enfin la température du dialysat.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Prescription) [Réf. 170]'),
  ('MG-ANES-000041-R171', 'La structure de la membrane utilisée pour la réalisation d''une EER doit être en cellulose modifiée ou synthétique.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Membrane) [Réf. 171]'),
  ('MG-ANES-000041-R172', 'Au cours de l''EER (intermittente ou continue), la filtration à travers la membrane doit être gérée par un contrôle automatisé.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Filtration) [Réf. 172]'),
  ('MG-ANES-000041-R173', 'Au cours de l''hémofiltration, la fraction de filtration doit être surveillée en continu et la filtration doit être interrompue lors des situations à risque de chute du débit sanguin (nursing).', 'Faible', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Filtration) [Réf. 173]'),
  ('MG-ANES-000041-R174', 'Avant toute mise en route d''une EER et en particulier pour l''hémofiltration, il est nécessaire de : s''assurer de l''absence de coudure du cathéter ; respecter les procédures de gestion des cathéters veineux centraux ; s''assurer de son bon positionnement dans le vaisseau (cliché thoracique) ; s''assurer de sa position adaptée au débit souhaité.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Mise en route) [Réf. 174]'),
  ('MG-ANES-000041-R175', 'La pose et l''entretien des cathéters doivent être conformes aux recommandations du CLIN concernant la prévention du risque infectieux au cours de la mise en place des cathéters veineux centraux.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Cathéters) [Réf. 175]'),
  ('MG-ANES-000041-R176', 'La surveillance d''une séance d''EER chez un patient de réanimation doit comporter au minimum : le monitorage continu de l''ECG et de la fréquence cardiaque ; la mesure rapprochée de la pression artérielle ; le recueil du ratio de filtration (techniques convectives), de la pression de retour veineux et de la pression transmembranaire ; une mesure pluriquotidienne de la température pour l''EER continue ; un bilan hydrique en fin de séance et chaque jour pour l''EER continue ; un ionogramme sanguin en fin de séance et toutes les 12 heures pour l''EER continue ; une évaluation quotidienne (et à chaque modification de posologie) de l''activité systémique de l''anticoagulant pour l''EER continue ; la mesure quotidienne de la gazométrie artérielle et à chaque changement du débit de restitution en bicarbonates au cours de l''hémofiltration continue.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Surveillance) [Réf. 176]'),
  ('MG-ANES-000041-R177', 'Dans le cas particulier d''un traitement antithrombotique au citrate, il faut doser toutes les quatre heures en état stable le calcium ionisé.', 'Faible', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Citrate) [Réf. 177]'),
  ('MG-ANES-000041-R178', 'La sécurisation de l''EER continue et intermittente nécessite, en sus de la surveillance clinique déjà décrite, la mise en place d''une procédure écrite, facilement disponible.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Procédure) [Réf. 178]'),
  ('MG-ANES-000041-R179', 'Cette procédure doit comporter, en sus de la surveillance déjà décrite, la description des techniques de montage et de purge du circuit extracorporel, des techniques de branchement et de débranchement, des paramètres de surveillance du circuit, et du choix de la composition des solutions pour dialyse et hémofiltration et de leur remplacement en cours de traitement.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Procédure) [Réf. 179]'),
  ('MG-ANES-000041-R180', 'Une procédure de désinfection interne des générateurs entre les séances d''hémodialyse doit être mise en place.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Générateurs) [Réf. 180]'),
  ('MG-ANES-000041-R181', 'Les responsables d''un service de réanimation dans lequel sont réalisées des séances d''hémodialyse par un générateur fabriquant un dialysat à partir de l''eau de distribution publique doivent faire partie des acteurs impliqués dans le processus de gestion de la qualité de l''eau.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Qualité de l''eau) [Réf. 181]'),
  ('MG-ANES-000041-R182', 'Un tel service doit disposer d''une procédure d''alerte en cas de non-conformité chimique ou microbiologique de l''eau pour hémodialyse.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Qualité de l''eau) [Réf. 182]'),
  ('MG-ANES-000041-R183', 'La recherche d''un résidu de solution désinfectante dans le dialysat doit être systématique avant tout branchement d''une séance d''hémodialyse réalisée par un tel générateur.', 'Fort', null, 'Champ 7 — Sécurisation des procédures d''épuration extra-rénale (EER — Qualité de l''eau) [Réf. 183]'),
  ('MG-ANES-000041-R184', 'Tout service de réanimation pédiatrique devrait disposer d''un tableau de dilution des catécholamines précisant la correspondance entre le débit (mL/h) et la dose (µg/min).', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 184]'),
  ('MG-ANES-000041-R185', 'Le matériel de monitorage doit être doté d''alarmes adaptées à l''âge de l''enfant.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 185]'),
  ('MG-ANES-000041-R186', 'Lorsqu''une voie fémorale a été mise en place dans un contexte d''urgence, son maintien doit être reconsidéré au bout de 48 heures.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 186]'),
  ('MG-ANES-000041-R187', 'Les lignes de perfusion artérielle doivent toujours être raccordées à une tête de pression.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 187]'),
  ('MG-ANES-000041-R188', 'Un matériel spécifique (pompes, tubulures et sondes), adapté et clairement identifié, doit être utilisé pour éviter le risque de confusion entre les perfusions (artérielles ou veineuses) et l''alimentation.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 188]'),
  ('MG-ANES-000041-R189', 'Une boîte d''intubation pédiatrique doit comporter des lames droites et des lames courbes de toutes les tailles existantes.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 189]'),
  ('MG-ANES-000041-R190', 'L''usage de l''aspiration en système clos doit être strictement limité aux situations où le dérecrutement a des conséquences significatives et persistantes sur l''oxygénation.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 190]'),
  ('MG-ANES-000041-R191', 'Tout pôle de réanimation pédiatrique doit être équipé de masques de ventilation manuelle adaptés à la taille de l''enfant.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 191]'),
  ('MG-ANES-000041-R192', 'Tout service de réanimation pédiatrique doit pouvoir réaliser des épurations extra-rénales.', 'Faible', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 192]'),
  ('MG-ANES-000041-R193', 'Les techniques d''EER (cathéters, moniteur, volume extracorporel, débit) doivent être adaptées à la taille de l''enfant.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 193]'),
  ('MG-ANES-000041-R194', 'La dialyse péritonéale est une méthode d''EER qui reste utilisable en réanimation pédiatrique.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 194]'),
  ('MG-ANES-000041-R195', 'Le maintien de l''expertise du personnel pédiatrique en technique d''EER fait partie d''une formation continue spécifique.', 'Fort', 'Pédiatrie', 'Champ 8 — Spécificités pédiatriques (Pédiatrie) [Réf. 195]'),
  ('MG-ANES-000041-R196', 'L''administration de corticoïdes par voie IV au moins six heures avant l''extubation peut être proposée.', 'Indécision', null, 'Zone d''indécision — 3 propositions (ni accord ni désaccord) (Extubation) [Réf. 196]'),
  ('MG-ANES-000041-R197', 'Si une extubation est prévue, il peut être proposé d''utiliser un guide échangeur pour faciliter la réintubation éventuelle.', 'Indécision', null, 'Zone d''indécision — 3 propositions (ni accord ni désaccord) (Extubation) [Réf. 197]'),
  ('MG-ANES-000041-R198', 'Lorsqu''il est réalisé une déplétion chez un patient à risque, il est nécessaire de mettre en place un monitorage de la précharge ventriculaire adapté aux conditions du patient.', 'Indécision', null, 'Zone d''indécision — 3 propositions (ni accord ni désaccord) (Déplétion) [Réf. 198]')) as v(code, statement, grade, population, source_section)
where d.source_url = 'https://sfar.org/securisation-des-procedures-a-risques-en-reanimation-risque-infectieux-exclu/'
on conflict (recommendation_code) do nothing;
