-- Migration : Urgences obstétricales extrahospitalières — RFE SFAR/SFMU,
-- avec CNGOF, Collège national des sages-femmes, GFRUP. Groupe de travail
-- présidé par G. Bagou (SFAR/SFMU), secrétaire V. Hamel. 9 chapitres
-- traités indépendamment. Recommandations validées au 3e trimestre 2010,
-- publiées Ann Fr Anesth Reanim 2012;31:652-665.
-- Source : rfe-sfar-website/build/content_urgences_ob_extrahosp.json (2001
-- lignes JSON — la fiche la plus volumineuse du corpus migré à ce jour).
--
-- MÉTHODOLOGIE — GRADE annoncé mais littérature spécifique au champ peu
-- abondante : AUCUN grade individuel 1+/2+/A/B/C n'est utilisé — chaque
-- item a été coté par vote Delphi (2 tours) et correspond systématiquement
-- à un Accord fort (hors très rares situations sans consensus, non
-- détaillées par la source). `grade` = 'AE' sur toutes les lignes migrées
-- (accord fort par Delphi, cohérent avec la convention déjà utilisée pour
-- `thrombectomie`/0082, `plyo_transfusion`/0083, `brule_grave`/0086).
--
-- STRUCTURE ET ATOMISATION : la source présente son contenu en tableaux
-- "Thème | Détail" (pas de R1/R2 numérotés), un par chapitre — chaque ligne
-- "Thème" de ces tableaux est migrée comme une recommandation atomique
-- distincte, `condition_topic` portant le libellé du thème et `source_section`
-- le chapitre d'origine. 8 des 9 chapitres sont couverts (chapitre 9 —
-- formation/évaluation des pratiques — résumé en une ligne, cohérent avec
-- le traitement condensé que la source elle-même lui réserve, disclosed
-- dans son propre panneau de portée).
--
-- EXCLUSIONS EXPLICITES (disclosed, pas un oubli — cohérent avec le
-- principe déjà appliqué à `insuffisance_analgesie_cesarienne`/0096 et
-- `sauv`/0084) :
-- 1. Cellules purement épidémiologiques/étiologiques ("Enjeu", "Étiologies
--    principales", "Facteurs de risque") : contexte descriptif, pas un
--    énoncé "il faut faire X".
-- 2. Tableau 1 (signes évoquant une urgence par terme) et Tableau 2
--    (diagnostic différentiel placenta prævia/HRP) : tableaux de référence
--    diagnostique différentielle, pas des recommandations d'action.
-- 3. Fig. 1 (algorithme HPP) et Fig. 2 (algorithme de titration
--    antihypertensive) : leur contenu cliniquement actionnable est déjà
--    porté par les lignes `recommendations` issues des tableaux "Thème |
--    Détail" adjacents (ex. Fig.1 "mesures immédiates" = même contenu que
--    la ligne "Prévention"/"Ocytocine après délivrance" ; Fig.1 "atonie
--    utérine"/"lésion de la filière génitale" = mêmes gestes que les
--    lignes homonymes du tableau suivant) — reproduire les deux formes
--    (figure + tableau) créerait un doublon, pas une couverture
--    supplémentaire. Les seuils de titration antihypertensive propres à
--    Fig.2 (non répétés ailleurs) sont en revanche intégralement repris
--    dans une ligne dédiée ci-dessous.
-- 4. Tableau 3 (4 groupes d'aide à la décision par âge gestationnel,
--    traumatisme) et Tableau 4 (3 classes de vecteur de transport, MAP) :
--    consolidés chacun en une seule ligne `recommendations` (classification
--    décisionnelle actionnable, mais dont les 4/3 branches forment un seul
--    arbre de décision cohérent, pas 4/3 recommandations indépendantes).
--
-- ⚠️ DISCLOSURE — 2 CORRECTIONS D'UNITÉ DÉJÀ FAITES PAR LE CONTENU
-- CONSTRUIT LUI-MÊME (reproduites telles quelles, pas une nouvelle
-- correction de cette migration) : (1) posologie du sulprostone imprimée
-- "100 à 500 mg/h" dans la source — incompatible avec un usage clinique,
-- lue et corrigée en 100-500 µg/h (artefact d'extraction PDF "µ"→"m",
-- même classe que documentée dans `fiche_sujet_age_esf.py`) ; (2) seuil de
-- créatininémie de la prééclampsie sévère imprimé "135 mmol/L" dans la
-- source — incompatible avec la survie, lu et corrigé en 135 µmol/L, même
-- classe d'artefact. Les deux corrections sont conservées telles quelles
-- dans les statements concernés ci-dessous, avec mention du correctif.
--
-- ⚠️ DISCLOSURE — DIVERGENCE DE FORMULATION NON RÉCONCILIÉE : le texte
-- ("10 UI en IVD lente, renouvelées et/ou complétées par un débit de 5 à
-- 10 UI/h, sans dépasser 40 UI au total") et la Fig. 1 ("10 UI en 20 min ±
-- bolus de 5 UI, maximum 40 UI") expriment le même schéma d'ocytocine
-- post-délivrance de façon différente — les deux formulations sont
-- disclosed dans la ligne concernée, aucune retenue comme "la bonne".
--
-- SOCIÉTÉS : GFRUP ne figure pas dans le seed Annexe B (vérifié contre la
-- liste complète des 18 sociétés) — non lié. SFAR, SFMU et CNGOF, toutes
-- trois présentes dans le seed, sont liées en `document_societies`. Le
-- Collège national des sages-femmes n'est pas une société médicale au
-- sens du seed — non lié comme société, mais la specialty `sage_femme_
-- maieuticienne` est retenue ci-dessous en reconnaissance de sa
-- coautorité.
--
-- SOURCE_URL / PDF_URL : `library_final.json` (recherche "Urgences
-- Obstétricales Extrahospitalières" — exactement 1 correspondance) donne
-- `href`/`direct_pdf_url`, `exact_date` = "2010" (année seule) —
-- `publication_date` = 2010-01-01 (convention année seule, cohérente avec
-- "validées au 3e trimestre 2010" du contenu construit ; distincte de la
-- date de publication en revue, 2012, non confondue).
--
-- `specialties` : `anesthesie_reanimation`, `medecine_d_urgence` (SFMU
-- co-autrice, régulation Samu/Smur au cœur du document), `gynecologie_
-- obstetrique` (CNGOF co-auteur, sujet obstétrical central), `pediatrie`
-- (prise en charge du nouveau-né, chapitre dédié) et `sage_femme_
-- maieuticienne` (Collège national des sages-femmes coauteur, sages-femmes
-- actrices centrales de l'accouchement inopiné).

insert into public.documents (title, doc_type, original_language, publication_date, source_url, pdf_url, grading_system, freshness_status)
values (
  'Urgences obstétricales extrahospitalières',
  'RFE', 'fr', '2010-01-01',
  'https://sfar.org/urgences-obstetricales-extrahospitalieres/',
  'https://sfar.org/wp-content/uploads/2015/10/2_AFAR_Urgences-Obstetricales-Extrahospitalieres.pdf',
  'GRADE annoncé mais littérature spécifique peu abondante : aucun grade individuel 1+/2+/A/B/C — chaque item coté par vote Delphi (2 tours), Accord fort quasi systématique (hors rares situations sans consensus, non détaillées). 9 chapitres traités indépendamment ; 8 chapitres cliniques migrés en recommandations atomiques (tableaux "Thème/Détail" de la source, une ligne par thème), chapitre 9 (formation/EPP/réseaux) résumé en une ligne, cohérent avec le traitement condensé de la source elle-même. 2 corrections d''unité disclosed par le contenu construit (sulprostone mg/h→µg/h, créatininémie mmol/L→µmol/L, artefacts d''extraction PDF).',
  'a_jour'
)
on conflict (source_url) do nothing;

insert into public.document_societies (document_id, society_id)
select d.id, s.id from public.documents d, public.societies s
where d.source_url = 'https://sfar.org/urgences-obstetricales-extrahospitalieres/'
  and (s.acronym, s.country_or_region) in (('SFAR', 'France'), ('SFMU', 'France'), ('CNGOF', 'France'))
on conflict do nothing;

insert into public.document_specialties (document_id, specialty_id)
select d.id, s.id from public.documents d, public.specialties s
where d.source_url = 'https://sfar.org/urgences-obstetricales-extrahospitalieres/'
  and s.slug in ('anesthesie_reanimation', 'medecine_d_urgence', 'gynecologie_obstetrique', 'pediatrie', 'sage_femme_maieuticienne')
on conflict do nothing;

insert into public.recommendations (recommendation_code, document_id, statement, grade, condition_topic, source_section, source_url, status)
select v.code, d.id, v.statement, v.grade, v.condition_topic, v.source_section,
  'https://sfar.org/urgences-obstetricales-extrahospitalieres/',
  'draft'
from public.documents d, (values
  ('MG-ANES-000099-R01', 'Le 15 (Samu) est le seul numéro à composer pour toute urgence obstétricale extrahospitalière (hors transferts interhospitaliers).', 'AE', 'Numéro d''appel unique', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R02', '3e trimestre ou post-partum précoce → régulation prioritaire par un médecin urgentiste. Enfant né ou accouchement en cours → départ réflexe d''une équipe Smur + régulation médicale prioritaire.', 'AE', 'Priorisation en régulation', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R03', 'Utilisation recommandée des scores de Malinas, SPIA et Prémat-SPIA (avant 33 SA) — leur association est recommandée pour leur complémentarité.', 'AE', 'Scores d''aide à la régulation', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R04', 'Orienter vers une maternité adaptée au plateau technique requis ; grossesse à bas risque → maternité choisie par la patiente ; urgence vitale maternelle → maternité la plus proche quel que soit le terme.', 'AE', 'Orientation vers la maternité', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R05', 'La décision d''accoucher sur place vs. transporter repose sur l''évaluation de la rapidité de dilatation (2 touchers vaginaux à 10 min d''intervalle) ; dilatation complète + envie irrépressible de pousser → accouchement sur place.', 'AE', 'Décision accoucher sur place vs. transporter', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R06', 'Transport au 2e/3e trimestre : décubitus latéral, ceinturée — le décubitus dorsal est proscrit. Voie veineuse périphérique systématique.', 'AE', 'Transport de la parturiente', 'Chapitre 1 — Recours au Samu centre 15'),
  ('MG-ANES-000099-R07', 'Favoriser les positions d''hyperflexion des cuisses sur l''abdomen. Ne débuter les efforts expulsifs que lorsque la présentation commence à apparaître à la vulve (garantie d''une dilatation complète).', 'AE', 'Position et efforts expulsifs', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R08', 'Pas d''épisiotomie systématique. Médiolatérale, au moment d''une contraction, réservée à : présentation par le siège chez une primipare, indications fœtales d''accélération de l''expulsion.', 'AE', 'Épisiotomie', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R09', 'Une fois la tête dégagée, vérifier un circulaire du cordon ; si serré et gênant, clamper et sectionner entre 2 pinces avant de reprendre les efforts expulsifs pour l''épaule antérieure.', 'AE', 'Dégagement / circulaire du cordon', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R10', 'Prévention de l''HPP, 4 règles : vessie vide ; utérus vide ; utérus contracté (massage utérin + ocytocine) ; compensation volémique rapide. Le clampage précoce du cordon y participe également.', 'AE', 'Prévention de l''HPP (4 règles)', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R11', '5 UI d''ocytocine en IVD lente à la sortie complète de l''enfant, au plus tard dans la minute suivant l''expulsion ; délivrance attendue dans les 30 min ; massage utérin répété (séquences > 15 s) jusqu''à la prise en charge en maternité.', 'AE', 'Délivrance dirigée', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R12', 'MEOPA inhalé possible pour l''analgésie de l''accouchement inopiné ; infiltration locale du périnée recommandée en cas d''épisiotomie.', 'AE', 'Analgésie de l''accouchement inopiné', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R13', 'Accouchement par le siège : attendre l''apparition du siège à la vulve avant les efforts expulsifs, exclusivement pendant les contractions — ne jamais tirer sur un siège. 4 gestes : épisiotomie d''indication large, faire tourner le dos en avant, manœuvre de Lovset si relèvement des bras, technique de Mauriceau si rétention de la tête dernière.', 'AE', 'Accouchement par le siège', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R14', 'Dystocie des épaules : le plus souvent une fausse dystocie → manœuvre de Mac Roberts.', 'AE', 'Dystocie des épaules', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R15', 'Procidence d''un bras : incompatible avec l''accouchement par voie basse → transport rapide en décubitus latéral sous oxygène vers la maternité la plus proche, accueil organisé au bloc opératoire obstétrical.', 'AE', 'Procidence d''un bras', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R16', 'Procidence du cordon (urgence vitale) : si le cordon bat, refouler la présentation (poing ou 2 doigts intravaginaux, sans comprimer le cordon), position de Trendelenburg + décubitus latéral genoux contre poitrine, tocolyse IV pour bloquer les contractions, transport le plus rapide possible.', 'AE', 'Procidence du cordon', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R17', 'Grossesse gémellaire : situation à haut risque (anoxie du 2e jumeau, HPP) — décision transport vs. accouchement sur place au cas par cas ; demande de renfort recommandée si accouchement hors maternité.', 'AE', 'Grossesse gémellaire', 'Chapitre 2 — Accouchement inopiné extrahospitalier : mécanique'),
  ('MG-ANES-000099-R18', 'Prise en charge du nouveau-né, 5 règles dans l''ordre : clamper/couper/vérifier le cordon (2 artères, 1 veine) ; prévenir l''hypothermie ; évaluer l''état clinique ; prévenir l''hypoglycémie (<2,2 mmol/L à 30 min de vie) ; favoriser le peau-à-peau.', 'AE', 'Séquence des 5 règles de prise en charge néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R19', 'Section du cordon : stérile, entre 2 clamps, à ≥10 cm de l''ombilic.', 'AE', 'Section du cordon', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R20', 'Lutte contre l''hypothermie néonatale : sécher l''enfant ou utiliser un sac en polyéthylène sans séchage préalable ; toujours couvrir la tête d''un bonnet ; peau-à-peau privilégié ; décubitus latéral, liberté des VAS, surveillance rapprochée.', 'AE', 'Lutte contre l''hypothermie néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R21', 'Évaluation clinique néonatale : tonus, ventilation, couleur et/ou SpO2, puis fréquence cardiaque — le score d''Apgar n''a pas de valeur décisionnelle pour la réalisation d''un geste. Stimulation possible pour déclencher la respiration, sans jamais secouer l''enfant.', 'AE', 'Évaluation clinique néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R22', 'Hypoglycémie néonatale : sérum glucosé à 10% préférentiellement per os à la seringue si nouveau-né conscient et terme >34 SA. Le sérum glucosé à 30% est toujours contre-indiqué. Mise au sein recommandée si la mère le souhaite.', 'AE', 'Prise en charge de l''hypoglycémie néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R23', 'Nouveau-né sans signe de vie : prise en charge selon les recommandations ILCOR ; demande de renfort recommandée.', 'AE', 'Nouveau-né sans signe de vie', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R24', 'Pas de désobstruction systématique des VAS si l''enfant va bien. Si nécessaire : aspiration à dépression réglable <150 mmHg (200 cmH2O).', 'AE', 'Désobstruction des VAS néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R25', 'La qualité de la ventilation prime sur la FiO2. Chez le prématuré, débuter avec une FiO2 de 0,30 à 0,40, objectif SpO2 85-95%. Intubation de sauvetage orale possible sans sédation, mais une ventilation au BAVU + masque reste préférable à des tentatives d''intubation répétées et maladroites.', 'AE', 'Ventilation et oxygénation néonatales', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R26', 'RCP néonatale : massage cardiaque externe + ventilation efficace dès bradycardie <60/min — ratio 2 ventilations pour 6 compressions thoraciques.', 'AE', 'RCP néonatale', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R27', 'Le certificat d''accouchement/naissance est rédigé par le médecin ou la sage-femme ayant pratiqué l''accouchement ou sectionné le cordon ; le médecin s''assure de la déclaration à l''état civil dans les 3 jours ouvrables (4 si dimanche ou jour férié).', 'AE', 'Certificat d''accouchement / naissance', 'Chapitre 2 — Prise en charge du nouveau-né en extrahospitalier'),
  ('MG-ANES-000099-R28', 'Toute métrorragie chez une femme enceinte au 2e/3e trimestre doit être régulée par un médecin urgentiste (interrogatoire : terme, prævia connu, HTA connue, couleur/abondance du saignement, douleurs/contractions, mouvements fœtaux). En l''absence de prævia connu, évoquer un HRP jusqu''à preuve du contraire.', 'AE', 'Régulation des métrorragies du 2e/3e trimestre', 'Chapitre 3 — Hémorragies du 2e et 3e trimestre'),
  ('MG-ANES-000099-R29', 'Envoi systématique d''une équipe Smur à la moindre suspicion d''HRP ou de prævia hémorragique ; décubitus latéral ; bloc opératoire/obstétricien/anesthésiste prévenus et produits sanguins disponibles dès l''arrivée ; remplissage par cristalloïdes ou amidons ayant l''AMM chez la femme enceinte ; oxygénothérapie de principe.', 'AE', 'Prise en charge générale des hémorragies du 2e/3e trimestre', 'Chapitre 3 — Hémorragies du 2e et 3e trimestre'),
  ('MG-ANES-000099-R30', 'Placenta prævia : toucher vaginal formellement contre-indiqué si prævia connu/suspecté. Tocolyse possible en préhospitalier si CU + transport long + saignement important (concertation obstétricien). Transport en décubitus latéral. Lieu d''accouchement = maternité la plus proche (idéalement multidisciplinaire) si prævia recouvrant hémorragique ou suspicion d''accreta.', 'AE', 'Placenta prævia', 'Chapitre 3 — Hémorragies du 2e et 3e trimestre'),
  ('MG-ANES-000099-R31', 'Hématome rétroplacentaire (HRP) : aucun examen ne doit retarder l''extraction fœtale si le fœtus est vivant ; transport rapide vers la maternité la plus proche que l''enfant soit vivant ou décédé.', 'AE', 'Hématome rétroplacentaire', 'Chapitre 3 — Hémorragies du 2e et 3e trimestre'),
  ('MG-ANES-000099-R32', 'Le retentissement clinique de l''HPP peut être tardif et brutal (une perte de 1000 mL peut être bien tolérée) — une surveillance attentive systématique après tout accouchement est requise. Critères de gravité : hémorragie intarissable, sang incoagulable, signes de choc.', 'AE', 'Surveillance systématique et critères de gravité de l''HPP', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R33', 'Prévention de l''HPP avant délivrance : délivrance dirigée (5 UI d''ocytocine IVD lente, IM à défaut, dans la minute suivant la naissance) ; une traction douce sur le cordon associée au refoulement de l''utérus est un facteur préventif reconnu, mais il ne faut jamais tirer fermement sur le cordon sans formation préalable.', 'AE', 'Prévention de l''HPP avant délivrance', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R34', 'Ocytocine après délivrance (utérus vide) : 10 UI en IVD lente, renouvelées et/ou complétées par un débit de perfusion IV de 5 à 10 UI/h, sans dépasser 40 UI au total. (Divergence de formulation disclosed : la Fig. 1 de la source exprime ce même schéma comme "10 UI en 20 min ± bolus de 5 UI, maximum 40 UI" — non réconciliée.)', 'AE', 'Ocytocine après délivrance', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R35', 'Si le placenta est incomplet et dans l''attente d''une révision utérine, il ne faut pas recourir à l''ocytocine — sauf en cas de transport long avec une hémorragie objectivée.', 'AE', 'Contre-indication à l''ocytocine', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R36', 'Si la délivrance n''a pas eu lieu et le décollement placentaire n''est pas obtenu : délivrance artificielle sous anesthésie générale avec intubation si l''opérateur est formé ; si l''opérateur n''est pas formé, transport rapide directement, sans attendre les mesures immédiates.', 'AE', 'Conduite si délivrance non faite', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R37', 'Si l''hémorragie persiste malgré les mesures immédiates : en cas d''atonie utérine, poursuivre ocytocine (maximum 40 UI) + massage utérin continu, discuter une révision utérine sous anesthésie générale avec intubation si possible, puis administrer du sulprostone (100 à 500 µg/h — correction disclosed, la source imprime "100 à 500 mg/h", dose incompatible avec un usage clinique, probable artefact d''extraction "µ"→"m"), puis transport rapide.', 'AE', 'Atonie utérine persistante — conduite', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R38', 'Si l''hémorragie persiste malgré les mesures immédiates et qu''une lésion de la filière génitale (épisiotomie, périnée, vagin) est identifiée : méchage ou compression maintenus jusqu''à la prise en charge hospitalière, puis transport rapide.', 'AE', 'Lésion de la filière génitale — conduite', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R39', 'Les gestes endo-utérins (délivrance artificielle, révision utérine) imposent une anesthésie avec induction en séquence rapide et intubation, maintenues jusqu''à la prise en charge hospitalière spécialisée. Asepsie rigoureuse et antibioprophylaxie à large spectre systématiques.', 'AE', 'Anesthésie pour gestes endo-utérins', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R40', 'Les produits sanguins labiles sont utilisables en préhospitalier (procédures de transfusion en urgence vitale immédiate) sans retarder le transport ; acheminer les documents immuno-hématologiques avec la patiente.', 'AE', 'Produits sanguins labiles en préhospitalier', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R41', 'Le transfert interhospitalier pour HPP grave (ex. en vue d''une embolisation) justifie une décision réfléchie et médicalisée, concertée entre équipes d''origine et receveuse. Un état hémodynamique instable malgré une prise en charge bien conduite est une contre-indication au transport et impose une chirurgie d''hémostase sur place, si possible conservatrice ; la réparation des lésions de la filière génitale doit être réalisée avant le transfert.', 'AE', 'Transfert interhospitalier pour HPP grave', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R42', 'HPP tardive (>3 jours) : douleur pelvienne + fièvre + lochies malodorantes + utérus mou non involué → évoquer une endométrite hémorragique. Orientation vers l''obstétricien référent, sauf urgence vitale immédiate exceptionnelle.', 'AE', 'HPP tardive', 'Chapitre 4 — Hémorragie du post-partum (HPP)'),
  ('MG-ANES-000099-R43', 'Port correct d''une ceinture de sécurité homologuée à 3 points chez la femme enceinte ; son association aux airbags améliore la sécurité.', 'AE', 'Prévention des traumatismes — ceinture de sécurité', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R44', 'En régulation, rechercher systématiquement : grossesse et terme, mécanisme et cinétique du traumatisme, métrorragie, contractions utérines, rupture des membranes. Penser à une possible grossesse chez toute femme en âge de procréer traumatisée. Rechercher des violences domestiques si le mécanisme n''est pas évident.', 'AE', 'Régulation du traumatisme chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R45', 'Brûlures chez la femme enceinte : majorer les formules de compensation hydrique (surface corporelle maternelle augmentée) ; interruption de grossesse à envisager si surface corporelle brûlée >50%.', 'AE', 'Brûlures chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R46', 'Intoxication oxycarbonée : oxygénothérapie normobare impérative si symptômes ou HbCO positif, quel que soit le terme (retentissement fœtal retardé, plus long et plus sévère que le retentissement maternel). Oxygénothérapie hyperbare systématique, organisée très précocement avec les centres d''hyperbarie et les obstétriciens.', 'AE', 'Intoxication oxycarbonée chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R47', 'Électrisation chez la femme enceinte : surveillance fœtale prolongée 24 à 48h si le courant passe entre un membre supérieur et un membre inférieur (lésions fœtales possibles retardées).', 'AE', 'Électrisation chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R48', 'Aide à la décision selon l''âge de grossesse et l''état clinique maternel après traumatisme (4 groupes) : test positif chez une femme en période d''activité génitale → prise en charge maternelle ; terme ≤24 SA (fœtus non viable) → adaptation diagnostique/thérapeutique ; terme >24 SA (fœtus viable) → prise en charge maternelle ET fœtale (monitorage, échographie, extraction prématurée à discuter) ; détresse maternelle ou inefficacité circulatoire → délais très courts, césarienne post-mortem à discuter si traitement inefficace.', 'AE', 'Classification décisionnelle par âge gestationnel (traumatisme)', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R49', 'Suivre les recommandations de monitorage du traumatisé grave, en tenant compte des modifications ECG physiologiques de la grossesse et de l''hémodilution physiologique pour l''interprétation de l''Hb. Cardiotocographe portable utilisable en préhospitalier — une souffrance fœtale est possible malgré un état maternel rassurant, réévaluation fréquente nécessaire.', 'AE', 'Monitorage du traumatisme chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R50', 'Décubitus latéral systématique à toutes les étapes jusqu''au bloc opératoire pour prévenir la compression cave ; si la patiente ne peut être mobilisée, surélever une hanche (droite de préférence) ou récliner manuellement l''utérus vers la gauche.', 'AE', 'Prévention de la compression cave', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R51', 'Débuter un remplissage précoce avant les signes cliniques d''hypovolémie (perte possible de 30-35% de la volémie sans signe clinique). Indications d''oxygénothérapie larges (sensibilité fœtale à l''hypoxie). Respecter l''hyperventilation physiologique de la grossesse (PaCO2 ≈32 mmHg) en ventilation mécanique.', 'AE', 'Remplissage et oxygénothérapie du traumatisme chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R52', 'Rechercher systématiquement après traumatisme : décollement placentaire (fréquent même pour un traumatisme mineur, parfois retardé de 24-48h) ; rupture splénique ; rupture utérine (surtout 3e trimestre/traumatisme violent). Pas de toucher vaginal chez une femme enceinte traumatisée.', 'AE', 'Lésions à rechercher systématiquement après traumatisme', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R53', 'Pas de contre-indication à l''analgésie chez la femme enceinte traumatisée : palier 1 = paracétamol ; palier 2 = dextropropoxyphène ; palier 3 = morphine (risques de dépression respiratoire et de sevrage néonatal si extraction). MEOPA utilisable.', 'AE', 'Analgésie du traumatisme chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R54', 'Remplissage par cristalloïdes ± amidons ayant l''AMM chez la femme enceinte. Si transfusion de globules rouges nécessaire : concentrés érythrocytaires O rhésus négatif, si possible Kell négatif. Catécholamines en complément d''un remplissage bien conduit, malgré le risque de détournement partiel de la circulation fœtale.', 'AE', 'Remplissage et transfusion du traumatisme chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R55', 'Intubation trachéale chez la femme enceinte traumatisée : toujours considérée comme difficile et à estomac plein. Induction en séquence rapide avec manœuvre de Sellick systématique. Voie nasotrachéale à éviter. Sondes plus petites (diamètre 5,5 à 7). Avoir à disposition une technique alternative de contrôle des voies aériennes.', 'AE', 'Intubation trachéale chez la femme enceinte', 'Chapitre 5 — Traumatismes chez la femme enceinte'),
  ('MG-ANES-000099-R56', 'Définitions : HTA gravidique = PAS ≥140 et/ou PAD ≥90 mmHg entre la 20e SA et le 42e jour post-partum. Prééclampsie = HTA gravidique + protéinurie >0,3 g/24h. Prééclampsie sévère = prééclampsie + au moins un critère parmi : HTA sévère (PAS≥160 et/ou PAD≥110), oligurie <500 mL/24h ou créatininémie >135 µmol/L (correction disclosed, la source imprime "135 mmol/L", valeur incompatible avec la survie) ou protéinurie >5 g/24h, OAP ou barre épigastrique persistante ou HELLP, éclampsie ou troubles neurologiques persistants, thrombopénie <100 G/L, HRP, retentissement fœtal. Éclampsie = crise convulsive tonicoclonique en contexte d''HTA gravidique. HELLP = hémolyse + cytolyse hépatique + thrombopénie.', 'AE', 'Définitions HTA gravidique / prééclampsie / éclampsie / HELLP', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R57', 'Le diagnostic préhospitalier de prééclampsie est principalement clinique ; mesure de la PA au repos, en décubitus latéral ou en position semi-assise. L''absence d''œdème localisé ou de prise de poids brutal n''élimine pas le diagnostic.', 'AE', 'Diagnostic préhospitalier de la prééclampsie', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R58', 'Signes d''alerte à rechercher : HTA sévère ; signes d''éclampsie imminente (céphalées rebelles, troubles visuels, ROT polycinétiques) ; signes neurologiques évocateurs d''AVC ; signes de choc, contracture utérine, métrorragies (HRP) ; dyspnée/OAP ; douleur épigastrique (HELLP) ; oligurie/anurie.', 'AE', 'Signes d''alerte de la prééclampsie sévère', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R59', 'Envoi rapide d''une équipe médicale recommandé si suspicion de forme sévère/compliquée. Orientation selon des critères maternels (USI obstétricale ou réanimation adulte) ET fœtaux (maternité de type adapté à l''âge gestationnel).', 'AE', 'Envoi d''équipe et orientation en cas de prééclampsie sévère', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R60', 'Transfert in utero indiqué vers une maternité de type adapté si signes de sévérité/complications entre 24 et 36 SA. Contre-indications : HRP connu/suspecté, instabilité hémodynamique, HTA non contrôlée, complication systémique (OAP, éclampsie, hématome sous-capsulaire du foie) — mesures thérapeutiques sur site avant TIU ultérieur. Anomalies sévères du RCF → extraction en urgence sur place quel que soit le type de maternité.', 'AE', 'TIU — indications et contre-indications en cas de prééclampsie', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R61', 'FC, SpO2, FR, PA non invasive, et capnométrie si ventilation mécanique — monitorage recommandé pendant toute la prise en charge préhospitalière de la prééclampsie.', 'AE', 'Monitorage de la prééclampsie', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R62', 'Traitement antihypertenseur à débuter si PAS>160 ou PAD>110 mmHg, par titration : si PAS>180 ou PAM>140 mmHg, traitement d''attaque par nicardipine 0,5-1 mg IV puis 4-7 mg en 30 min ; sinon traitement d''entretien par nicardipine 1-6 mg/h IV ou labétalol 5-20 mg/h IV. Réévaluation après 30 min : si PAS<140 et PAM<100, diminuer/arrêter ; si 140<PAS<160 ou 100<PAM<120, poursuivre l''entretien ; si PAS>160 ou PAM>120, associer nicardipine 6 mg/h + labétalol 5-20 mg/h (ou clonidine 15-40 µg/h si contre-indication aux bêta-bloquants) ; en cas d''effets secondaires, réduire la nicardipine et associer labétalol ou clonidine. Réévaluation après 30 minutes puis chaque heure dans tous les cas. Ne pas faire descendre la PAM sous 100 mmHg ni la PAS sous 140 mmHg.', 'AE', 'Protocole de titration antihypertensive (seuils et posologies)', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R63', 'Une expansion volémique est possible en cas d''hypotension significative à l''instauration du traitement antihypertenseur, associée au décubitus latéral — prudente (risque d''OAP), reposant sur les cristalloïdes.', 'AE', 'Expansion volémique lors du traitement antihypertenseur', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R64', 'Une détresse respiratoire est possible chez la patiente prééclamptique, pouvant nécessiter une intubation — risque majoré d''intubation difficile et de poussée hypertensive à l''induction, à anticiper et prévenir.', 'AE', 'Détresse respiratoire chez la patiente prééclamptique', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R65', 'Traitement de l''éclampsie : mesures générales de la crise convulsive + sulfate de magnésium 2 à 4 g IV lente puis entretien IV continu 1 g/h, + correction de l''HTA si présente. Récidive → 2e dose de 1,5-2 g. Les benzodiazépines injectables et la phénytoïne sont utilisables en préhospitalier mais moins efficaces que le sulfate de magnésium.', 'AE', 'Traitement de l''éclampsie', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R66', 'Prévention primaire par sulfate de magnésium indiquée devant l''apparition de troubles neurologiques persistants (céphalées, troubles visuels, ROT polycinétiques) en cas de prééclampsie sévère, en l''absence de contre-indication (insuffisance rénale, pathologie neuromusculaire). Un inhibiteur calcique pour l''HTA ne doit pas retarder le sulfate de magnésium.', 'AE', 'Prévention primaire de l''éclampsie par sulfate de magnésium', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R67', 'Surveillance du sulfate de magnésium : évaluation répétée des ROT, de la fréquence respiratoire et de la conscience. Signes d''hypermagnésémie (ROT diminués/abolis, FR<10-12/min, troubles de conscience) → envisager l''arrêt de la perfusion et l''antagonisation par 1 g de gluconate de calcium IV.', 'AE', 'Surveillance du sulfate de magnésium', 'Chapitre 6 — HTA, prééclampsie, éclampsie'),
  ('MG-ANES-000099-R68', 'Diagnostic de la MAP en régulation : contractions utérines régulières et douloureuses entre la 24e et la 36e SA révolue. Facteurs de risque à rechercher : antécédent d''accouchement prématuré, grossesse multiple, infection maternelle, métrorragies, placenta prævia, malformation utérine, béance cervico-isthmique, hydramnios.', 'AE', 'Diagnostic de la menace d''accouchement prématuré en régulation', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R69', 'Transport en décubitus latéral vers la maternité la plus proche de type adapté à l''âge gestationnel, sauf accouchement imminent justifiant l''envoi d''une équipe médicalisée.', 'AE', 'Transport en cas de MAP', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R70', 'La tocolyse préhospitalière est exceptionnellement initiée, en concertation avec l''équipe obstétricale receveuse ; choix selon les disponibilités locales et les protocoles de réseau.', 'AE', 'Tocolyse préhospitalière', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R71', 'Contre-indications au transport en cas de MAP : risque d''accouchement pendant le transport, souffrance fœtale aiguë patente. Non-indications médicales de TIU : terme <24 SA ou >32 SA, transfert entre établissements de même type.', 'AE', 'Contre-indications et non-indications au transport (MAP)', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R72', 'Éléments objectifs du TIU pour MAP : longueur et ouverture du col par échographie endovaginale, recherche de la fibronectine. Vérifier la réalisation de la 1re cure de corticothérapie de maturation pulmonaire fœtale avant tout transport. Réévaluation de la faisabilité du transport par l''équipe obstétricale au moment du départ.', 'AE', 'Éléments objectifs du TIU pour MAP', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R73', 'Choix du tocolytique : atosiban (antagoniste de l''ocytocine) est le tocolytique de choix en préhospitalier (profil de tolérance favorable). Inhibiteurs calciques hors AMM, risques cardiovasculaires potentiellement graves. Bêtamimétiques : effets indésirables hémodynamiques fréquents, potentiellement graves, contre-indiqués en cas de grossesse gémellaire (éviter aussi les inhibiteurs calciques). Ne jamais associer plusieurs tocolytiques ; ne pas changer de tocolytique efficace lors d''un transfert médicalisé.', 'AE', 'Choix du tocolytique', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R74', 'Surveillance pendant le transport pour MAP : FC et PA systématiquement monitorées, avec rapport de surveillance écrit joint au dossier. Tococardiographie possible lors d''un transport de classe 3.', 'AE', 'Surveillance pendant le transport (MAP)', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R75', 'Choix du vecteur de transport selon l''état de la patiente (circulaire DHOS/01/2006/273), 3 classes : Classe 1 (ambulance simple) — rupture prématurée des membranes isolée, MAP sans tocolyse IV, ou MAP simple avec tocolyse IV par antagoniste de l''ocytocine ; Classe 2 (transport infirmier interhospitalier) — MAP simple avec tocolyse IV (médicalisation à discuter), ou MAP gémellaire avec tocolyse IV par antagoniste de l''ocytocine ; Classe 3 (transport médicalisé Smur) — MAP avec tocolyse IV (médicalisation à discuter selon le tocolytique), ou dilatation du col ≥4 cm et terme <30 SA (à discuter avec le Samu en conférence téléphonique demandeur/receveur).', 'AE', 'Classification du vecteur de transport (MAP)', 'Chapitre 7 — Menace d''accouchement prématuré (MAP)'),
  ('MG-ANES-000099-R76', 'L''organisation des transferts in utero est régionale, intégrée aux réseaux de périnatalité (circulaire DHOS/01/2006/273) — une cellule de périnatalité développe et applique les protocoles consensuels entre Samu, obstétriciens, néonatologues, anesthésistes réanimateurs et sages-femmes, et recherche les places adaptées.', 'AE', 'Organisation régionale des transferts in utero', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R77', 'Le TIU est indiqué en cas d''inadéquation entre la structure d''hospitalisation et la pathologie maternelle/fœtale ; le bénéfice pour l''enfant est d''autant plus élevé que le terme est précoce. Si transport maternel pour pathologie non obstétricale, une surveillance obstétricale adaptée doit être possible dans la structure d''accueil.', 'AE', 'Indication du transfert in utero', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R78', 'Contre-indications fœtales au TIU : anomalies du RCF significatives imposant une extraction sur place en urgence (engagement anticipé du Smur pédiatrique si terme <32 SA ou poids estimé <1500 g).', 'AE', 'Contre-indications fœtales au TIU', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R79', 'Contre-indications maternelles au TIU : risque d''accouchement pendant le transport, suspicion d''HRP, HTA gravidique sévère non contrôlée, instabilité hémodynamique, placenta prævia avec métrorragies actives.', 'AE', 'Contre-indications maternelles au TIU', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R80', 'Règles de terme pour le TIU : pas d''indication avant 24 SA (hors cause non liée à la grossesse) ; au-delà de 32 SA, le terme seul ne justifie pas un transfert vers un type supérieur ; pas d''indication médicale fœtale entre établissements de même type.', 'AE', 'Règles de terme pour le TIU', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R81', 'Pour une MAP, la décision de TIU dépend de 5 éléments : dilatation et longueur du col (évaluée par l''équipe demandeuse par échographie endovaginale), contractions utérines, terme, type de l''établissement demandeur. À partir de 32 SA, une dilatation ≥4 cm est une contre-indication au transfert ; en deçà, l''opportunité se discute selon le type d''établissement et la durée de transport.', 'AE', 'Décision de TIU pour MAP', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R82', 'Orientation par terme pour le TIU : type 2 à partir de 32 SA avec poids fœtal estimé >1500 g ; type 3 pour menace d''accouchement très prématuré (24 SA à 31 SA + 6 j) ou poids estimé <1500 g, grossesse triple.', 'AE', 'Orientation par terme (type de maternité)', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R83', 'La décision de TIU se prend par accord entre le médecin demandeur (présent auprès de la patiente) et le médecin receveur, puis avec le médecin régulateur du Samu et le médecin transporteur du Smur si le transport est médicalisé. L''état clinique est réévalué au départ pour confirmer la faisabilité.', 'AE', 'Décision et modalités du TIU', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R84', 'Pendant le transport in utero : décubitus latéral ceinturé (prévention de la compression cave) ; dossier obstétrical accompagne systématiquement la patiente ; traçabilité écrite de la surveillance, des événements intercurrents et des traitements.', 'AE', 'Surveillance pendant le transport in utero', 'Chapitre 8 — Transferts in utero (TIU) interhospitaliers'),
  ('MG-ANES-000099-R85', 'Formation initiale puis continue recommandée pour tous les professionnels Samu/Smur aux urgences obstétricales préhospitalières (accouchement physiologique et situations complexes), avec un programme d''évaluation des pratiques professionnelles selon une méthode HAS et un développement recommandé de réseaux périnatals régionaux, avec transferts périnatals systématiquement régulés par le Samu.', 'AE', 'Formation, évaluation des pratiques et réseaux (résumé, chapitre condensé par la source elle-même)', 'Chapitre 9 — Formation, évaluation des pratiques, réseaux')
) as v(code, statement, grade, condition_topic, source_section)
where d.source_url = 'https://sfar.org/urgences-obstetricales-extrahospitalieres/'
on conflict (recommendation_code) do nothing;
